import {MATERIALS,MAX,initial,sanitize,speed,capacity,cost,buy,points,START,FINISH,areaAt,level,patrols,overlap,rayBlocked} from './model.js';
const $=id=>document.getElementById(id), canvas=$('world'),ctx=canvas.getContext('2d'),KEY='gamebox.unfinished-business.v1';
let p;try{p=sanitize(JSON.parse(localStorage.getItem(KEY)))}catch{p=initial()}
let mode='menu',selected='invisibility',held=false,skillPointer=null,stickPointer=null,keys=new Set(),input={x:0,y:0},blocks=level(),people=patrols(),ghost={x:240,y:START,face:1},energy=0,runPoints=0,t=0,cam=0,viewH=800,last=0,noticeUntil=0,contact=null,contactTime=0,lastSafe={x:240,y:START},phaseExit=null,seen=0,audio=null,saveFailed=false;
const names={speed:'Movement speed',invisibility:'Invisibility',phase:'Phase',touch:'Touch'},icons={speed:'↗',invisibility:'◌',phase:'◇',touch:'✦'},labels={invisibility:'VANISH',phase:'PHASE',touch:'TOUCH'};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){try{localStorage.setItem(KEY,JSON.stringify(p))}catch{saveFailed=true;}}
function note(s,d=4){$('notice').textContent=s;noticeUntil=performance.now()+d*1000;}
function tone(f=440,d=.12){if(!p.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.6,audio.currentTime+d);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function resetInput(){held=false;skillPointer=null;stickPointer=null;input={x:0,y:0};keys.clear();$('nub').style.transform='';$('skills').hidden=true;$('selector').setAttribute('aria-expanded','false');}
function footer(){return `<div class="footer"><a href="../index.html"><img src="../GameBox%20back%20button.png" alt="Game Box"></a><button class="sound" id="sound">SOUND ${p.sound?'ON':'OFF'}</button></div>`}
function show(html){resetInput();$('overlay').hidden=false;$('overlay').innerHTML=`<div class="menu">${html}</div>`;document.querySelectorAll('[data-start]').forEach(b=>b.onclick=start);$('sound')?.addEventListener('click',()=>{p.sound=!p.sound;save();$('sound').textContent=`SOUND ${p.sound?'ON':'OFF'}`});}
function home(){mode='menu';$('hud').hidden=true;$('controls').hidden=true;show(`<canvas class="brandGhost" id="portrait" width="96" height="110"></canvas><span class="eyebrow">A LITTLE GHOST. A LONG WAY HOME.</span><h1>Unfinished<br><em>Business</em></h1><p class="subtitle">The afterlife is waiting.<br>Try not to be seen on the way.</p><div class="record">BEST ${p.best} · ${p.bank} GHOST POINTS</div><button class="primary" data-start>${p.runs?'Make another escape':'Begin your escape'} →</button><button class="secondary" id="upgrade">Your abilities</button><button class="secondary" id="help">How to play</button>${footer()}`);const c=$('portrait').getContext('2d');drawGhost(c,48,66,5,1,0);$('upgrade').onclick=()=>shop(false);$('help').onclick=help;}
function help(){show(`<span class="eyebrow">THE RULES OF BEING DEAD</span><h2>Keep a low profile.</h2><div class="help"><p><b>Move</b> with the left thumbstick. On a keyboard, use WASD or arrow keys.</p><p><b>Hold Skill</b> to use your selected ability. Tap the arrow above it to switch. Keyboard: Space to use; 1, 2, 3 to select.</p><p>Being seen sends you home. Every attempt earns points for your furthest distance—even if you reach the same spot again.</p><p>Buy speed and longer invisibility. Discover Phase in the house and Touch in the garage. Hold Phase or Touch while moving into an obstacle.</p><p>Only one skill works at a time. Reach the ferry to find your afterlife.</p></div><button class="primary" id="back">Got it</button>`);$('back').onclick=home;}
function description(k){if(k==='speed')return `${speed(p)} → ${speed(p)+11} pace`;if(k==='invisibility')return `${capacity(p).toFixed(2)} → ${(capacity(p)+.65).toFixed(2)} seconds`;if(k==='phase')return `${MATERIALS[p.phase]} → ${MATERIALS[Math.min(7,p.phase+1)]}`;return ['','Curtains → Handles','Handles → Heavy gates','Heavy gates → Shutters','Shutters → Industrial doors','Maximum strength'][p.touch];}
function shop(result=false,win=false){mode='shop';$('controls').hidden=true;show(`<span class="eyebrow">${win?'THE CROSSING IS YOURS':result?'BACK TO THE BEGINNING':'GROW INTO YOUR GHOST'}</span><h2>${win?'Rest, at last.':result?'Somebody saw you.':'A little more spirit.'}</h2>${result?`<div class="stats"><div><strong>+${runPoints}</strong><small>THIS ATTEMPT</small></div><div><strong>${p.bank}</strong><small>GHOST POINTS</small></div><div><strong>${p.best}</strong><small>BEST</small></div></div>`:`<p class="record">${p.bank} GHOST POINTS AVAILABLE</p>`}<div class="upgrades">${Object.keys(MAX).filter(k=>k==='speed'||p[k]>0).map(k=>`<div class="upgrade"><span class="icon">${icons[k]}</span><div><b>${names[k]}</b><small>${p[k]>=MAX[k]?'Fully upgraded':description(k)}</small></div><button class="buy" data-buy="${k}" ${p[k]>=MAX[k]||p.bank<cost(p,k)?'disabled':''}>${p[k]>=MAX[k]?'MAX':cost(p,k)+' GP'}</button></div>`).join('')}</div>${result&&p.runs===1?'<p class="subtitle">Invisibility unlocked. Hold VANISH to disappear briefly. Spend your points to go further.</p>':''}${saveFailed?'<p>Storage unavailable. Keep this tab open to retain progress.</p>':''}<button class="primary" data-start>${win?'Take another journey':'Try again'} →</button><button class="secondary" id="menu">Main menu</button>${footer()}`);document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{if(buy(p,b.dataset.buy)){save();tone(650);shop(result,win)}});$('menu').onclick=home;}
function start(){mode='play';blocks=level();people=patrols();ghost={x:240,y:START,face:1};lastSafe={...ghost};phaseExit=null;runPoints=0;t=0;seen=0;contact=null;contactTime=0;energy=capacity(p);selected='invisibility';cam=START-viewH*.68;resetInput();$('overlay').hidden=true;$('hud').hidden=false;$('controls').hidden=false;updateSkills();note(p.runs?'Every step forward counts.':'Drag the left control to move. Stay out of sight.',4);tone(320);}
function finish(win=false){if(mode!=='play')return;p.bank+=runPoints;p.best=Math.max(p.best,runPoints);p.runs++;if(!p.invisibility)p.invisibility=1;if(win)p.won=true;save();tone(win?880:160,.3);shop(true,win);}
function pause(){if(mode!=='play')return;mode='pause';show(`<span class="eyebrow">TAKE A BREATHER</span><h2>Time stands still.</h2><button class="primary" id="resume">Keep going</button><button class="secondary" id="end">Bank points & return</button>${footer()}`);$('resume').onclick=()=>{mode='play';$('overlay').hidden=true;resetInput()};$('end').onclick=()=>{mode='play';finish()};}
$('pause').onclick=pause;window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function updateSkills(){$('skillWrap').hidden=!p.invisibility;$('selector').hidden=!p.phase;$('skillIcon').textContent=icons[selected];$('skillName').textContent=labels[selected];$('skills').innerHTML=['invisibility','phase','touch'].filter(k=>p[k]).map(k=>`<button data-skill="${k}" class="${k===selected?'selected':''}">${icons[k]} &nbsp; ${names[k]}</button>`).join('');document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{held=false;selected=b.dataset.skill;updateSkills();$('skills').hidden=true;$('selector').setAttribute('aria-expanded','false')});}
$('selector').onclick=()=>{held=false;$('skills').hidden=!$('skills').hidden;$('selector').setAttribute('aria-expanded',String(!$('skills').hidden))};
$('skill').onpointerdown=e=>{if(mode!=='play')return;e.preventDefault();skillPointer=e.pointerId;$('skill').setPointerCapture(e.pointerId);held=true;tone(260,.06)};
for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('skill').addEventListener(ev,e=>{if(e.pointerId===skillPointer){held=false;skillPointer=null}});
$('stick').onpointerdown=e=>{if(mode!=='play'||stickPointer!==null)return;stickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);moveStick(e)};
function moveStick(e){if(e.pointerId!==stickPointer)return;const r=$('stick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),s=Math.min(1,len/36);input={x:len?dx/len*s:0,y:len?dy/len*s:0};$('nub').style.transform=`translate(${input.x*30}px,${input.y*30}px)`;}
$('stick').onpointermove=moveStick;for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(ev,e=>{if(e.pointerId===stickPointer){stickPointer=null;input={x:0,y:0};$('nub').style.transform=''}});
window.addEventListener('keydown',e=>{if(e.code==='Escape'){pause();return}if(mode!=='play')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space')held=true;const k={Digit1:'invisibility',Digit2:'phase',Digit3:'touch'}[e.code];if(k&&p[k]){held=false;selected=k;updateSkills()}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')held=false});
function unlock(k,text){if(p[k])return;p[k]=1;save();updateSkills();note(text,6);tone(750,.25)}
function active(k){return held&&selected===k&&p[k]>0&&(k!=='invisibility'||energy>0)}
function move(dx,dy,dt){const nx=ghost.x+dx,ny=ghost.y+dy,hits=blocks.filter(b=>overlap(nx,ny,b));const phase=active('phase');const blocked=hits.find(b=>!(phase&&p.phase>=b.phase));if(blocked){if(active('touch')&&p.touch>=blocked.touch){if(contact!==blocked){contact=blocked;contactTime=0}contactTime+=dt;if(contactTime>.45){blocked.open=true;contact=null;tone(180)}}else if(blocked.phase<99)note(`${MATERIALS[blocked.phase]} · Phase ${blocked.phase} or Touch ${blocked.touch}`,1.2);return;}ghost.x=nx;ghost.y=ny;if(!hits.length){lastSafe={x:nx,y:ny};phaseExit=null;}else if(phase){phaseExit={x:dx,y:dy};}}
function update(dt){t+=dt;for(const h of people){const u=(t+h.offset)/h.period*Math.PI*2;h.x=(h.min+h.max)/2+Math.sin(u)*(h.max-h.min)/2;h.angle=Math.cos(u)>0?0:Math.PI;}
let x=input.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y=input.y+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),len=Math.hypot(x,y);if(len>1){x/=len;y/=len}if(x)ghost.face=x<0?0:2;else if(y)ghost.face=y<0?3:1;
// Finish the current crossing on release; fall back safely if another material blocks the exit.
if(phaseExit&&!active('phase')){const length=Math.hypot(phaseExit.x,phaseExit.y)||1;let exit=null;for(let d=1;d<160;d++){const x=ghost.x+phaseExit.x/length*d,y=ghost.y+phaseExit.y/length*d;if(blocks.some(b=>overlap(x,y,b)&&b.phase>p.phase))break;if(!blocks.some(b=>overlap(x,y,b))){exit={x,y};break}}ghost.x=(exit||lastSafe).x;ghost.y=(exit||lastSafe).y;lastSafe={x:ghost.x,y:ghost.y};phaseExit=null}
const s=speed(p)*dt;if(x)move(x*s,0,dt);if(y)move(0,y*s,dt);if(!active('touch')){contact=null;contactTime=0}ghost.y=Math.max(FINISH,Math.min(START+35,ghost.y));runPoints=Math.max(runPoints,points(ghost.y));if(ghost.y<2835)unlock('phase','Phase unlocked · Select ◇ and hold Skill through the curtain.');if(ghost.y<2690)unlock('touch','Touch unlocked · Select ✦ to move light obstacles.');
const invisible=active('invisibility');if(invisible)energy=Math.max(0,energy-dt);let spotted=false;for(const h of people){const dx=ghost.x-h.x,dy=ghost.y-h.y,d=Math.hypot(dx,dy),angle=Math.atan2(dy,dx),delta=Math.atan2(Math.sin(angle-h.angle),Math.cos(angle-h.angle));if(!invisible&&d<h.range&&Math.abs(delta)<.61&&!rayBlocked(h.x,h.y,ghost.x,ghost.y,blocks))spotted=true;}
seen=spotted?seen+dt:Math.max(0,seen-dt*3);if(seen>.18){finish();return}if(ghost.y<=FINISH){finish(true);return}
cam+=(ghost.y-viewH*.68-cam)*Math.min(1,dt*8);cam=Math.max(0,Math.min(START-viewH*.68,cam));$('distance').textContent=runPoints;$('chapter').textContent=areaAt(ghost.y).name.toUpperCase();$('best').textContent=`BEST ${Math.max(p.best,runPoints)}`;$('reserve').textContent=selected==='invisibility'?`${energy.toFixed(1)}s / ${capacity(p).toFixed(1)}s`:`TIER ${p[selected]}`;$('skill').classList.toggle('active',held);}
function rect(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),w,h)}
function drawGhost(c,x,y,scale,face,time,alpha=1){c.save();c.globalAlpha=alpha;const bob=reduced?0:Math.round(Math.sin(time*3)*2);c.fillStyle='#09121c66';c.beginPath();c.ellipse(x,y+14*scale,5*scale,1.5*scale,0,0,Math.PI*2);c.fill();const rows=['00001111110000','00111111111100','01111111111110','01111111111110','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','01121122112110','00111011011100','00010000001000'];for(let j=0;j<rows.length;j++)for(let i=0;i<14;i++){const v=rows[j][i];if(v!=='0')rect(c,x+(i-7)*scale,y+(j-8)*scale+bob,scale,scale,v==='2'?'#c4cccb':'#eeeFec')};if(face!==3){const ex=face===0?-5:face===2?2:-3;for(const ox of [ex,ex+4])rect(c,x+ox*scale,y-3*scale+bob,scale,3*scale,'#142029')}c.restore();}
function prop(b){const {x,y,w,h,kind}=b;if(b.open){rect(ctx,x,y,w,3,'#badbc34d');return}rect(ctx,x+5,y+8,w,h,'#07101d55');if(kind==='wall'){rect(ctx,x,y,w,h,'#26353e');rect(ctx,x,y-9,w,9,'#778386');rect(ctx,x,y,w,3,'#a8ada544');return}const colors={bed:'#748787',dresser:'#786654',sofa:'#7e737e',cabinet:'#657378',car:'#66828d',shelf:'#787563',hedge:'#426555',stone:'#718184',curtain:'#a28391',door:'#96734f',gate:'#70857c',barrier:'#908071',shutter:'#7e8e99'};rect(ctx,x,y,w,h,colors[kind]||'#6b747e');rect(ctx,x,y,w,4,'#ffffff25');rect(ctx,x+w-5,y,5,h,'#0003');if(kind==='bed'){rect(ctx,x+8,y+10,w-16,30,'#d7d5c1');rect(ctx,x+7,y+50,w-14,h-58,'#526b79');rect(ctx,x+7,y+56,w-14,5,'#a4b4a4')}else if(kind==='car'){rect(ctx,x+10,y+25,w-20,30,'#263d4b');rect(ctx,x+10,y+h-43,w-20,24,'#263d4b');rect(ctx,x-3,y+25,6,22,'#15232a');rect(ctx,x+w-3,y+25,6,22,'#15232a');rect(ctx,x+9,y+4,13,4,'#ffe6b4');rect(ctx,x+w-22,y+4,13,4,'#ffe6b4')}else if(kind==='curtain'||kind==='shutter'){for(let i=7;i<w;i+=12)rect(ctx,x+i,y,3,h,'#0002')}else if(kind==='hedge'){for(let i=0;i<8;i++)rect(ctx,x+8+(i*19)%(w-18),y+8+(i*29)%(h-18),10,9,'#62806a')}else{for(let i=20;i<h;i+=25)rect(ctx,x+5,y+i,w-10,2,'#0003')}if(b.phase<99){ctx.font='9px sans-serif';ctx.fillStyle='#f0ead5';ctx.textAlign='center';ctx.fillText(MATERIALS[b.phase].toUpperCase(),x+w/2,y-10);}}
function human(h){const x=h.x,y=h.y,step=Math.sin(t*8)*3;ctx.fillStyle='#08151e66';ctx.beginPath();ctx.ellipse(x,y+13,13,6,0,0,7);ctx.fill();rect(ctx,x-8,y+3,6,11+step,'#273340');rect(ctx,x+3,y+3,6,11-step,'#273340');rect(ctx,x-12,y-15,24,21,'#b18f78');rect(ctx,x-15,y-10,4,14,'#d3b294');rect(ctx,x+11,y-10,4,14,'#d3b294');rect(ctx,x-8,y-29,16,16,'#d3b294');rect(ctx,x-9,y-31,18,7,'#594b46');rect(ctx,x+(h.angle===0?5:-7),y-22,3,3,'#263039');}
function draw(){ctx.fillStyle='#111c27';ctx.fillRect(0,0,480,viewH);ctx.save();ctx.translate(0,-Math.round(cam));for(let y=0;y<3500;y+=40){const a=areaAt(y);rect(ctx,0,y,480,40,a.floor);for(let x=22;x<458;x+=52){rect(ctx,x,y,1,40,'#00000013');rect(ctx,x,y+39,52,1,'#ffffff09');if(a.kind===0){rect(ctx,x+8,y+10,25,1,'#ffffff08');rect(ctx,x+3,y+27,35,1,'#0000000c');}}if(a.kind===3){rect(ctx,65,y,8,24,'#c7c4aa55');rect(ctx,408,y,8,24,'#c7c4aa55')}}
// Woven runners and small details give the rooms a lived-in identity.
for(const y of [3210,2880]){rect(ctx,176,y,125,135,'#303d4680');rect(ctx,183,y+7,111,121,'#92796930');ctx.strokeStyle='#baa78c30';ctx.lineWidth=2;ctx.strokeRect(189,y+13,99,109);for(let i=0;i<8;i++)rect(ctx,190+i*12,y+3,2,4,'#b7a68750')}
// Warm pools of light and cool shadow bind the whole journey together.
for(const y of [3330,2920,2580,2290,1980,1670,1380,1020,660]){if(y<cam-220||y>cam+viewH+220)continue;const g=ctx.createRadialGradient(430,y,5,430,y,180);g.addColorStop(0,'#eec98d20');g.addColorStop(1,'#eec98d00');ctx.fillStyle=g;ctx.fillRect(240,y-180,230,360);rect(ctx,438,y-8,12,16,'#ddbe87')}
for(const h of people){if(h.y<cam-200||h.y>cam+viewH+200)continue;ctx.beginPath();ctx.moveTo(h.x,h.y);for(let a=h.angle-.6;a<=h.angle+.61;a+=.05){let d=0;for(;d<h.range;d+=8){if(blocks.some(b=>overlap(h.x+Math.cos(a)*d,h.y+Math.sin(a)*d,b,0)))break}ctx.lineTo(h.x+Math.cos(a)*d,h.y+Math.sin(a)*d)}ctx.closePath();ctx.fillStyle=seen?'#efac7955':'#f7d49a17';ctx.fill();}
const visible=blocks.filter(b=>b.y+b.h>cam-40&&b.y<cam+viewH+50);visible.forEach(prop);people.filter(h=>h.y>cam-50&&h.y<cam+viewH+50).forEach(human);
ctx.textAlign='center';ctx.fillStyle='#b7dac366';ctx.font='10px sans-serif';for(const y of [3370,2720,2080,1490,740])ctx.fillText('↑  THE CROSSING',240,y);
rect(ctx,172,60,136,115,'#758e8b');rect(ctx,185,65,110,88,'#abcfc144');ctx.fillStyle='#daf2d7';ctx.font='18px Georgia';ctx.fillText('THE LAST FERRY',240,45);const g=ctx.createRadialGradient(240,120,10,240,120,140);g.addColorStop(0,'#c5ffda55');g.addColorStop(1,'#c5ffda00');ctx.fillStyle=g;ctx.fillRect(100,0,280,260);
drawGhost(ctx,ghost.x,ghost.y-16,3,ghost.face,t,active('invisibility')?.25:active('phase')?.6:1);if(active('touch')){ctx.strokeStyle='#e9c58a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(ghost.x,ghost.y-7,24,0,7);ctx.stroke()}ctx.restore();const v=ctx.createLinearGradient(0,0,480,0);v.addColorStop(0,'#08151c77');v.addColorStop(.15,'#08151c00');v.addColorStop(.85,'#08151c00');v.addColorStop(1,'#08151c77');ctx.fillStyle=v;ctx.fillRect(0,0,480,viewH);}
function resize(){const r=canvas.getBoundingClientRect();viewH=480*r.height/r.width;canvas.width=480;canvas.height=Math.round(viewH);ctx.imageSmoothingEnabled=false;if(mode!=='play')cam=Math.max(0,START-viewH*.68)}window.addEventListener('resize',resize);resize();home();
function frame(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;if(mode==='play')update(dt);else if(mode==='menu')t+=dt;draw();$('notice').style.opacity=mode==='play'&&now<noticeUntil?'1':'0';requestAnimationFrame(frame)}requestAnimationFrame(frame);
