import {MATERIALS,MAX,initial,sanitize,speed,capacity,cost,buy,overlap,rayBlocked} from './model.js';
import {WORLD,LEVELS,SPAWN,FERRY,REGIONS,areaAt,generateWorld,discover} from './world.js';
import {navigation,createEntities,updateEntities,investigate,resolveSightings,createTokens,collectTokens} from './entities.js';
import {createScenery,drawSceneryProp,drawStreetLamp,drawFerry} from './scenery.js';
import {drawHuman,drawCat} from './characters.js';
const $=id=>document.getElementById(id), canvas=$('world'),ctx=canvas.getContext('2d'),KEY='gamebox.unfinished-business.v1';
let p;try{p=sanitize(JSON.parse(localStorage.getItem(KEY)))}catch{p=initial()}
let world=generateWorld(p.worldSeed,p.level),visited=new Set(p.visitedByLevel?.[p.level]||p.visited||[]),saveTimer=0,nav=navigation(world.blocks),effects={boost:0,stiff:0,energy:0},tokens=createTokens(nav),scenery=createScenery(world);
let mode='menu',selected='invisibility',held=false,skillPointer=null,stickPointer=null,stickOrigin={x:0,y:0},keys=new Set(),input={x:0,y:0},blocks=world.blocks,people=createEntities(nav,p.level),ghost={...world.spawn,face:1},energy=0,runPoints=0,t=0,cam=0,camX=0,viewH=800,last=0,noticeUntil=0,contact=null,contactTime=0,lastSafe={...world.spawn},phaseExit=null,seen=0,audio=null,saveFailed=false;
const names={speed:'Movement speed',invisibility:'Invisibility',phase:'Phase',touch:'Touch'},icons={speed:'↗',invisibility:'◌',phase:'◇',touch:'✦'},labels={invisibility:'VANISH',phase:'PHASE',touch:'TOUCH'};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){p.visitedByLevel??=[[],[],[],[],[]];p.visitedByLevel[p.level]=[...visited];p.visited=p.visitedByLevel[p.level];try{localStorage.setItem(KEY,JSON.stringify(p))}catch{saveFailed=true;}}
function note(s,d=4){$('notice').textContent=s;noticeUntil=performance.now()+d*1000;}
function tone(f=440,d=.12){if(!p.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.6,audio.currentTime+d);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function resetInput(){held=false;skillPointer=null;stickPointer=null;input={x:0,y:0};keys.clear();$('nub').style.transform='';$('stick').hidden=true;}
function footer(){return `<div class="footer"><a href="../index.html"><img src="../shared/assets/GameBox%20back%20button.png" alt="Game Box"></a><button class="sound" id="sound">SOUND ${p.sound?'ON':'OFF'}</button></div>`}
function show(html){resetInput();$('overlay').hidden=false;$('overlay').innerHTML=`<div class="menu">${html}</div>`;document.querySelectorAll('[data-start]').forEach(b=>b.onclick=start);$('sound')?.addEventListener('click',()=>{p.sound=!p.sound;save();$('sound').textContent=`SOUND ${p.sound?'ON':'OFF'}`});}
function home(){mode='menu';$('hud').hidden=true;$('controls').hidden=true;show(`<canvas class="brandGhost" id="portrait" width="96" height="110"></canvas><span class="eyebrow">A LITTLE GHOST. A LONG WAY HOME.</span><h1>Unfinished<br><em>Business</em></h1><p class="subtitle">The afterlife is waiting.<br>Try not to be seen on the way.</p><div class="record">LEVEL ${p.level+1} · ${LEVELS[p.level].name.toUpperCase()}<br>${p.bank} GHOST POINTS</div><button class="primary" data-start>${p.runs?'Make another escape':'Begin your escape'} →</button>${p.unlockedLevel>0?'<button class="secondary" id="levels">Choose level</button>':''}<button class="secondary" id="upgrade">Your abilities</button><button class="secondary" id="help">How to play</button>${footer()}`);const c=$('portrait').getContext('2d');drawGhost(c,48,66,5,1,0);$('levels')?.addEventListener('click',chooseLevel);$('upgrade').onclick=()=>shop(false);$('help').onclick=help;}
function chooseLevel(){show(`<span class="eyebrow">CHOOSE YOUR WAY HOME</span><h2>Five neighbourhoods.</h2><p class="subtitle">Each level has busier streets, tighter routes and more witnesses.</p>${LEVELS.map((l,i)=>`<button class="secondary" data-level="${i}" ${i>p.unlockedLevel?'disabled':''}>${i+1}. ${l.name}${i>p.unlockedLevel?' · LOCKED':''}</button>`).join('')}<button class="secondary" id="menu">Back</button>${footer()}`);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{save();p.level=Number(b.dataset.level);visited=new Set(p.visitedByLevel?.[p.level]||[]);save();home()});$('menu').onclick=home;}
function help(){show(`<span class="eyebrow">THE RULES OF BEING DEAD</span><h2>Keep a low profile.</h2><div class="help"><p><b>Move</b> by dragging anywhere on the play area. On a keyboard, use WASD or arrow keys.</p><p><b>Hold an ability button</b> along the bottom to use it while moving. Keyboard: Space to use; 1, 2, 3 to select.</p><p>Being seen sends you home. Step onto new ground to earn a Ghost Point. Explored ground stays recorded across attempts and reloads; retracing your steps earns nothing.</p><p>Buy speed and longer invisibility. Discover Phase in the house and Touch in the garage. Hold Phase or Touch while moving into an obstacle.</p><p>Only one skill works at a time. Explore in any direction. The map shows your position, not your footsteps or destination. Find hidden speed boosts, invisibility refills and Scared Stiff tokens. A Scared Stiff token freezes your next witness for eight seconds and is consumed. Black cats alert nearby humans; cameras can catch you. Opened doors attract investigation.</p></div><button class="primary" id="back">Got it</button>`);$('back').onclick=home;}
function description(k){if(k==='speed')return `${speed(p)} → ${speed(p)+11} pace`;if(k==='invisibility')return `${capacity(p).toFixed(2)} → ${(capacity(p)+.65).toFixed(2)} seconds`;if(k==='phase')return `${MATERIALS[p.phase]} → ${MATERIALS[Math.min(7,p.phase+1)]}`;return ['','Curtains → Handles','Handles → Heavy gates','Heavy gates → Shutters','Shutters → Industrial doors','Maximum strength'][p.touch];}
function shop(result=false,win=false){mode='shop';$('controls').hidden=true;show(`<span class="eyebrow">${win?'THE CROSSING IS YOURS':result?'BACK TO THE BEGINNING':'GROW INTO YOUR GHOST'}</span><h2>${win?'Rest, at last.':result?'Somebody saw you.':'A little more spirit.'}</h2>${result?`<div class="stats"><div><strong>+${runPoints}</strong><small>THIS ATTEMPT</small></div><div><strong>${p.bank}</strong><small>GHOST POINTS</small></div><div><strong>${p.runs}</strong><small>ATTEMPTS</small></div></div>`:`<p class="record">${p.bank} GHOST POINTS AVAILABLE</p>`}<div class="upgrades">${Object.keys(MAX).filter(k=>k==='speed'||p[k]>0).map(k=>`<div class="upgrade"><span class="icon">${skillGlyph(k)}</span><div><b>${names[k]}</b><small>${p[k]>=MAX[k]?'Fully upgraded':description(k)}</small></div><button class="buy" data-buy="${k}" ${p[k]>=MAX[k]||p.bank<cost(p,k)?'disabled':''}>${p[k]>=MAX[k]?'MAX':cost(p,k)+' GP'}</button></div>`).join('')}</div>${result&&p.runs===1?'<p class="subtitle">Invisibility unlocked. Hold VANISH to disappear briefly. Spend your points to go further.</p>':''}${saveFailed?'<p>Storage unavailable. Keep this tab open to retain progress.</p>':''}<button class="primary" data-start>${win?'Take another journey':'Try again'} →</button><button class="secondary" id="menu">Main menu</button>${footer()}`);document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{if(buy(p,b.dataset.buy)){save();tone(650);shop(result,win)}});$('menu').onclick=home;}
function start(){mode='play';world=generateWorld(p.worldSeed,p.level);blocks=world.blocks;nav=navigation(blocks);people=createEntities(nav,p.level);tokens=createTokens(nav);scenery=createScenery(world);visited=new Set(p.visitedByLevel?.[p.level]||[]);effects={boost:0,stiff:0,energy:0};ghost={...world.spawn,face:1};lastSafe={...ghost};phaseExit=null;runPoints=0;t=0;seen=0;contact=null;contactTime=0;energy=capacity(p);selected='invisibility';cam=world.spawn.y-viewH*.55;camX=world.spawn.x-240;resetInput();$('overlay').hidden=true;$('hud').hidden=false;$('controls').hidden=false;updateSkills();note(`Level ${p.level+1} · ${world.name}. Keep out of sight.`,4);tone(320);}
function finish(win=false){if(mode!=='play')return;p.best=Math.max(p.best,runPoints);p.runs++;if(!p.invisibility)p.invisibility=1;if(win){save();if(p.level<4){p.unlockedLevel=Math.max(p.unlockedLevel,p.level+1);p.level++;visited=new Set(p.visitedByLevel?.[p.level]||[]);}else p.won=true;}save();tone(win?880:160,.3);shop(true,win);}
function pause(){if(mode!=='play')return;save();mode='pause';show(`<span class="eyebrow">TAKE A BREATHER</span><h2>Time stands still.</h2><button class="primary" id="resume">Keep going</button><button class="secondary" id="end">Return home</button>${footer()}`);$('resume').onclick=()=>{mode='play';$('overlay').hidden=true;resetInput()};$('end').onclick=()=>{mode='play';finish()};}
$('pause').onclick=pause;window.addEventListener('blur',pause);window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
const GHOST_PIXELS=['00001111110000','00111111111100','01111111111110','01111111111110','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','11111111111111','01121122112110','00111011011100','00010000001000'];
function skillGlyph(k){
 const body=GHOST_PIXELS.map((row,y)=>[...row].map((v,x)=>v==='0'?'':`<rect x="${x+7}" y="${y+5}" width="1" height="1" fill="${v==='2'?'#bdcec6':'#f0f2e9'}" ${k==='invisibility'?`opacity="${x<5?.22:x<9?.52:.9}"`:''}/>`).join('')).join('');
 const eyes='<path d="M11 10h1v3h-1zm4 0h1v3h-1z" fill="#18313a"/>';
 const shadow='<path d="M9 24h10v1H9zm-2 1h14v2H7zm2 2h10v1H9z" fill="#07151b" opacity=".65"/>';
 const wall='<path d="M15 2h9v23h-9z" fill="#887aa4"/><path d="M16 3h7v1h-7zm0 6h7v1h-7zm0 6h7v1h-7zm0 6h7v1h-7zM19 4h1v5h-1zm-2 6h1v5h-1zm3 6h1v5h-1z" fill="#c0acd5"/>';
 const crate='<path d="M20 16h10v11H20z" fill="#d4ab67"/><path d="M21 17h8v1h-8zm0 8h8v1h-8zM21 18h1v7h-1zm7 0h1v7h-1zM23 20h1v1h-1zm1 1h1v1h-1zm1 1h1v1h-1z" fill="#785b3c"/><path d="M18 15h2v3h2v2h-4z" fill="#eef2e6"/>';
 const trails='<path d="M0 9h5v2H0zm2 6h3v2H2zm-2 5h5v2H0z" fill="#b6f7d2"/>';
 const shimmer='<path d="M3 3h1v1H3zm-1 1h3v1H2zm1 1h1v1H3zm21 13h1v1h-1zm-1 1h3v1h-3zm1 1h1v1h-1z" fill="#b6f7d2"/>';
 return `<svg viewBox="0 0 32 30" shape-rendering="crispEdges" aria-hidden="true">${shadow}${k==='phase'?wall:''}${k==='speed'?trails:''}<g ${k==='touch'?'transform="translate(-3 0)"':''}>${body}${eyes}</g>${k==='phase'?'<path d="M17 5h3v15h-3z" fill="#ab91c8" opacity=".5"/><path d="m25 10 4 4-4 4v-3h-3v-2h3z" fill="#e6ceff"/>':''}${k==='touch'?crate:''}${k==='invisibility'?shimmer:''}</svg>`;
}
function updateSkills(){
 $('abilityBar').innerHTML=['invisibility','phase','touch'].map(k=>`<button class="ability ${p[k]?'':'locked'}" id="ability-${k}" aria-label="Hold ${names[k]}${p[k]?'':' — locked'}" aria-disabled="${!p[k]}" aria-pressed="false" data-ability="${k}"><span class="abilityArt">${skillGlyph(k)}</span><strong>${labels[k]}</strong><small id="reserve-${k}">${p[k]?'HOLD':'LOCKED'}</small><span class="abilityMeter"><i id="meter-${k}"></i></span></button>`).join('');
 document.querySelectorAll('[data-ability]').forEach(button=>{
  button.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const k=button.dataset.ability;if(mode!=='play')return;if(!p[k]){note(k==='invisibility'?'Invisibility unlocks after your first attempt.':k==='phase'?'Discover Phase further inside the house.':'Discover Touch in the garage.');return}if(skillPointer!==null)return;skillPointer=e.pointerId;selected=k;held=true;button.setPointerCapture(e.pointerId);tone(260,.06)};
  for(const ev of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(ev,e=>{if(e.pointerId===skillPointer){held=false;skillPointer=null}});
 });
}
$('game').addEventListener('pointerdown',e=>{
 if(mode!=='play'||stickPointer!==null||e.target.closest('button,a,#overlay'))return;
 e.preventDefault();stickPointer=e.pointerId;stickOrigin={x:e.clientX,y:e.clientY};const r=$('game').getBoundingClientRect();$('stick').style.left=`${e.clientX-r.left}px`;$('stick').style.top=`${e.clientY-r.top}px`;$('stick').hidden=false;$('game').setPointerCapture(e.pointerId);moveStick(e);
});
function moveStick(e){if(e.pointerId!==stickPointer)return;const dx=e.clientX-stickOrigin.x,dy=e.clientY-stickOrigin.y,len=Math.hypot(dx,dy),s=Math.min(1,len/42);input={x:len?dx/len*s:0,y:len?dy/len*s:0};$('nub').style.transform=`translate(${input.x*30}px,${input.y*30}px)`;}
$('game').addEventListener('pointermove',moveStick);
for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('game').addEventListener(ev,e=>{if(e.pointerId===stickPointer){stickPointer=null;input={x:0,y:0};$('nub').style.transform='';$('stick').hidden=true}});
window.addEventListener('keydown',e=>{if(e.code==='Escape'){pause();return}if(mode!=='play')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space')held=true;const k={Digit1:'invisibility',Digit2:'phase',Digit3:'touch'}[e.code];if(k&&p[k]){held=false;selected=k;updateSkills()}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')held=false});
function unlock(k,text){if(p[k])return;p[k]=1;save();updateSkills();note(text,6);tone(750,.25)}
function active(k){return held&&selected===k&&p[k]>0&&(k!=='invisibility'||energy>0)}
function move(dx,dy,dt){const nx=ghost.x+dx,ny=ghost.y+dy,hits=blocks.filter(b=>overlap(nx,ny,b));const phase=active('phase');const blocked=hits.find(b=>!(phase&&p.phase>=b.phase));if(blocked){if(active('touch')&&p.touch>=blocked.touch){if(contact!==blocked){contact=blocked;contactTime=0}contactTime+=dt;if(contactTime>.45){blocked.open=true;nav=navigation(blocks);investigate(people,nav,{x:blocked.x+blocked.w/2,y:blocked.y+blocked.h/2});contact=null;tone(180)}}else if(blocked.phase<99)note(`${MATERIALS[blocked.phase]} · Phase ${blocked.phase} or Touch ${blocked.touch}`,1.2);return;}ghost.x=nx;ghost.y=ny;if(!hits.length){lastSafe={x:nx,y:ny};phaseExit=null;}else if(phase){phaseExit={x:dx,y:dy};}}
function update(dt){t+=dt;effects.boost=Math.max(0,effects.boost-dt);updateEntities(people,nav,blocks,dt);
let x=input.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y=input.y+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),len=Math.hypot(x,y);if(len>1){x/=len;y/=len}if(x)ghost.face=x<0?0:2;else if(y)ghost.face=y<0?3:1;
// Finish the current crossing on release; fall back safely if another material blocks the exit.
if(phaseExit&&!active('phase')){const length=Math.hypot(phaseExit.x,phaseExit.y)||1;let exit=null;for(let d=1;d<160;d++){const x=ghost.x+phaseExit.x/length*d,y=ghost.y+phaseExit.y/length*d;if(blocks.some(b=>overlap(x,y,b)&&b.phase>p.phase))break;if(!blocks.some(b=>overlap(x,y,b))){exit={x,y};break}}ghost.x=(exit||lastSafe).x;ghost.y=(exit||lastSafe).y;lastSafe={x:ghost.x,y:ghost.y};phaseExit=null}
const s=speed(p)*(effects.boost>0?1.65:1)*dt;if(x)move(x*s,0,dt);if(y)move(0,y*s,dt);if(!active('touch')){contact=null;contactTime=0}ghost.x=Math.max(34,Math.min(WORLD.width-34,ghost.x));ghost.y=Math.max(34,Math.min(WORLD.height-34,ghost.y));
// Award once per small ground cell, immediately bank it, and persist the same visited set.
if(!blocks.some(b=>overlap(ghost.x,ghost.y,b,0))&&discover(visited,ghost.x,ghost.y)){runPoints++;p.bank++;}
saveTimer+=dt;if(saveTimer>1){save();saveTimer=0;}
if(ghost.x>400&&ghost.x<900&&ghost.y>1480&&ghost.y<2200)unlock('phase','Phase unlocked · Hold PHASE to cross the curtain.');
if(ghost.x>1060&&ghost.x<1560&&ghost.y>1630&&ghost.y<2150)unlock('touch','Touch unlocked · Hold TOUCH to move light obstacles.');

effects.energy=energy;for(const message of collectTokens(tokens,ghost,effects,!!p.invisibility,capacity(p))){note(message,4);tone(740,.15)}energy=effects.energy;
const invisible=active('invisibility');if(invisible)energy=Math.max(0,energy-dt);
const sight=resolveSightings(people,ghost,blocks,effects,invisible,(source,max)=>investigate(people,nav,source,max));
if(sight.blocked){seen=0;note('Scared Stiff! Witness frozen · token used.',3);tone(180,.22)}
const spotted=sight.danger;
seen=spotted?seen+dt:Math.max(0,seen-dt*3);if(seen>.18){finish();return}if(Math.hypot(ghost.x-world.ferry.x,ghost.y-world.ferry.y)<48){finish(true);return}
cam+=(ghost.y-viewH*.55-cam)*Math.min(1,dt*8);camX+=(ghost.x-240-camX)*Math.min(1,dt*8);cam=Math.max(0,Math.min(WORLD.height-viewH,cam));camX=Math.max(0,Math.min(WORLD.width-480,camX));$('distance').textContent=runPoints;$('chapter').textContent=areaAt(ghost.x,ghost.y,p.level).name.toUpperCase();$('best').textContent=[effects.boost>0?`BOOST ${Math.ceil(effects.boost)}s`:'',effects.stiff?`SCARED STIFF ×${effects.stiff}`:''].filter(Boolean).join(' · ')||'KEEP OUT OF SIGHT';for(const k of ['invisibility','phase','touch']){const button=$('ability-'+k),using=active(k);button.classList.toggle('active',using);button.setAttribute('aria-pressed',String(using));$('reserve-'+k).textContent=!p[k]?'LOCKED':k==='invisibility'?`${energy.toFixed(1)}s`:`TIER ${p[k]}`;$('meter-'+k).style.width=!p[k]?'0%':k==='invisibility'?`${energy/Math.max(.01,capacity(p))*100}%`:'100%';}}

function rect(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),w,h)}
function drawGhost(c,x,y,scale,face,time,alpha=1){c.save();c.globalAlpha=alpha;const bob=reduced?0:Math.round(Math.sin(time*3)*2);c.fillStyle='#09121c66';c.beginPath();c.ellipse(x,y+14*scale,5*scale,1.5*scale,0,0,Math.PI*2);c.fill();const rows=GHOST_PIXELS;for(let j=0;j<rows.length;j++)for(let i=0;i<14;i++){const v=rows[j][i];if(v!=='0')rect(c,x+(i-7)*scale,y+(j-8)*scale+bob,scale,scale,v==='2'?'#c4cccb':'#eeeFec')};if(face!==3){const ex=face===0?-5:face===2?2:-3;for(const ox of [ex,ex+4])rect(c,x+ox*scale,y-3*scale+bob,scale,3*scale,'#142029')}c.restore();}
function prop(b){drawSceneryProp(ctx,b);if(!b.open&&b.phase<99&&Math.hypot(b.x+b.w/2-ghost.x,b.y+b.h/2-ghost.y)<180){ctx.font='9px sans-serif';ctx.fillStyle='#f0ead5';ctx.textAlign='center';ctx.fillText(MATERIALS[b.phase].toUpperCase(),b.x+b.w/2,b.y-13);}}
function drawEntity(e){
 const {x,y}=e;
 if(e.kind==='camera'){ctx.save();ctx.translate(x,y);ctx.rotate(e.angle);rect(ctx,-8,-4,14,8,'#74858f');rect(ctx,1,-7,19,14,'#c9d1c8');rect(ctx,16,-5,5,10,'#273a44');rect(ctx,7,-3,3,3,e.frozen>0?'#a6f0f2':'#ed8e77');ctx.restore();}
 else if(e.kind==='cat')drawCat(ctx,e,reduced);
 else drawHuman(ctx,e,reduced);
 ctx.textAlign='center';ctx.font='bold 13px sans-serif';
 if(e.frozen>0){ctx.strokeStyle='#bceaf0';ctx.lineWidth=2;ctx.strokeRect(x-20,y-38,40,55);ctx.fillStyle='#c5f9ff';ctx.fillText('✧',x,y-43);}
 else if(e.state==='investigate'||e.state==='search'){ctx.fillStyle='#f3ce87';ctx.fillText('?',x,y-40)}
 else if(e.meow>0){ctx.fillStyle='#c8e888';ctx.fillText('!',x,y-29)}
}
function drawToken(token){const {x,y,kind}=token,color=kind==='speed'?'#f3ce87':kind==='refill'?'#b6f7d2':'#d9c2ff';ctx.save();ctx.translate(x,y+(reduced?0:Math.sin(t*3+token.id)*2));ctx.fillStyle='#091622aa';ctx.beginPath();ctx.ellipse(0,11,12,4,0,0,7);ctx.fill();rect(ctx,-8,-10,16,19,'#263642');ctx.strokeStyle=color;ctx.lineWidth=2;ctx.strokeRect(-8,-10,16,19);ctx.fillStyle=color;if(kind==='speed'){ctx.beginPath();ctx.moveTo(1,-7);ctx.lineTo(-4,1);ctx.lineTo(0,1);ctx.lineTo(-1,6);ctx.lineTo(5,-2);ctx.lineTo(1,-2);ctx.fill()}else if(kind==='refill'){rect(ctx,-3,-6,6,10,color);rect(ctx,-5,-3,10,5,color)}else{rect(ctx,-5,-5,10,10,color);rect(ctx,-3,-2,2,3,'#263642');rect(ctx,2,-2,2,3,'#263642')}ctx.restore();}
function draw(){
 ctx.fillStyle='#111c27';ctx.fillRect(0,0,480,viewH);ctx.save();ctx.translate(-Math.round(camX),-Math.round(cam));
 // Static floor detail is cached once; only the visible camera crop is drawn per frame.
 ctx.drawImage(scenery,Math.round(camX),Math.round(cam),480,Math.min(viewH,WORLD.height-cam),Math.round(camX),Math.round(cam),480,Math.min(viewH,WORLD.height-cam));
 for(const d of world.decor)if(d.kind==='lamp'&&d.x>camX-40&&d.x<camX+520&&d.y>cam-40&&d.y<cam+viewH+40)drawStreetLamp(ctx,d);
 for(const h of people){if(h.frozen>0)continue;if(h.x<camX-200||h.x>camX+680||h.y<cam-200||h.y>cam+viewH+200)continue;ctx.beginPath();ctx.moveTo(h.x,h.y);for(let a=h.angle-h.half;a<=h.angle+h.half+.01;a+=.075){let d=0;for(;d<h.range;d+=10){if(blocks.some(b=>overlap(h.x+Math.cos(a)*d,h.y+Math.sin(a)*d,b,0)))break}ctx.lineTo(h.x+Math.cos(a)*d,h.y+Math.sin(a)*d)}ctx.closePath();ctx.fillStyle=h.kind==='cat'?'#b6d99d10':h.kind==='camera'?'#b6cce328':seen?'#efac7955':'#f7d49a1c';ctx.fill();}
 const visible=blocks.filter(b=>b.x+b.w>camX-50&&b.x<camX+530&&b.y+b.h>cam-60&&b.y<cam+viewH+60);for(const b of visible){if(b.kind==='water'){rect(ctx,b.x,b.y,b.w,b.h,'#254655');for(let y=Math.max(b.y,Math.floor(cam/32)*32);y<Math.min(b.y+b.h,cam+viewH);y+=32)for(let x=b.x+10;x<b.x+b.w;x+=56)rect(ctx,x+Math.round(Math.sin(t+y)*3),y,26,2,'#8ebaba25');}else prop(b);}
 people.filter(h=>h.x>camX-40&&h.x<camX+520&&h.y>cam-50&&h.y<cam+viewH+50).forEach(drawEntity);
 ctx.textAlign='center';ctx.font='11px sans-serif';ctx.fillStyle='#e0dcc470';for(const r of world.regions)if(r.x+r.w>camX&&r.x<camX+480&&r.y>cam-30&&r.y<cam+viewH)ctx.fillText(r.name.toUpperCase(),r.x+r.w/2,r.y+40);
 drawFerry(ctx,world.ferry);ctx.fillStyle='#dce6bf';ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText('THE LAST FERRY',world.ferry.x,world.ferry.y-110);

 for(const token of tokens)if(!token.collected&&Math.hypot(token.x-ghost.x,token.y-ghost.y)<115&&!rayBlocked(token.x,token.y,ghost.x,ghost.y,blocks))drawToken(token);
 drawGhost(ctx,ghost.x,ghost.y-16,3,ghost.face,t,active('invisibility')?.25:active('phase')?.6:1);
 if(active('touch')){ctx.strokeStyle='#e9c58a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(ghost.x,ghost.y-7,24,0,7);ctx.stroke()}ctx.restore();
 if(mode==='play')drawMap();
}
function drawMap(){const x=366,y=102,w=98,h=90,sx=w/WORLD.width,sy=h/WORLD.height;rect(ctx,x-4,y-4,w+8,h+8,'#0d1c27dd');ctx.strokeStyle='#8caa8370';ctx.lineWidth=1;ctx.strokeRect(x-4,y-4,w+8,h+8);for(const r of world.regions)rect(ctx,x+r.x*sx,y+r.y*sy,r.w*sx,r.h*sy,'#55716a44');rect(ctx,x+ghost.x*sx-2,y+ghost.y*sy-2,4,4,'#ffffff');ctx.fillStyle='#c0d1be';ctx.font='8px sans-serif';ctx.textAlign='right';ctx.fillText(`LEVEL ${p.level+1}`,x+w,y+h+14);}
function resize(){const r=canvas.getBoundingClientRect();viewH=480*r.height/r.width;canvas.width=480;canvas.height=Math.round(viewH);ctx.imageSmoothingEnabled=false;if(mode!=='play'){cam=Math.max(0,Math.min(WORLD.height-viewH,world.spawn.y-viewH*.55));camX=Math.max(0,world.spawn.x-240)}}window.addEventListener('resize',resize);resize();home();
function frame(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;if(mode==='play')update(dt);else if(mode==='menu')t+=dt;draw();$('notice').style.opacity=mode==='play'&&now<noticeUntil?'1':'0';requestAnimationFrame(frame)}requestAnimationFrame(frame);
