(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const ROSTER_KEY='gamebox.players.v1',CARD_SAVE_KEY='gamebox.cardGames.v3',COIN_SAVE_KEY='gamebox.coinGames.v2',CARD_SELECTION_KEY='gamebox.players.cards.v1',COIN_SELECTION_KEY='gamebox.players.coins.v1';
  const ranks=['A','K','Q','J','10','9','8','7','6','5','4','3','2'];
  const suits=[{symbol:'♠',red:false},{symbol:'♥',red:true},{symbol:'♦',red:true},{symbol:'♣',red:false}];
  const ruleKeys=[...ranks,'JOKER_RED','JOKER_BLACK'];
  const exampleRules={A:'Make a new rule.',K:'Everyone takes part.',Q:'Ask another player a question.',J:'Choose another player.','10':'Pick a category and take turns naming answers.','9':'Pick a word and take turns rhyming.','8':'Choose a mate.','7':'Hands up — last player loses.','6':'Choose a player.','5':'Everyone joins in.','4':'Touch the floor — last player loses.','3':'You take the action.','2':'Choose two people.',JOKER_RED:'Wild card — invent a temporary rule.',JOKER_BLACK:'Reverse the turn order.'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const read=(key,fallback=[])=>{try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}};
  const write=(key,v)=>localStorage.setItem(key,JSON.stringify(v));
  const shuffle=input=>{const out=[...input];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
  const coinResult=()=>{try{const a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return(a[0]&1)?'H':'T'}catch{return Math.random()>=.5?'H':'T'}};

  function roster(){const items=read(ROSTER_KEY,[]);return Array.isArray(items)?items.filter(p=>p?.id&&String(p.name||'').trim()).map(p=>({id:String(p.id),name:String(p.name).trim()})):[]}
  function selection(key,max=4){const valid=new Set(roster().map(p=>p.id)),ids=read(key,[]);return Array.isArray(ids)?ids.map(String).filter(id=>valid.has(id)).slice(0,max):[]}
  function selectedPeople(key,max=4){const map=new Map(roster().map(p=>[p.id,p]));return selection(key,max).map(id=>map.get(id)).filter(Boolean)}
  function renderHomeRoster(){const list=$('homePlayers');if(!list)return;const people=roster();list.innerHTML='';if(!people.length){list.innerHTML='<div class="emptyNote">Add players here once. Every game will use this list.</div>';return}people.forEach(person=>{const row=document.createElement('div');row.className='homePlayerPill';row.innerHTML=`<span>${esc(person.name)}</span><button type="button" aria-label="Remove ${esc(person.name)}">×</button>`;row.querySelector('button').onclick=()=>{write(ROSTER_KEY,roster().filter(p=>p.id!==person.id));write(CARD_SELECTION_KEY,selection(CARD_SELECTION_KEY).filter(id=>id!==person.id));write(COIN_SELECTION_KEY,selection(COIN_SELECTION_KEY).filter(id=>id!==person.id));renderHomeRoster();renderAllPlayerPickers();syncAllLanPlayerSelects()};list.appendChild(row)})}
  function addHomePlayer(){const input=$('newPlayerName'),name=input.value.trim();if(!name)return;const people=roster();if(people.some(p=>p.name.toLowerCase()===name.toLowerCase())){input.select();return}people.push({id:uid(),name});write(ROSTER_KEY,people);input.value='';renderHomeRoster();renderAllPlayerPickers();syncAllLanPlayerSelects();input.focus()}

  const pickerDefs=[];
  function setupPicker(containerId,storageKey,max,onChange){const container=$(containerId),def={container,storageKey,max,onChange};pickerDefs.push(def);renderPicker(def)}
  function renderPicker(def){if(!def.container)return;const people=roster(),ids=selection(def.storageKey,def.max);def.container.innerHTML='';if(!people.length){def.container.innerHTML='<div class="emptyNote">Add players on the Home screen first.</div>';def.onChange?.([]);return}people.forEach(person=>{const b=document.createElement('button');b.type='button';b.className=`playerChoice${ids.includes(person.id)?' selected':''}`;b.textContent=person.name;b.onclick=()=>{let current=selection(def.storageKey,def.max);if(current.includes(person.id))current=current.filter(id=>id!==person.id);else if(current.length<def.max)current.push(person.id);write(def.storageKey,current);renderAllPlayerPickers();syncAllLanPlayerSelects()};def.container.appendChild(b)});def.onChange?.(selectedPeople(def.storageKey,def.max))}
  function renderAllPlayerPickers(){pickerDefs.forEach(renderPicker)}

  function setText(id,text){const el=$(id);if(el)el.textContent=text}
  function showView(name){document.querySelectorAll('[data-view]').forEach(v=>v.classList.toggle('hidden',v.dataset.view!==name));window.scrollTo({top:0,behavior:'smooth'})}
  function setLanStatus(prefix,text,strong=''){const el=$(`${prefix}LanStatus`);if(el)el.innerHTML=strong?`<strong>${esc(strong)}</strong> ${esc(text)}`:esc(text)}
  function lanAvailable(){return !!window.GameBoxLAN?.Session&&'RTCPeerConnection'in window}

  function lanMarkup(prefix,label){return `<section class="panel lanPanel"><div><h3>Play ${esc(label)} on separate phones</h3><p>Connect phones directly over the same Wi-Fi. The current player's phone gets the active control; every phone sees the result.</p></div><div class="lanModeRow"><button type="button" class="btn secondary" id="${prefix}LanHostMode">Host Wi-Fi game</button><button type="button" class="btn secondary" id="${prefix}LanJoinMode">Join Wi-Fi game</button></div><div id="${prefix}LanStatus" class="lanStatus">Local single-device mode is ready.</div><div id="${prefix}LanHost" class="lanControls hidden"><label>This phone is playing as<select id="${prefix}LanHostPlayer"></select></label><button type="button" class="btn secondary" id="${prefix}LanCreateInvite">Create friend invite</button><label>Invite code<textarea id="${prefix}LanOffer" readonly placeholder="Create an invite, then send this code to your friend"></textarea></label><label>Friend answer<textarea id="${prefix}LanAnswerIn" placeholder="Paste the answer code they send back"></textarea></label><button type="button" class="btn secondary" id="${prefix}LanAcceptAnswer">Connect friend</button><div id="${prefix}LanDevices" class="lanDeviceList"></div><button type="button" class="btn good" id="${prefix}LanStart">Start Wi-Fi game</button><div class="lanNote">For 3–4 players, create a new invite for each additional phone.</div></div><div id="${prefix}LanJoin" class="lanControls hidden"><label>Your player name<input id="${prefix}LanJoinName" maxlength="24" placeholder="e.g. Jess"></label><label>Host invite<textarea id="${prefix}LanOfferIn" placeholder="Paste the host's invite code"></textarea></label><button type="button" class="btn secondary" id="${prefix}LanMakeAnswer">Create answer</button><label>Answer code<textarea id="${prefix}LanAnswerOut" readonly placeholder="Send this code back to the host"></textarea></label><div class="lanNote">Keep this page open while the host pastes your answer and starts the game.</div></div></section>`}
  function installLanPanel(prefix,label,setupView){const stack=document.querySelector(`[data-view="${setupView}"] .setupStack`);if(!stack||$(`${prefix}LanPanelMount`))return;const mount=document.createElement('div');mount.id=`${prefix}LanPanelMount`;mount.innerHTML=lanMarkup(prefix,label);const details=stack.querySelector('details.settings');stack.insertBefore(mount,details||null)}
  function installNetworkBadge(viewName,prefix){const shell=document.querySelector(`[data-view="${viewName}"] .playShell`);if(!shell)return;const badge=document.createElement('div');badge.id=`${prefix}NetworkBadge`;badge.className='networkBadge';shell.prepend(badge)}

  const card={rules:Object.fromEntries(ruleKeys.map(k=>[k,''])),name:'',players:[],deck:[],current:0,last:null,history:[],playing:false};
  const cardNet={active:false,role:null,localPlayerId:null,session:null};
  function buildDeck(){const deck=[];for(const rank of ranks)for(const suit of suits)deck.push({rank,suit:suit.symbol,red:suit.red,ruleKey:rank,label:`${rank}${suit.symbol}`});deck.push({rank:'JOKER',joker:true,red:true,ruleKey:'JOKER_RED',label:'Red Joker'});deck.push({rank:'JOKER',joker:true,red:false,ruleKey:'JOKER_BLACK',label:'Black Joker'});return shuffle(deck)}
  function renderCardRules(){const wrap=$('cardRules');wrap.innerHTML='';ranks.forEach(rank=>{const row=document.createElement('label');row.className='ruleLine';row.innerHTML=`<strong>${rank}</strong><input maxlength="100" value="${esc(card.rules[rank])}" placeholder="Penalty / rule">`;row.querySelector('input').oninput=e=>card.rules[rank]=e.target.value.trim();wrap.appendChild(row)});[['JOKER_RED','Red Joker'],['JOKER_BLACK','Black Joker']].forEach(([key,label])=>{const row=document.createElement('label');row.className='ruleLine';row.innerHTML=`<strong>${label}</strong><input maxlength="100" value="${esc(card.rules[key])}" placeholder="Penalty / rule">`;row.querySelector('input').oninput=e=>card.rules[key]=e.target.value.trim();wrap.appendChild(row)})}
  function resetCardNetForLocal(){cardNet.active=false;cardNet.role=null;cardNet.localPlayerId=null;const b=$('cardNetworkBadge');if(b)b.className='networkBadge'}
  function startCardGame(){const players=selectedPeople(CARD_SELECTION_KEY,4);if(!players.length)return setText('cardStatus','Select at least one player.');resetCardNetForLocal();card.players=players;card.name=$('cardGameName').value.trim();card.deck=buildDeck();card.current=0;card.last=null;card.history=[];card.playing=true;renderCardPlay();showView('cards-play')}
  function performCardDraw(){if(!card.playing||!card.deck.length)return;const person=card.players[card.current],drawn=card.deck.pop();card.last={...drawn,playerId:person.id,playerName:person.name};card.history.unshift(card.last);card.current=(card.current+1)%card.players.length;renderCardPlay();if(cardNet.active&&cardNet.role==='host')broadcastCardState()}
  function requestCardDraw(){if(!cardNet.active)return performCardDraw();const current=card.players[card.current];if(!current||cardNet.localPlayerId!==current.id)return;if(cardNet.role==='host')performCardDraw();else cardNet.session.sendToHost({type:'card-action',action:'draw'})}
  function renderCardFace(target,c){if(!c){target.className='playingCard emptyPlayingCard';target.innerHTML='<span>TURN<br>A CARD</span>';return}target.className=`playingCard${c.red?' red':''}`;if(c.joker)target.innerHTML=`<div class="jokerWord">★<br>${c.red?'RED':'BLACK'}<br>JOKER</div>`;else target.innerHTML=`<div class="cardCorner top">${esc(c.rank)}<span>${c.suit}</span></div><div class="cardSuit">${c.suit}</div><div class="cardCorner bottom">${esc(c.rank)}<span>${c.suit}</span></div>`}
  function renderCardPlay(){const next=card.players[card.current],last=card.last;$('cardJustTurned').classList.toggle('hidden',!last);$('cardJustTurnedName').textContent=last?`${last.playerName} turned`:'';renderCardFace($('cardFace'),last);$('cardPenalty').textContent=last?(card.rules[last.ruleKey]||'No penalty'):'Turn the first card to begin.';$('cardNextName').textContent=card.deck.length&&next?next.name:'Deck finished';const localTurn=!cardNet.active||cardNet.localPlayerId===next?.id;$('cardDrawButton').disabled=!card.deck.length||!localTurn;$('cardDrawButton').textContent=!card.deck.length?'Deck finished':localTurn?(cardNet.active?'Turn your card':`Turn card for ${next.name}`):`${next.name}'s turn`;$('cardDeckCount').textContent=`${card.deck.length} cards left`;const hist=$('cardRecent');hist.innerHTML='';card.history.slice(0,8).forEach(h=>{const row=document.createElement('div');row.className='miniHistory';row.innerHTML=`<strong>${esc(h.playerName)}</strong><span>${esc(h.label)} · ${esc(card.rules[h.ruleKey]||'No penalty')}</span>`;hist.appendChild(row)});const badge=$('cardNetworkBadge');if(badge){badge.classList.toggle('show',cardNet.active);badge.classList.toggle('yourTurn',cardNet.active&&localTurn&&!!card.deck.length);badge.classList.toggle('waiting',cardNet.active&&!localTurn);badge.textContent=cardNet.active?(!card.deck.length?'Wi-Fi game · deck finished':localTurn?`Your turn — you are ${next.name}`:`Waiting for ${next.name} to turn a card`):''}if($('cardRestart'))$('cardRestart').disabled=cardNet.active&&cardNet.role==='client'}
  function restartCardGame(){if(!card.players.length)return;if(cardNet.active&&cardNet.role==='client')return;card.deck=buildDeck();card.current=0;card.last=null;card.history=[];card.playing=true;renderCardPlay();if(cardNet.active)broadcastCardState()}
  function cardSnapshot(){return{name:card.name,players:card.players,rules:card.rules,deck:card.deck,current:card.current,last:card.last,history:card.history,playing:card.playing}}
  function applyCardSnapshot(s){card.name=s.name||'';card.players=Array.isArray(s.players)?s.players:[];card.rules={...Object.fromEntries(ruleKeys.map(k=>[k,''])),...(s.rules||{})};card.deck=Array.isArray(s.deck)?s.deck:[];card.current=Number(s.current)||0;card.last=s.last||null;card.history=Array.isArray(s.history)?s.history:[];card.playing=!!s.playing;renderCardPlay();showView('cards-play')}
  function broadcastCardState(){cardNet.session?.broadcast({type:'card-state',state:cardSnapshot()})}
  function saveCardSetup(){const name=$('cardGameName').value.trim();if(!name)return setText('cardStatus','Give this setup a name first.');const items=read(CARD_SAVE_KEY,[]),selectedIds=selection(CARD_SELECTION_KEY,4),item={id:uid(),name,players:selectedIds,rules:{...card.rules}},existing=items.findIndex(x=>String(x.name).toLowerCase()===name.toLowerCase());if(existing>=0){item.id=items[existing].id;items[existing]=item}else items.unshift(item);write(CARD_SAVE_KEY,items);renderCardSaves();setText('cardStatus',`Saved “${name}”.`)}
  function renderCardSaves(){const wrap=$('cardSaved'),items=read(CARD_SAVE_KEY,[]);wrap.innerHTML='';if(!items.length)return wrap.innerHTML='<div class="emptyNote">No saved setups.</div>';items.forEach(item=>{const row=document.createElement('div');row.className='savedRow';row.innerHTML=`<div><strong>${esc(item.name)}</strong><span>${Object.values(item.rules||{}).filter(Boolean).length} rules</span></div><div><button type="button" data-load>Load</button><button type="button" data-delete>Delete</button></div>`;row.querySelector('[data-load]').onclick=()=>{$('cardGameName').value=item.name;card.rules={...Object.fromEntries(ruleKeys.map(k=>[k,''])),...(item.rules||{})};const valid=new Set(roster().map(p=>p.id));write(CARD_SELECTION_KEY,(item.players||[]).filter(id=>valid.has(id)).slice(0,4));renderCardRules();renderAllPlayerPickers();syncAllLanPlayerSelects();setText('cardStatus',`Loaded “${item.name}”.`)};row.querySelector('[data-delete]').onclick=()=>{write(CARD_SAVE_KEY,items.filter(x=>x.id!==item.id));renderCardSaves()};wrap.appendChild(row)})}

  const coin={players:[],current:0,round:1,playing:false,winner:null,last:null,totals:new Map(),streaks:new Map(),goal:{mode:'free',target:3},coinsPerPlayer:new Map()};
  const coinNet={active:false,role:null,localPlayerId:null,session:null};
  function readCoinGoal(){const mode=$('coinGoalMode').value,target=Math.max(2,Math.min(20,parseInt($('coinGoalTarget').value,10)||3));$('coinGoalTarget').value=String(target);return{mode,target}}
  function goalLabel(goal){const n=goal.target;return({'free':'Free play','total-heads':`First to ${n} Heads`,'total-tails':`First to ${n} Tails`,'streak-heads':`First to ${n} Heads in a row`,'streak-tails':`First to ${n} Tails in a row`,'streak-either':`First to ${n} matching flips in a row`})[goal.mode]||'Free play'}
  function renderCoinPlayerSettings(){const wrap=$('coinPlayerSettings');wrap.innerHTML='';selectedPeople(COIN_SELECTION_KEY,4).forEach(person=>{const current=coin.coinsPerPlayer.get(person.id)||1,row=document.createElement('label');row.className='coinPlayerSetting';row.innerHTML=`<strong>${esc(person.name)}</strong><span>Coins per turn</span><input type="number" min="1" max="20" inputmode="numeric" value="${current}">`;row.querySelector('input').onchange=e=>{const n=Math.max(1,Math.min(20,parseInt(e.target.value,10)||1));e.target.value=String(n);coin.coinsPerPlayer.set(person.id,n)};wrap.appendChild(row)})}
  function resetCoinNetForLocal(){coinNet.active=false;coinNet.role=null;coinNet.localPlayerId=null;const b=$('coinNetworkBadge');if(b)b.className='networkBadge'}
  function initialiseCoin(players){coin.players=players;coin.current=0;coin.round=1;coin.playing=true;coin.winner=null;coin.last=null;coin.goal=readCoinGoal();coin.totals=new Map();coin.streaks=new Map();players.forEach(p=>{coin.totals.set(p.id,{H:0,T:0});coin.streaks.set(p.id,{H:0,T:0,eitherSide:null,either:0});if(!coin.coinsPerPlayer.has(p.id))coin.coinsPerPlayer.set(p.id,1)})}
  function startCoinGame(){const players=selectedPeople(COIN_SELECTION_KEY,4);if(!players.length)return setText('coinStatus','Select at least one player.');resetCoinNetForLocal();initialiseCoin(players);renderCoinPlay();showView('coins-play')}
  function checkCoinWin(person){if(coin.goal.mode==='free')return false;const total=coin.totals.get(person.id),streak=coin.streaks.get(person.id),n=coin.goal.target;if(coin.goal.mode==='total-heads')return total.H>=n;if(coin.goal.mode==='total-tails')return total.T>=n;if(coin.goal.mode==='streak-heads')return streak.H>=n;if(coin.goal.mode==='streak-tails')return streak.T>=n;if(coin.goal.mode==='streak-either')return streak.either>=n;return false}
  function performCoinFlip(){if(!coin.playing||coin.winner)return;const person=coin.players[coin.current],count=coin.coinsPerPlayer.get(person.id)||1,results=Array.from({length:count},coinResult),total=coin.totals.get(person.id),streak=coin.streaks.get(person.id);for(const result of results){total[result]++;streak.H=result==='H'?streak.H+1:0;streak.T=result==='T'?streak.T+1:0;if(streak.eitherSide===result)streak.either++;else{streak.eitherSide=result;streak.either=1}}coin.last={person,results};if(checkCoinWin(person)){coin.winner=person;coin.playing=false}else{coin.current++;if(coin.current>=coin.players.length){coin.current=0;coin.round++}}renderCoinPlay();if(coinNet.active&&coinNet.role==='host')broadcastCoinState()}
  function requestCoinFlip(){if(!coinNet.active)return performCoinFlip();const current=coin.players[coin.current];if(!current||coinNet.localPlayerId!==current.id)return;if(coinNet.role==='host')performCoinFlip();else coinNet.session.sendToHost({type:'coin-action',action:'flip'})}
  function coinProgress(person){const total=coin.totals.get(person.id)||{H:0,T:0},streak=coin.streaks.get(person.id)||{H:0,T:0,either:0,eitherSide:null},n=coin.goal.target;if(coin.goal.mode==='total-heads')return`${total.H} / ${n} Heads`;if(coin.goal.mode==='total-tails')return`${total.T} / ${n} Tails`;if(coin.goal.mode==='streak-heads')return`${streak.H} / ${n} Heads in a row`;if(coin.goal.mode==='streak-tails')return`${streak.T} / ${n} Tails in a row`;if(coin.goal.mode==='streak-either')return`${streak.either} / ${n} ${streak.eitherSide==='H'?'Heads':streak.eitherSide==='T'?'Tails':'matching'} in a row`;return`${total.H} Heads · ${total.T} Tails`}
  function renderCoinPlay(){$('coinGoalBanner').textContent=goalLabel(coin.goal);const last=coin.last;$('coinJustFlipped').classList.toggle('hidden',!last);$('coinJustFlippedName').textContent=last?`${last.person.name} flipped`:'';const grid=$('coinResults');grid.innerHTML='';if(!last)grid.innerHTML='<div class="coinPlaceholder">Flip to begin</div>';else last.results.forEach(r=>{const el=document.createElement('div');el.className=`bigCoin ${r==='T'?'tails':''}`;el.textContent=r==='H'?'H':'T';grid.appendChild(el)});const progress=$('coinProgress');progress.innerHTML='';coin.players.forEach(p=>{const row=document.createElement('div');row.className=`progressRow${coin.winner?.id===p.id?' winner':''}`;row.innerHTML=`<strong>${esc(p.name)}</strong><span>${esc(coinProgress(p))}</span>`;progress.appendChild(row)});$('coinWinner').classList.toggle('hidden',!coin.winner);if(coin.winner)$('coinWinner').innerHTML=`<span>🏆 WINNER</span><strong>${esc(coin.winner.name)}</strong><small>${esc(goalLabel(coin.goal))}</small>`;const next=coin.winner?null:coin.players[coin.current],localTurn=!coinNet.active||coinNet.localPlayerId===next?.id;$('coinNextName').textContent=coin.winner?'Game over':next?.name||'—';$('coinFlipButton').disabled=!!coin.winner||!localTurn;$('coinFlipButton').textContent=coin.winner?'Game over':localTurn?(coinNet.active?'Flip your coins':`Flip for ${next.name}`):`${next.name}'s turn`;const badge=$('coinNetworkBadge');if(badge){badge.classList.toggle('show',coinNet.active);badge.classList.toggle('yourTurn',coinNet.active&&localTurn&&!coin.winner);badge.classList.toggle('waiting',coinNet.active&&!localTurn);badge.textContent=coinNet.active?(coin.winner?`Wi-Fi game · ${coin.winner.name} wins`:localTurn?`Your turn — you are ${next.name}`:`Waiting for ${next.name} to flip`):''}if($('coinRestart'))$('coinRestart').disabled=coinNet.active&&coinNet.role==='client'}
  function restartCoinGame(){if(!coin.players.length)return;if(coinNet.active&&coinNet.role==='client')return;if(coinNet.active){const players=[...coin.players],goal={...coin.goal},counts=new Map(coin.coinsPerPlayer);coin.players=players;coin.current=0;coin.round=1;coin.playing=true;coin.winner=null;coin.last=null;coin.goal=goal;coin.coinsPerPlayer=counts;coin.totals=new Map();coin.streaks=new Map();players.forEach(p=>{coin.totals.set(p.id,{H:0,T:0});coin.streaks.set(p.id,{H:0,T:0,eitherSide:null,either:0})});renderCoinPlay();broadcastCoinState()}else{write(COIN_SELECTION_KEY,coin.players.map(p=>p.id));startCoinGame()}}
  function coinSnapshot(){return{players:coin.players,current:coin.current,round:coin.round,playing:coin.playing,winner:coin.winner,last:coin.last,goal:coin.goal,totals:Object.fromEntries(coin.totals),streaks:Object.fromEntries(coin.streaks),coinsPerPlayer:Object.fromEntries(coin.coinsPerPlayer)}}
  function applyCoinSnapshot(s){coin.players=Array.isArray(s.players)?s.players:[];coin.current=Number(s.current)||0;coin.round=Number(s.round)||1;coin.playing=!!s.playing;coin.winner=s.winner||null;coin.last=s.last||null;coin.goal=s.goal||{mode:'free',target:3};coin.totals=new Map(Object.entries(s.totals||{}));coin.streaks=new Map(Object.entries(s.streaks||{}));coin.coinsPerPlayer=new Map(Object.entries(s.coinsPerPlayer||{}).map(([k,v])=>[k,Number(v)||1]));renderCoinPlay();showView('coins-play')}
  function broadcastCoinState(){coinNet.session?.broadcast({type:'coin-state',state:coinSnapshot()})}
  function saveCoinSetup(){const name=$('coinGameName').value.trim();if(!name)return setText('coinStatus','Give this setup a name first.');const items=read(COIN_SAVE_KEY,[]),item={id:uid(),name,players:selection(COIN_SELECTION_KEY,4),goal:readCoinGoal(),coins:Object.fromEntries(coin.coinsPerPlayer)},ix=items.findIndex(x=>String(x.name).toLowerCase()===name.toLowerCase());if(ix>=0){item.id=items[ix].id;items[ix]=item}else items.unshift(item);write(COIN_SAVE_KEY,items);renderCoinSaves();setText('coinStatus',`Saved “${name}”.`)}
  function renderCoinSaves(){const wrap=$('coinSaved'),items=read(COIN_SAVE_KEY,[]);wrap.innerHTML='';if(!items.length)return wrap.innerHTML='<div class="emptyNote">No saved setups.</div>';items.forEach(item=>{const row=document.createElement('div');row.className='savedRow';row.innerHTML=`<div><strong>${esc(item.name)}</strong><span>${esc(goalLabel(item.goal||{mode:'free',target:3}))}</span></div><div><button data-load>Load</button><button data-delete>Delete</button></div>`;row.querySelector('[data-load]').onclick=()=>{const valid=new Set(roster().map(p=>p.id));write(COIN_SELECTION_KEY,(item.players||[]).filter(id=>valid.has(id)).slice(0,4));$('coinGameName').value=item.name;const goal=item.goal||{mode:'free',target:3};$('coinGoalMode').value=goal.mode;$('coinGoalTarget').value=goal.target;coin.coinsPerPlayer=new Map(Object.entries(item.coins||{}));renderAllPlayerPickers();renderCoinPlayerSettings();syncAllLanPlayerSelects();setText('coinStatus',`Loaded “${item.name}”.`)};row.querySelector('[data-delete]').onclick=()=>{write(COIN_SAVE_KEY,items.filter(x=>x.id!==item.id));renderCoinSaves()};wrap.appendChild(row)})}

  function getNet(prefix){return prefix==='card'?cardNet:coinNet}
  function getSelected(prefix){return selectedPeople(prefix==='card'?CARD_SELECTION_KEY:COIN_SELECTION_KEY,4)}
  function syncLanHostPlayer(prefix){const select=$(`${prefix}LanHostPlayer`);if(!select)return;const net=getNet(prefix),people=getSelected(prefix),previous=select.value;select.innerHTML=people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(people.some(p=>p.id===previous))select.value=previous;if(!select.value&&people[0])select.value=people[0].id;if(net.role==='host'&&!net.active)net.localPlayerId=select.value||null;select.disabled=!!net.session?.peers().some(p=>p.meta?.playerId)}
  function syncAllLanPlayerSelects(){syncLanHostPlayer('card');syncLanHostPlayer('coin');renderLanDevices('card');renderLanDevices('coin')}
  function claimedPlayerIds(prefix){const net=getNet(prefix),set=new Set();if(net.localPlayerId)set.add(net.localPlayerId);net.session?.peers().forEach(p=>{if(p.meta?.playerId)set.add(p.meta.playerId)});return set}
  function renderLanDevices(prefix){const wrap=$(`${prefix}LanDevices`),net=getNet(prefix);if(!wrap)return;const self=getSelected(prefix).find(p=>p.id===net.localPlayerId);const peers=net.session?.peers()||[];let html='';if(self)html+=`<div class="lanDevice"><strong>${esc(self.name)}</strong><span>This phone · Host</span></div>`;peers.forEach(p=>{html+=`<div class="lanDevice"><strong>${esc(p.meta?.playerName||p.meta?.requestedName||'Connected phone')}</strong><span>${p.meta?.playerId?'Ready':'Needs player match'}</span></div>`});wrap.innerHTML=html||'<div class="lanNote">No phones connected yet.</div>';syncLanStart(prefix)}
  function syncLanStart(prefix){const btn=$(`${prefix}LanStart`),net=getNet(prefix),people=getSelected(prefix);if(!btn)return;const claimed=claimedPlayerIds(prefix);btn.disabled=!(net.role==='host'&&people.length>=2&&people.every(p=>claimed.has(p.id)))}
  function showLanMode(prefix,mode){const net=getNet(prefix);$(`${prefix}LanHost`).classList.toggle('hidden',mode!=='host');$(`${prefix}LanJoin`).classList.toggle('hidden',mode!=='join');if(mode==='host'){net.role='host';syncLanHostPlayer(prefix);setLanStatus(prefix,'Choose which selected player uses this phone, then create an invite for each friend.','Host:')}else{net.role='client';setLanStatus(prefix,'Paste the host invite and enter the same player name the host selected for you.','Join:')}}
  function installNetSession(prefix){const net=getNet(prefix);net.session=new GameBoxLAN.Session({game:prefix==='card'?'house-rules':'coin-flip',onStatus:text=>setLanStatus(prefix,text,net.role==='host'?'Host:':'Join:'),onPeersChanged:()=>{if(net.role==='client'&&net.session.clientChannel?.readyState==='open'){const name=$(`${prefix}LanJoinName`).value.trim();if(name)net.session.sendToHost({type:'hello',name})}renderLanDevices(prefix)},onMessage:(msg,source)=>handleLanMessage(prefix,msg,source)})}
  function handleLanMessage(prefix,msg,source){const net=getNet(prefix);if(source.role==='host'){
      if(msg.type==='hello'){assignPeer(prefix,source.peer,msg.name);return}
      if(prefix==='card'&&msg.type==='card-action'&&msg.action==='draw'){const current=card.players[card.current];if(cardNet.active&&source.peer.meta?.playerId===current?.id)performCardDraw();return}
      if(prefix==='coin'&&msg.type==='coin-action'&&msg.action==='flip'){const current=coin.players[coin.current];if(coinNet.active&&source.peer.meta?.playerId===current?.id)performCoinFlip();return}
    }else{
      if(msg.type==='assigned'){net.localPlayerId=msg.player.id;net.active=false;setLanStatus(prefix,`Connected as ${msg.player.name}. Waiting for the host to start.`,'Ready:');return}
      if(msg.type==='assignment-error'){setLanStatus(prefix,msg.message||'Your player name did not match the host setup.','Not assigned:');return}
      if(prefix==='card'&&(msg.type==='card-start'||msg.type==='card-state')){cardNet.active=true;cardNet.role='client';applyCardSnapshot(msg.state);return}
      if(prefix==='coin'&&(msg.type==='coin-start'||msg.type==='coin-state')){coinNet.active=true;coinNet.role='client';applyCoinSnapshot(msg.state);return}
    }}
  function assignPeer(prefix,peer,requested){const net=getNet(prefix),people=getSelected(prefix),requestedName=String(requested||'').trim(),claimed=claimedPlayerIds(prefix);peer.meta.requestedName=requestedName;let match=people.find(p=>p.name.toLowerCase()===requestedName.toLowerCase()&&!claimed.has(p.id));const open=people.filter(p=>!claimed.has(p.id));if(!match&&open.length===1)match=open[0];if(!match){net.session.sendToPeer(peer,{type:'assignment-error',message:`Name not matched. Available: ${open.map(p=>p.name).join(', ')||'none'}`});renderLanDevices(prefix);return}peer.meta.playerId=match.id;peer.meta.playerName=match.name;net.session.sendToPeer(peer,{type:'assigned',player:match});setLanStatus(prefix,`${match.name}'s phone connected.`,'Connected:');renderLanDevices(prefix)}
  async function createInvite(prefix){if(!lanAvailable())return setLanStatus(prefix,'This browser does not support peer-to-peer WebRTC.');const net=getNet(prefix),people=getSelected(prefix);if(people.length<2)return setLanStatus(prefix,'Select at least two players first.');net.role='host';net.localPlayerId=$(`${prefix}LanHostPlayer`).value||people[0].id;try{$(`${prefix}LanOffer`).value=await net.session.createHostOffer();setLanStatus(prefix,'Send the invite to one friend, then paste their answer below.','Invite ready:')}catch(err){console.error(err);setLanStatus(prefix,'Could not create an invite on this browser.','Error:')}}
  async function acceptAnswer(prefix){const net=getNet(prefix);try{await net.session.acceptHostAnswer($(`${prefix}LanAnswerIn`).value);$(`${prefix}LanAnswerIn`).value='';$(`${prefix}LanOffer`).value='';setLanStatus(prefix,'Connection is being established.','Connecting:')}catch(err){console.error(err);setLanStatus(prefix,'That answer code could not be accepted.','Error:')}}
  async function makeAnswer(prefix){if(!lanAvailable())return setLanStatus(prefix,'This browser does not support peer-to-peer WebRTC.');const net=getNet(prefix),name=$(`${prefix}LanJoinName`).value.trim();if(!name)return setLanStatus(prefix,'Enter your player name first.');net.role='client';try{$(`${prefix}LanAnswerOut`).value=await net.session.createClientAnswer($(`${prefix}LanOfferIn`).value);setLanStatus(prefix,'Send the answer back to the host. Keep this page open.','Answer ready:')}catch(err){console.error(err);setLanStatus(prefix,'That invite code could not be read.','Error:')}}
  function startWifiCard(){const people=getSelected('card'),net=cardNet;if(!people.every(p=>claimedPlayerIds('card').has(p.id)))return setLanStatus('card','Every selected player needs an assigned phone before starting.');card.players=people;card.name=$('cardGameName').value.trim();card.deck=buildDeck();card.current=0;card.last=null;card.history=[];card.playing=true;net.active=true;net.role='host';net.session.broadcast({type:'card-start',state:cardSnapshot()});renderCardPlay();showView('cards-play')}
  function startWifiCoin(){const people=getSelected('coin'),net=coinNet;if(!people.every(p=>claimedPlayerIds('coin').has(p.id)))return setLanStatus('coin','Every selected player needs an assigned phone before starting.');initialiseCoin(people);net.active=true;net.role='host';net.session.broadcast({type:'coin-start',state:coinSnapshot()});renderCoinPlay();showView('coins-play')}
  function wireLanControls(prefix){$(`${prefix}LanHostMode`).onclick=()=>showLanMode(prefix,'host');$(`${prefix}LanJoinMode`).onclick=()=>showLanMode(prefix,'join');$(`${prefix}LanHostPlayer`).onchange=e=>{const net=getNet(prefix);net.localPlayerId=e.target.value;renderLanDevices(prefix)};$(`${prefix}LanCreateInvite`).onclick=()=>createInvite(prefix);$(`${prefix}LanAcceptAnswer`).onclick=()=>acceptAnswer(prefix);$(`${prefix}LanMakeAnswer`).onclick=()=>makeAnswer(prefix);$(`${prefix}LanJoinName`).onchange=()=>{const net=getNet(prefix);if(net.role==='client'&&net.session.clientChannel?.readyState==='open')net.session.sendToHost({type:'hello',name:$(`${prefix}LanJoinName`).value.trim()})};$(`${prefix}LanStart`).onclick=prefix==='card'?startWifiCard:startWifiCoin}

  function init(){installLanPanel('card','House Rules','cards-setup');installLanPanel('coin','Coin Flip','coins-setup');installNetworkBadge('cards-play','card');installNetworkBadge('coins-play','coin');installNetSession('card');installNetSession('coin');renderHomeRoster();renderCardRules();renderCardSaves();renderCoinSaves();setupPicker('cardPlayerPicker',CARD_SELECTION_KEY,4,()=>syncLanHostPlayer('card'));setupPicker('coinPlayerPicker',COIN_SELECTION_KEY,4,()=>{renderCoinPlayerSettings();syncLanHostPlayer('coin')});wireLanControls('card');wireLanControls('coin');$('addPlayer').onclick=addHomePlayer;$('newPlayerName').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addHomePlayer()}};document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>showView(btn.dataset.go));$('cardExamples').onclick=()=>{card.rules={...card.rules,...exampleRules};renderCardRules()};$('cardClearRules').onclick=()=>{card.rules=Object.fromEntries(ruleKeys.map(k=>[k,'']));renderCardRules()};$('cardStart').onclick=startCardGame;$('cardDrawButton').onclick=requestCardDraw;$('cardRestart').onclick=restartCardGame;$('cardSave').onclick=saveCardSetup;$('coinGoalMode').onchange=()=>{$('coinGoalTargetWrap').classList.toggle('hidden',$('coinGoalMode').value==='free')};$('coinGoalTargetWrap').classList.toggle('hidden',$('coinGoalMode').value==='free');$('coinStart').onclick=startCoinGame;$('coinFlipButton').onclick=requestCoinFlip;$('coinRestart').onclick=restartCoinGame;$('coinSave').onclick=saveCoinSetup;syncAllLanPlayerSelects()}
  init();
})();