(() => {
  const $ = id => document.getElementById(id);
  const CUSTOM_KEY='gamebox.heads.custom.v1';
  const ROUNDS_KEY='gamebox.heads.rounds.v1';
  const DURATIONS=[30,45,60,90];
  const TILT_THRESHOLD=60;
  const REARM_THRESHOLD=22;
  const TILT_HOLD_MS=90;
  const REARM_HOLD_MS=100;

  const BUILTIN={
    movies:{name:'Movies',cards:['Jurassic Park','Titanic','The Matrix','Toy Story','Jaws','Ghostbusters','The Lion King','Home Alone','Gladiator','Finding Nemo','Shrek','Rocky','Back to the Future','Frozen','The Terminator','Harry Potter','The Avengers','Pirates of the Caribbean','The Godfather','E.T.','Star Wars','Indiana Jones','Men in Black','The Truman Show','Mean Girls']},
    animals:{name:'Animals',cards:['Elephant','Giraffe','Penguin','Kangaroo','Octopus','Gorilla','Crocodile','Flamingo','Dolphin','Hedgehog','Koala','Rhinoceros','Sloth','Peacock','Meerkat','Chameleon','Walrus','Ostrich','Jellyfish','Badger','Beagle','Lobster','Parrot','Polar Bear','Zebra']},
    food:{name:'Food & Drink',cards:['Pizza','Fish and Chips','Spaghetti','Chocolate','Cheeseburger','Sushi','Pancakes','Ice Cream','Curry','Popcorn','Tacos','Lasagne','Doughnut','Apple Pie','Hot Dog','Burrito','Milkshake','Cupcake','Nachos','Paella','Croissant','Peanut Butter','Watermelon','Coffee','Lemonade']},
    people:{name:'Famous People',cards:['Taylor Swift','David Beckham','Adele','Tom Hanks','Beyoncé','Elton John','Gordon Ramsay','Ed Sheeran','Dwayne Johnson','Lady Gaga','Daniel Radcliffe','Serena Williams','Leonardo DiCaprio','Rihanna','Lewis Hamilton','Dolly Parton','Keanu Reeves','Usain Bolt','Jennifer Aniston','Bruno Mars','Emma Watson','Will Smith','Shakira','Chris Hemsworth','Meryl Streep']},
    places:{name:'Places',cards:['London','Paris','New York','Rome','Tokyo','Sydney','Las Vegas','Dubai','Barcelona','Amsterdam','Hawaii','The Grand Canyon','Mount Everest','Disneyland','Stonehenge','The Eiffel Tower','The Great Wall of China','Hollywood','Venice','The Sahara Desert','Buckingham Palace','Niagara Falls','The North Pole','Times Square','Loch Ness']},
    sports:{name:'Sports',cards:['Football','Rugby','Tennis','Cricket','Golf','Boxing','Formula One','Basketball','Baseball','Swimming','Darts','Snooker','Cycling','Skiing','Surfing','Volleyball','Badminton','Gymnastics','Ice Hockey','Horse Racing','Table Tennis','Archery','Rowing','Wrestling','Skateboarding']},
    music:{name:'Music',cards:['The Beatles','Queen','ABBA','Coldplay','Oasis','Spice Girls','Michael Jackson','Madonna','Fleetwood Mac','Foo Fighters','Ariana Grande','Billie Eilish','Kylie Minogue','George Michael','Whitney Houston','Britney Spears','Bon Jovi','Dua Lipa','Stevie Wonder','Celine Dion','The Rolling Stones','Katy Perry','Eminem','Elvis Presley','Take That']},
    objects:{name:'Everyday Objects',cards:['Toothbrush','Umbrella','Remote Control','Toaster','Vacuum Cleaner','Shopping Trolley','Hairdryer','Alarm Clock','Sunglasses','Kettle','Headphones','Doorbell','Wheelbarrow','Pillow','Stapler','Backpack','Torch','Ladder','Scissors','Mirror','Washing Machine','Suitcase','Frying Pan','Binoculars','Rubber Duck']}
  };

  const state={
    duration:60,selected:new Set(['movies']),deck:[],current:null,history:[],correct:0,passes:0,
    player:'Player 1',roundName:'',extraCards:[],playing:false,endAt:0,timer:null,countdown:null,
    tiltEnabled:false,latestTilt:null,baseline:0,tiltSamples:[],tiltArmed:true,candidate:null,candidateSince:0,neutralSince:0,
    motionHandler:null,orientationHandler:null,editCustomId:null,audioCtx:null,pendingStart:false,landscapeSession:false
  };

  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const readStore=key=>{try{return JSON.parse(localStorage.getItem(key))||[]}catch{return[]}};
  const writeStore=(key,v)=>localStorage.setItem(key,JSON.stringify(v));
  const lines=v=>[...new Set(String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];
  const shuffle=input=>{const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const deg=d=>d*Math.PI/180;
  const wrapDelta=d=>((d+540)%360)-180;
  const circularMean=values=>{if(!values.length)return 0;let s=0,c=0;for(const v of values){s+=Math.sin(deg(v));c+=Math.cos(deg(v))}return Math.atan2(s,c)*180/Math.PI};

  function allCategories(){const built=Object.entries(BUILTIN).map(([id,v])=>({id,type:'builtin',name:v.name,cards:[...v.cards]}));const custom=readStore(CUSTOM_KEY).map(x=>({id:x.id,type:'custom',name:x.name,cards:[...(x.cards||[])]}));return [...built,...custom]}
  function renderTimers(){const w=$('headsTimer');w.innerHTML='';DURATIONS.forEach(n=>{const b=document.createElement('button');b.type='button';b.textContent=`${n}s`;b.className=n===state.duration?'active':'';b.onclick=()=>{state.duration=n;renderTimers()};w.appendChild(b)})}
  function renderCategories(){const w=$('headsCategories');w.innerHTML='';allCategories().forEach(cat=>{const l=document.createElement('label');l.className='headsCategory';l.innerHTML=`<input type="checkbox" ${state.selected.has(cat.id)?'checked':''}><span class="headsCategoryCard"><strong>${esc(cat.name)}</strong><span>${cat.cards.length} cards${cat.type==='custom'?' · custom':''}</span></span>`;l.querySelector('input').onchange=e=>e.target.checked?state.selected.add(cat.id):state.selected.delete(cat.id);w.appendChild(l)})}
  function renderCustomList(){const w=$('headsCustomList'),items=readStore(CUSTOM_KEY);w.innerHTML='';if(!items.length){w.innerHTML='<div class="sub" style="margin:0">No custom categories yet.</div>';return}items.forEach(item=>{const d=document.createElement('div');d.className='headsCustomItem';d.innerHTML=`<div class="headsPresetInfo"><strong>${esc(item.name)}</strong><span>${(item.cards||[]).length} cards</span></div><div class="headsPresetActions"><button class="tiny edit">Edit</button><button class="tiny del">Delete</button></div>`;d.querySelector('.edit').onclick=()=>{state.editCustomId=item.id;$('headsCustomName').value=item.name;$('headsCustomCards').value=(item.cards||[]).join('\n');$('headsSaveCategory').textContent='Update Custom Category';$('headsCustomStatus').textContent=`Editing “${item.name}”.`};d.querySelector('.del').onclick=()=>{writeStore(CUSTOM_KEY,items.filter(x=>x.id!==item.id));state.selected.delete(item.id);if(state.editCustomId===item.id)clearCustomForm();renderCustomList();renderCategories()};w.appendChild(d)})}
  function clearCustomForm(){state.editCustomId=null;$('headsCustomName').value='';$('headsCustomCards').value='';$('headsSaveCategory').textContent='Save Custom Category'}
  function saveCustomCategory(){const name=$('headsCustomName').value.trim(),cards=lines($('headsCustomCards').value);if(!name){$('headsCustomStatus').textContent='Give the category a name.';return}if(!cards.length){$('headsCustomStatus').textContent='Add at least one card.';return}const items=readStore(CUSTOM_KEY);if(state.editCustomId){const ix=items.findIndex(x=>x.id===state.editCustomId);if(ix>=0)items[ix]={...items[ix],name,cards};$('headsCustomStatus').textContent=`Updated “${name}”.`}else{const id=uid();items.unshift({id,name,cards});state.selected.add(id);$('headsCustomStatus').textContent=`Created “${name}”.`}writeStore(CUSTOM_KEY,items);clearCustomForm();renderCustomList();renderCategories()}
  function collectSetup(){state.roundName=$('headsRoundName').value.trim();state.player=$('headsPlayerName').value.trim()||'Player 1';state.extraCards=lines($('headsExtraCards').value)}
  function roundPayload(id=null){collectSetup();return{id:id||uid(),name:state.roundName||'Saved Round',player:state.player,duration:state.duration,categories:[...state.selected],extraCards:[...state.extraCards]}}
  function saveRound(){collectSetup();if(!state.roundName){$('headsStatus').textContent='Give the round a name before saving.';$('headsRoundName').focus();return}if(!state.selected.size&&!state.extraCards.length){$('headsStatus').textContent='Select a category or add extra cards first.';return}const items=readStore(ROUNDS_KEY),ix=items.findIndex(x=>String(x.name).toLowerCase()===state.roundName.toLowerCase()),p=roundPayload(ix>=0?items[ix].id:null);if(ix>=0)items[ix]=p;else items.unshift(p);writeStore(ROUNDS_KEY,items);renderSavedRounds();$('headsStatus').textContent=`Saved “${state.roundName}”.`}
  function renderSavedRounds(){const w=$('headsSavedRounds'),items=readStore(ROUNDS_KEY);w.innerHTML='';if(!items.length){w.innerHTML='<div class="sub" style="margin:0">No saved rounds yet.</div>';return}items.forEach(item=>{const d=document.createElement('div');d.className='headsPresetLine';d.innerHTML=`<div class="headsPresetInfo"><strong>${esc(item.name)}</strong><span>${item.duration}s · ${(item.categories||[]).length} categories · ${(item.extraCards||[]).length} extra</span></div><div class="headsPresetActions"><button class="tiny load">Load</button><button class="tiny del">Delete</button></div>`;d.querySelector('.load').onclick=()=>loadRound(item.id);d.querySelector('.del').onclick=()=>{writeStore(ROUNDS_KEY,items.filter(x=>x.id!==item.id));renderSavedRounds()};w.appendChild(d)})}
  function loadRound(id){const item=readStore(ROUNDS_KEY).find(x=>x.id===id);if(!item)return;state.roundName=item.name||'';state.player=item.player||'Player 1';state.duration=DURATIONS.includes(item.duration)?item.duration:60;state.selected=new Set(item.categories||[]);state.extraCards=[...(item.extraCards||[])];$('headsRoundName').value=state.roundName;$('headsPlayerName').value=state.player;$('headsExtraCards').value=state.extraCards.join('\n');renderTimers();renderCategories();$('headsStatus').textContent=`Loaded “${state.roundName}”.`}
  function makeDeck(){collectSetup();const deck=[];allCategories().filter(c=>state.selected.has(c.id)).forEach(cat=>cat.cards.forEach(word=>deck.push({word,category:cat.name})));state.extraCards.forEach(word=>deck.push({word,category:'Extra Cards'}));return shuffle(deck)}

  function setMode(mode){const setup=mode==='setup';$('headsSetup').classList.toggle('hidden',!setup);$('headsPlay').classList.toggle('hidden',setup);$('headsSetupTab').classList.toggle('active',setup);$('headsPlayTab').classList.toggle('active',!setup);if(setup){stopActiveRound();exitLandscapeSession()}window.scrollTo({top:0,behavior:'smooth'})}
  function startRoundSetup(){const deck=makeDeck();if(!deck.length){$('headsStatus').textContent='Select at least one category or add an extra card.';return}Object.assign(state,{deck,current:null,history:[],correct:0,passes:0,playing:false,latestTilt:null,baseline:0,tiltSamples:[],tiltArmed:true,candidate:null,candidateSince:0,neutralSince:0,pendingStart:false});$('headsReadyTitle').textContent=state.roundName||'Ready?';$('headsReadyMeta').textContent=`${state.player} · ${state.duration} seconds · ${deck.length} cards available`;$('headsReady').classList.remove('hidden');$('headsCountdownWrap').classList.add('hidden');$('headsLive').classList.add('hidden');$('headsResults').classList.add('hidden');$('headsTiltState').textContent='When you begin, rotate the phone to landscape and hold it against your forehead.';setMode('play')}

  function getAudio(){try{if(!state.audioCtx){const C=window.AudioContext||window.webkitAudioContext;if(C)state.audioCtx=new C()}if(state.audioCtx?.state==='suspended')state.audioCtx.resume();return state.audioCtx}catch{return null}}
  function playCorrectSound(){const ctx=getAudio();if(!ctx)return;const n=ctx.currentTime,g=ctx.createGain();g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.25,n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+.34);g.connect(ctx.destination);[880,1320].forEach((f,i)=>{const o=ctx.createOscillator();o.type='sine';o.frequency.value=f;o.connect(g);o.start(n+i*.04);o.stop(n+.34)})}
  function playPassSound(){const ctx=getAudio();if(!ctx)return;const n=ctx.currentTime,g=ctx.createGain();g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.2,n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+.52);g.connect(ctx.destination);const o1=ctx.createOscillator(),o2=ctx.createOscillator();o1.type='sawtooth';o2.type='square';o1.frequency.setValueAtTime(250,n);o1.frequency.exponentialRampToValueAtTime(100,n+.45);o2.frequency.setValueAtTime(165,n+.07);o2.frequency.exponentialRampToValueAtTime(78,n+.48);o1.connect(g);o2.connect(g);o1.start(n);o2.start(n+.07);o1.stop(n+.5);o2.stop(n+.52)}

  function screenAngle(){const a=screen.orientation?.angle;return Number.isFinite(a)?a:(Number(window.orientation)||0)}
  function visualVerticalComponent(x,y){const r=deg(screenAngle());return x*Math.sin(r)+y*Math.cos(r)}
  function motionPitch(e){const a=e.accelerationIncludingGravity;if(!a)return null;const x=Number(a.x),y=Number(a.y),z=Number(a.z);if(![x,y,z].every(Number.isFinite)||Math.hypot(x,y,z)<4)return null;const v=visualVerticalComponent(x,y);return Math.atan2(z,v)*180/Math.PI}
  function orientationPitch(e){const beta=Number(e.beta),gamma=Number(e.gamma);if(!Number.isFinite(beta)||!Number.isFinite(gamma))return null;const b=deg(beta),g=deg(gamma);const x=-Math.sin(g)*Math.cos(b),y=Math.sin(b),z=Math.cos(g)*Math.cos(b);const v=visualVerticalComponent(x,y);return Math.atan2(z,v)*180/Math.PI}
  function acceptTilt(v){if(!Number.isFinite(v))return;state.latestTilt=v;if(!state.playing){state.tiltSamples.push(v);if(state.tiltSamples.length>80)state.tiltSamples.shift()}else processTilt(v)}

  async function enableTilt(){state.tiltEnabled=false;state.latestTilt=null;state.tiltSamples=[];getAudio();let motion=false,orient=false;try{if('DeviceMotionEvent'in window){motion=typeof DeviceMotionEvent.requestPermission==='function'?(await DeviceMotionEvent.requestPermission())==='granted':true}}catch{}try{if('DeviceOrientationEvent'in window){orient=typeof DeviceOrientationEvent.requestPermission==='function'?(await DeviceOrientationEvent.requestPermission())==='granted':true}}catch{}if(state.motionHandler)window.removeEventListener('devicemotion',state.motionHandler,true);if(state.orientationHandler)window.removeEventListener('deviceorientation',state.orientationHandler,true);if(motion){state.motionHandler=e=>acceptTilt(motionPitch(e));window.addEventListener('devicemotion',state.motionHandler,true);state.tiltEnabled=true}else if(orient){state.orientationHandler=e=>acceptTilt(orientationPitch(e));window.addEventListener('deviceorientation',state.orientationHandler,true);state.tiltEnabled=true}$('headsTiltState').textContent=state.tiltEnabled?'Motion ready. Rotate to landscape and hold the phone still against your forehead.':'Motion permission unavailable. You can still use the fallback buttons.'}

  function processTilt(value){if(!state.playing)return;const delta=wrapDelta(value-state.baseline),abs=Math.abs(delta),now=performance.now();const direction=delta<=-TILT_THRESHOLD?'DOWN · CORRECT':delta>=TILT_THRESHOLD?'UP · PASS':delta<0?'moving down':'moving up';$('headsTiltReadout').textContent=`${Math.round(abs)}° ${direction}`;if(!state.tiltArmed){state.candidate=null;state.candidateSince=0;if(abs<=REARM_THRESHOLD){if(!state.neutralSince)state.neutralSince=now;if(now-state.neutralSince>=REARM_HOLD_MS){state.tiltArmed=true;state.neutralSince=0;$('headsTiltReadout').textContent='Ready — tilt 60°'}}else state.neutralSince=0;return}state.neutralSince=0;let action=null;if(delta<=-TILT_THRESHOLD)action='correct';else if(delta>=TILT_THRESHOLD)action='pass';if(!action){state.candidate=null;state.candidateSince=0;return}if(state.candidate!==action){state.candidate=action;state.candidateSince=now;return}if(now-state.candidateSince<TILT_HOLD_MS)return;state.tiltArmed=false;state.candidate=null;state.candidateSince=0;markCurrent(action)}

  function ensureRotateOverlay(){let o=$('headsRotateOverlay');if(o)return o;o=document.createElement('div');o.id='headsRotateOverlay';o.className='headsRotateOverlay';o.innerHTML='<div class="rotatePhone">↻</div><strong>Rotate your phone</strong><span>Heads Up is played in landscape.</span>';document.body.appendChild(o);return o}
  function isLandscape(){return matchMedia('(orientation: landscape)').matches||innerWidth>innerHeight}
  function updateRotateOverlay(){const o=ensureRotateOverlay();o.classList.toggle('show',state.landscapeSession&&!isLandscape())}
  async function enterLandscapeSession(){state.landscapeSession=true;document.body.classList.add('headsLandscapePlay');updateRotateOverlay();try{if(screen.orientation?.lock)await screen.orientation.lock('landscape')}catch{}}
  function exitLandscapeSession(){state.landscapeSession=false;state.pendingStart=false;document.body.classList.remove('headsLandscapePlay');updateRotateOverlay();try{screen.orientation?.unlock?.()}catch{}}
  function maybeStartAfterRotate(){updateRotateOverlay();if(state.pendingStart&&isLandscape()){state.pendingStart=false;beginCountdown()}}
  window.addEventListener('orientationchange',()=>setTimeout(maybeStartAfterRotate,120));window.addEventListener('resize',maybeStartAfterRotate);

  function beginCountdown(){if(state.countdown)return;$('headsReady').classList.add('hidden');$('headsCountdownWrap').classList.remove('hidden');state.tiltSamples=[];let n=3;$('headsCountdown').textContent=n;state.countdown=setInterval(()=>{n--;if(n>0){$('headsCountdown').textContent=n;return}clearInterval(state.countdown);state.countdown=null;state.baseline=state.tiltSamples.length?circularMean(state.tiltSamples.slice(-40)):(state.latestTilt??0);state.tiltArmed=true;state.candidate=null;state.neutralSince=0;$('headsCountdownWrap').classList.add('hidden');$('headsLive').classList.remove('hidden');beginLiveRound()},1000)}
  function beginLiveRound(){state.playing=true;state.endAt=performance.now()+state.duration*1000;nextCard();tick();state.timer=setInterval(tick,100)}
  function tick(){if(!state.playing)return;const left=Math.max(0,state.endAt-performance.now());$('headsClock').textContent=(left/1000).toFixed(1);if(left<=0)finishRound()}
  function nextCard(){if(!state.deck.length){const rebuilt=makeDeck();state.deck=rebuilt.filter(x=>!state.history.slice(-10).some(h=>h.word===x.word));if(!state.deck.length)state.deck=rebuilt}state.current=state.deck.pop()||null;if(!state.current){finishRound();return}$('headsWord').textContent=state.current.word;$('headsCardCategory').textContent=state.current.category;$('headsLivePlayer').textContent=state.player;$('headsLiveScore').textContent=`${state.correct} correct`}
  function flashResult(action){const c=document.querySelector('.headsWordCard');if(c)c.animate([{transform:'scale(1)'},{transform:'scale(.96)'},{transform:'scale(1)'}],{duration:200});$('headsTiltReadout').textContent=action==='correct'?'✓ Correct — return to forehead':'Pass — return to forehead'}
  function markCurrent(action){if(!state.playing||!state.current)return;state.history.push({...state.current,result:action});if(action==='correct'){state.correct++;playCorrectSound();try{navigator.vibrate?.(35)}catch{}}else{state.passes++;playPassSound();try{navigator.vibrate?.([25,25,25])}catch{}}flashResult(action);nextCard()}
  function finishRound(){if(!state.playing)return;state.playing=false;if(state.timer){clearInterval(state.timer);state.timer=null}$('headsLive').classList.add('hidden');$('headsResults').classList.remove('hidden');$('headsFinalScore').textContent=state.correct;$('headsFinalLabel').textContent=state.correct===1?'correct answer':'correct answers';$('headsCorrectCount').textContent=state.correct;$('headsPassCount').textContent=state.passes;renderHistory()}
  function renderHistory(){const w=$('headsHistory');w.innerHTML='';if(!state.history.length){w.innerHTML='<div class="sub">No cards answered.</div>';return}state.history.forEach(h=>{const d=document.createElement('div');d.className=`headsHistoryItem ${h.result}`;d.innerHTML=`<div><strong>${esc(h.word)}</strong><span>${esc(h.category)}</span></div><b>${h.result==='correct'?'✓ Correct':'Pass'}</b>`;w.appendChild(d)})}
  function stopActiveRound(){state.playing=false;if(state.timer){clearInterval(state.timer);state.timer=null}if(state.countdown){clearInterval(state.countdown);state.countdown=null}}
  function playAgain(){stopActiveRound();state.deck=makeDeck();state.history=[];state.correct=0;state.passes=0;state.current=null;state.baseline=0;state.tiltSamples=[];state.tiltArmed=true;state.candidate=null;$('headsResults').classList.add('hidden');$('headsReady').classList.remove('hidden');$('headsReadyTitle').textContent=state.roundName||'Ready?';$('headsReadyMeta').textContent=`${state.player} · ${state.duration} seconds · ${state.deck.length} cards available`}

  $('headsSetupTab').onclick=()=>setMode('setup');$('headsPlayTab').onclick=()=>{if(state.deck.length||state.playing)setMode('play');else $('headsStatus').textContent='Start a round from Setup first.'};$('headsStart').onclick=startRoundSetup;$('headsSaveRound').onclick=saveRound;$('headsSaveCategory').onclick=saveCustomCategory;$('headsBegin').onclick=async()=>{await enableTilt();await enterLandscapeSession();if(isLandscape())beginCountdown();else{state.pendingStart=true;updateRotateOverlay()}};$('headsBackSetup').onclick=()=>setMode('setup');$('headsResultsSetup').onclick=()=>setMode('setup');$('headsAgain').onclick=playAgain;$('headsCorrect').onclick=()=>markCurrent('correct');$('headsPass').onclick=()=>markCurrent('pass');window.addEventListener('pagehide',stopActiveRound);const reverse=$('headsReverseTilt');if(reverse?.closest('.headsToggle'))reverse.closest('.headsToggle').style.display='none';ensureRotateOverlay();renderTimers();renderCategories();renderCustomList();renderSavedRounds();
})();
