(()=>{"use strict";
const KEY="gamebox_pipeworks_v1";
const D=["N","E","S","W"],DR=[-1,0,1,0],DC=[0,1,0,-1],OP={N:"S",E:"W",S:"N",W:"E"};
const packs=[
{id:"classic",name:"Classic Pipes",desc:"Pure rotate-and-connect puzzles.",unlock:0,count:50,mode:"classic"},
{id:"junctions",name:"Junction Works",desc:"Tees, branches and misleading routes.",unlock:12,count:50,mode:"junctions"},
{id:"locked",name:"Locked Lines",desc:"Some correctly placed modules cannot move.",unlock:35,count:50,mode:"locked"},
{id:"rush",name:"Pressure Rush",desc:"Restore the line before pressure drops.",unlock:70,count:50,mode:"rush"}
];
const fresh={coins:150,xp:0,stars:0,sound:true,lastReward:"",completed:{},lastPack:"classic",lastLevel:1};
let s=load(),pack=packs[0],level=1,tiles=[],size=5,sourcePort=null,targetPort=null,turns=0,timer=0,timerMax=0,timerId=null,daily=false,won=false,flowWinTimer=null,firstTurnShown=false;
const WATER_STEP_MS=180,WATER_SEGMENT_MS=650;
const q=x=>document.querySelector(x),qa=x=>Array.from(document.querySelectorAll(x));
function load(){try{return Object.assign({},fresh,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return Object.assign({},fresh)}}
function save(){localStorage.setItem(KEY,JSON.stringify(s));syncCoins()}
function rng(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let x=t;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296}}
function hash(v){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function today(){return new Date().toISOString().slice(0,10)}
function key(id,n){return id+":"+n}
function stars(id,n){return(s.completed[key(id,n)]||{}).stars||0}
function packDone(p){let n=0;for(let i=1;i<=p.count;i++)if(stars(p.id,i))n++;return n}
function totalDone(){return Object.keys(s.completed||{}).filter(k=>!k.startsWith("daily:")).length}
function view(id){qa(".view").forEach(v=>v.classList.toggle("active",v.id===id));window.scrollTo(0,0)}
function syncCoins(){qa("[data-coins]").forEach(e=>e.textContent=s.coins)}
function toast(t){const e=q("#toast");e.textContent=t;e.classList.add("show");clearTimeout(e.x);e.x=setTimeout(()=>e.classList.remove("show"),1800)}
function beep(f,d){if(!s.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,c=beep.c||(beep.c=new A),o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.value=f;g.gain.setValueAtTime(.025,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}}
function haptic(ms=8){try{navigator.vibrate?.(ms)}catch{}}
function soundIcon(){q("#homeSoundIcon").src=s.sound?"../assets/gamebox/kenney/icons/Game Icons/White/2x/audioOn.png":"../assets/gamebox/kenney/icons/Game Icons/White/2x/audioOff.png";q("#menuSound").textContent="SOUND: "+(s.sound?"ON":"OFF")}
function packIcon(id){const map={classic:"straight",junctions:"tee",locked:"corner",rush:"cross"};return '<img src="assets/karsiori/tiles/'+map[id]+'.png" alt="">'}
function home(){syncCoins();soundIcon();q("#statLevel").textContent=totalDone()+1;q("#statXp").textContent=s.xp;q("#statStars").textContent=s.stars;const p=packs.find(x=>x.id===s.lastPack)||packs[0];q("#continue").textContent="PLAY "+p.name.toUpperCase()+" · "+Math.min(s.lastLevel,p.count);const claimed=s.lastReward===today();q("#reward").classList.toggle("claimed",claimed);q("#rewardText").textContent=claimed?"CLAIMED · BACK TOMORROW":"CLAIM +50";const box=q("#packs");box.innerHTML="";packs.forEach(p=>{const open=s.stars>=p.unlock,b=document.createElement("button");b.className="packButton"+(open?"":" locked");b.innerHTML='<span class="packIcon">'+packIcon(p.id)+'</span><span class="packText"><b>'+p.name.toUpperCase()+'</b><small>'+(open?p.desc:"Unlock at "+p.unlock+" stars")+'</small></span><span class="packCount">'+packDone(p)+"/"+p.count+"</span>";b.onclick=()=>open?openPack(p):toast("EARN "+p.unlock+" STARS TO UNLOCK");box.appendChild(b)})}
function openPack(p){pack=p;s.lastPack=p.id;save();q("#packBanner").innerHTML="<h2>"+p.name.toUpperCase()+"</h2><p>"+p.desc+"</p>";levels();view("pack")}
function levels(){syncCoins();const box=q("#levels");box.innerHTML="";const max=Math.min(pack.count,Math.max(1,packDone(pack)+1));for(let i=1;i<=pack.count;i++){const st=stars(pack.id,i),open=i<=max,b=document.createElement("button");b.className="level"+(st?" done":"")+(open?"":" locked")+(open&&!st&&i===max?" current":"");b.innerHTML=i+"<small>"+(st?Array.from({length:st},()=>'<i class="miniStar"></i>').join(""):"")+"</small>";b.onclick=()=>open&&start(pack,i);box.appendChild(b)}}
function rot(d,r){return D[(D.indexOf(d)+r+4)%4]}
function con(t){return t.base.map(d=>rot(d,t.rot))}
function generate(seed,p){const R=rng(seed);size=5;const cells=size*size,path=[];let r=Math.floor(R()*size),c=0;path.push(r*size);for(c=0;c<size-1;c++){let nr=Math.floor(R()*size),limit=2;if(Math.abs(nr-r)>limit)nr=r+(nr>r?limit:-limit);nr=Math.max(0,Math.min(size-1,nr));while(r!==nr){r+=nr>r?1:-1;path.push(r*size+c)}path.push(r*size+c+1)}sourcePort={cell:path[0],side:"W"};targetPort={cell:path[path.length-1],side:"E"};const links=Array.from({length:cells},()=>[]);for(let i=0;i<path.length;i++){const idx=path[i],rr=Math.floor(idx/size),cc=idx%size;if(i===0)links[idx].push("W");if(i===path.length-1)links[idx].push("E");if(i){const z=path[i-1],zr=Math.floor(z/size),zc=z%size;links[idx].push(rr<zr?"S":rr>zr?"N":cc<zc?"E":"W")}if(i<path.length-1){const z=path[i+1],zr=Math.floor(z/size),zc=z%size;links[idx].push(rr<zr?"S":rr>zr?"N":cc<zc?"E":"W")}}const set=new Set(path),simple=[["N","S"],["E","W"],["N","E"],["E","S"],["S","W"],["W","N"],["N"],["E"],["S"],["W"]],busy=simple.concat([["N","E","S"],["E","S","W"],["S","W","N"],["W","N","E"],["N","E","S","W"]]);tiles=[];for(let i=0;i<cells;i++){const on=set.has(i),pool=p.mode==="classic"?simple:busy,base=on?Array.from(new Set(links[i])):pool[Math.floor(R()*pool.length)].slice();let locked=false,rn=Math.floor(R()*4);if(p.mode==="locked"&&on&&R()<.18){rn=0;locked=true}tiles.push({base,rot:rn,on,locked})}let wrong=tiles.filter(t=>t.on&&!t.locked&&t.rot!==0).length;if(wrong<3){for(const t of tiles){if(t.on&&!t.locked&&t.rot===0){t.rot=1+Math.floor(R()*3);if(++wrong>=3)break}}}}
function setEq(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
const canonical={end:["N"],straight:["N","S"],corner:["N","E"],tee:["N","E","S"],cross:["N","E","S","W"]};
function shape(t){const n=t.base.length;if(n===1)return"end";if(n===2)return OP[t.base[0]]===t.base[1]?"straight":"corner";if(n===3)return"tee";return"cross"}
function baseSpriteRot(t){const type=shape(t),want=canonical[type];for(let r=0;r<4;r++)if(setEq(want.map(d=>rot(d,r)),t.base))return r;return 0}
function spriteRot(t){return(baseSpriteRot(t)+t.rot)%4}
function edgeXY(d){return d==="N"?[50,0]:d==="E"?[100,50]:d==="S"?[50,100]:[0,50]}
function routeD(a,b){const A=edgeXY(a);if(!b)return`M${A[0]} ${A[1]} L50 50`;const B=edgeXY(b);return OP[a]===b?`M${A[0]} ${A[1]} L${B[0]} ${B[1]}`:`M${A[0]} ${A[1]} L50 50 L${B[0]} ${B[1]}`}
function renderPorts(){const board=q("#board"),a=board.querySelector('[data-i="'+sourcePort.cell+'"]'),b=board.querySelector('[data-i="'+targetPort.cell+'"]');if(!a||!b)return;q("#sourcePort").style.setProperty("--portTop",board.offsetTop+a.offsetTop+a.offsetHeight/2+"px");q("#targetPort").style.setProperty("--portTop",board.offsetTop+b.offsetTop+b.offsetHeight/2+"px")}
function draw(){const board=q("#board");board.innerHTML="";tiles.forEach((t,i)=>{const e=document.createElement("button"),type=shape(t);e.className="tile"+(t.locked?" locked":"");e.dataset.i=i;e.style.setProperty("--sprite-rot",spriteRot(t));e.setAttribute("aria-label","Rotate pipe module "+(i+1));e.innerHTML='<img class="pipeSprite" src="assets/karsiori/tiles/'+type+'.png" alt=""><svg class="waterOverlay" viewBox="0 0 100 100" aria-hidden="true"></svg>';e.onclick=()=>turn(i,e);board.appendChild(e)});requestAnimationFrame(renderPorts);const info=flow();updateFlowUi(info)}
function floodInfo(){const dist=new Map(),parent=new Map(),list=[],start=sourcePort.cell;if(!con(tiles[start]).includes(sourcePort.side))return{dist,parent,success:false};dist.set(start,0);parent.set(start,{prev:null,from:sourcePort.side});list.push(start);while(list.length){const i=list.shift(),r=Math.floor(i/size),c=i%size;for(const d of con(tiles[i])){const x=D.indexOf(d),nr=r+DR[x],nc=c+DC[x];if(nr<0||nr>=size||nc<0||nc>=size)continue;const ni=nr*size+nc;if(!con(tiles[ni]).includes(OP[d]))continue;if(!dist.has(ni)){dist.set(ni,dist.get(i)+1);parent.set(ni,{prev:i,from:OP[d]});list.push(ni)}}}return{dist,parent,success:dist.has(targetPort.cell)&&con(tiles[targetPort.cell]).includes(targetPort.side)}}
function connectedExit(i,d,info){if(i===targetPort.cell&&d===targetPort.side)return info.success;const r=Math.floor(i/size),c=i%size,x=D.indexOf(d),nr=r+DR[x],nc=c+DC[x];if(nr<0||nr>=size||nc<0||nc>=size)return false;const ni=nr*size+nc;return info.dist.has(ni)&&con(tiles[ni]).includes(OP[d])}
function waterStroke(svg,d,delay){for(const cls of ["waterRoute","waterShine"]){const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",d);p.setAttribute("pathLength","100");p.setAttribute("class",cls);p.style.animationDelay=(delay+(cls==="waterShine"?55:0))+"ms";svg.appendChild(p)}}
function flow(){const info=floodInfo();q("#sourcePort").classList.toggle("live",info.dist.has(sourcePort.cell));q("#targetPort").classList.remove("reached");qa(".tile").forEach((e,i)=>{const overlay=e.querySelector(".waterOverlay");overlay.innerHTML="";e.classList.toggle("wet",info.dist.has(i));if(!info.dist.has(i))return;const entry=info.parent.get(i).from,exits=con(tiles[i]).filter(d=>d!==entry&&connectedExit(i,d,info)),delay=info.dist.get(i)*WATER_STEP_MS;if(exits.length)exits.forEach(d=>waterStroke(overlay,routeD(entry,d),delay));else waterStroke(overlay,routeD(entry,null),delay)});if(info.success){const endDelay=info.dist.get(targetPort.cell)*WATER_STEP_MS+WATER_SEGMENT_MS;setTimeout(()=>{if(floodInfo().success)q("#targetPort").classList.add("reached")},endDelay)}return info}
function updateFlowUi(info=floodInfo()){let pct=Math.max(8,Math.min(100,Math.round(info.dist.size/(size*1.35)*100)));const fill=q("#pressureFill"),txt=q("#pressureText");if(timerMax){pct=Math.max(0,Math.round(timer/timerMax*100));txt.textContent=timer<=15?"LOW":timer<=Math.round(timerMax*.45)?"FALLING":"STABLE";fill.classList.toggle("low",timer<=15)}else{txt.textContent=info.success?"OPEN":info.dist.size?"BUILDING":"READY";fill.classList.remove("low")}fill.style.width=pct+"%"}
function queueFinish(info){clearTimeout(flowWinTimer);if(!info.success)return;flowWinTimer=setTimeout(()=>{if(!won&&floodInfo().success)finish()},info.dist.get(targetPort.cell)*WATER_STEP_MS+WATER_SEGMENT_MS+100)}
function turn(i,e){if(won||tiles[i].locked)return;clearTimeout(flowWinTimer);tiles[i].rot=(tiles[i].rot+1)%4;turns++;q("#turns").textContent=turns;e.style.setProperty("--sprite-rot",spriteRot(tiles[i]));e.classList.add("turning");setTimeout(()=>e.classList.remove("turning"),140);if(!firstTurnShown){q("#firstHint").classList.add("hide");firstTurnShown=true}beep(340,.035);haptic();const info=flow();updateFlowUi(info);queueFinish(info)}
function start(p,n,opt={}){clearInterval(timerId);clearTimeout(flowWinTimer);won=false;firstTurnShown=false;q("#firstHint").classList.remove("hide");daily=!!opt.daily;pack=p;level=n;turns=0;q("#turns").textContent=0;generate(daily?opt.seed:hash(p.id+"|"+n+"|pipeworks"),p);q("#gamePack").textContent=(daily?"DAILY CHALLENGE":p.name).toUpperCase();q("#gameLevel").textContent=daily?today():"LEVEL "+n;timerMax=0;timer=0;const timed=p.mode==="rush"||daily;q("#timerBox").hidden=!timed;q("#coinHud").style.display=timed?"none":"grid";if(timed){timer=daily?95:Math.max(45,85-Math.floor(n/3));timerMax=timer;q("#timer").textContent=timer}draw();syncCoins();view("game");requestAnimationFrame(renderPorts);if(timed)timerId=setInterval(()=>{timer--;q("#timer").textContent=timer;q("#timerBox").classList.toggle("danger",timer<=15);updateFlowUi();if(timer<=0){clearInterval(timerId);toast("PRESSURE LOST · FINISH FOR 1 STAR")}},1000)}
function spend(n){if(s.coins<n){toast("NEED "+n+" COINS");return false}s.coins-=n;save();return true}
function fix(count,cost){if(won||!spend(cost))return;clearTimeout(flowWinTimer);const wrong=tiles.map((t,i)=>({t,i})).filter(x=>x.t.on&&!x.t.locked&&x.t.rot!==0);if(!wrong.length){s.coins+=cost;save();toast("MAIN ROUTE ALIGNED · CHECK JOINS");return}wrong.slice(0,count).forEach(x=>{x.t.rot=0;const e=q('.tile[data-i="'+x.i+'"]');e.style.setProperty("--sprite-rot",spriteRot(x.t));e.classList.add("hint");setTimeout(()=>e.classList.remove("hint"),1300)});beep(760,.08);haptic(16);const info=flow();updateFlowUi(info);queueFinish(info)}
function finish(){if(won)return;won=true;clearInterval(timerId);beep(580,.08);setTimeout(()=>beep(780,.1),90);haptic(35);let st=3,ideal=size*size*.9;if(turns>ideal)st--;if(turns>ideal*1.55)st--;if(pack.mode==="rush"&&timer<=0)st=Math.min(st,1);if(daily)st=3;st=Math.max(1,st);const coins=daily?75:15+st*5,xp=daily?35:10+level+st*3;let awardCoins=coins,awardXp=xp;if(daily){const k="daily:"+today();if(!s.completed[k]){s.completed[k]={stars:3};s.coins+=coins;s.xp+=xp}else{awardCoins=0;awardXp=0}}else{const k=key(pack.id,level),old=(s.completed[k]||{}).stars||0;if(st>old){s.stars+=st-old;s.completed[k]={stars:st,turns};s.coins+=coins;s.xp+=xp}else{awardCoins=5;awardXp=3;s.coins+=5;s.xp+=3}s.lastPack=pack.id;s.lastLevel=Math.min(pack.count,level+1)}save();q("#winStars").innerHTML=[1,2,3].map(n=>'<img class="'+(n<=st?"on":"off")+'" src="../assets/gamebox/kenney/ui/UI Pack - Adventure/minimap_icon_star_yellow.png" alt="">').join("");q("#wonCoins").textContent=awardCoins;q("#wonXp").textContent=awardXp;q("#next").textContent=daily?"BACK HOME":level>=pack.count?"PACK COMPLETE":"NEXT LEVEL";q("#win").classList.add("show")}
function closeOverlay(id){q(id).classList.remove("show")}
function leaveGame(){clearInterval(timerId);clearTimeout(flowWinTimer);closeOverlay("#menuOverlay");if(daily){home();view("home")}else{levels();view("pack")}}
q("#continue").onclick=()=>{const p=packs.find(x=>x.id===s.lastPack)||packs[0];start(p,Math.min(s.lastLevel,p.count))};
q("#daily").onclick=()=>start(packs[3],1,{daily:true,seed:hash(today()+"|pipeworks-daily")});
q("#reward").onclick=()=>{const d=today();if(s.lastReward===d)return toast("REWARD ALREADY CLAIMED");s.lastReward=d;s.coins+=50;save();home();beep(820,.1);toast("+50 COINS")};
q("#homeSound").onclick=()=>{s.sound=!s.sound;save();soundIcon()};q("#menuSound").onclick=()=>{s.sound=!s.sound;save();soundIcon()};
qa("[data-home]").forEach(b=>b.onclick=()=>{home();view("home")});q("#gameBack").onclick=leaveGame;
q("#hint").onclick=()=>fix(1,25);q("#fix3").onclick=()=>fix(3,50);
q("#gameMenu").onclick=()=>q("#menuOverlay").classList.add("show");q("#closeMenu").onclick=()=>closeOverlay("#menuOverlay");q("#menuLevelSelect").onclick=leaveGame;q("#restartLevel").onclick=()=>{closeOverlay("#menuOverlay");start(pack,level,daily?{daily:true,seed:hash(today()+"|pipeworks-daily")}:{})};
q("#next").onclick=()=>{closeOverlay("#win");if(daily){home();view("home")}else if(level>=pack.count)openPack(pack);else start(pack,level+1)};q("#levelSelect").onclick=()=>{closeOverlay("#win");leaveGame()};
window.addEventListener("resize",renderPorts);home();
})();