(() => {
  'use strict';
  const SAVE_KEY='gamebox-gridline-v1';
  const POINTS=[25,18,15,12,10,8,6,4,2,1,0,0];
  const BOT_NAMES=['Apex North','Redline Works','Vector GP','Copper Fox','Nightshift','Kestrel','Orion Motorsport','Blackbird','Summit Racing','Halo Autosport','Cinder Team','Blue Arrow','Forge Racing','Velocity Union'];
  const TRACKS=[
    {id:'harbour',name:'Harbour Sprint',discipline:'Open Wheel',laps:8,weather:'Dry',bias:'balanced',reward:420,difficulty:58},
    {id:'alpine',name:'Alpine Ring',discipline:'Open Wheel',laps:10,weather:'Cool',bias:'grip',reward:520,difficulty:62},
    {id:'desert',name:'Desert Oval',discipline:'Stock Car',laps:12,weather:'Hot',bias:'speed',reward:610,difficulty:66},
    {id:'forest',name:'Forest Stage',discipline:'Rally',laps:7,weather:'Damp',bias:'control',reward:680,difficulty:69}
  ];
  const DEFAULT_STATE={team:{name:'Gridline Racing',credits:2500,fans:0,division:'Rookie'},selectedDriver:'d1',selectedCar:'c1',drivers:[{id:'d1',name:'Alex Vale',level:1,xp:0,pace:68,racecraft:65,consistency:64,focus:67},{id:'d2',name:'Maya Hart',level:1,xp:0,pace:64,racecraft:69,consistency:70,focus:62}],cars:[{id:'c1',name:'GX-01',discipline:'Open Wheel',owned:true,level:1,speed:66,accel:64,grip:65,reliability:67},{id:'c2',name:'Thunder 8',discipline:'Stock Car',owned:false,cost:3200,level:1,speed:70,accel:60,grip:58,reliability:72},{id:'c3',name:'Trailhawk R',discipline:'Rally',owned:false,cost:4200,level:1,speed:61,accel:66,grip:73,reliability:69}],workshop:{engine:1,aero:1,tyres:1,pit:1},championship:{round:1,points:0,season:1,botPoints:{}},history:[]};
  let state=loadState(),raceTimer=null,hostPending=null,hostPeers=[],joinPeer=null,joinChannel=null;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n)),money=n=>Math.round(n).toLocaleString('en-GB'),average=a=>a.reduce((x,y)=>x+y,0)/a.length,uid=()=>Math.random().toString(36).slice(2,10),clone=o=>JSON.parse(JSON.stringify(o));
  function mergeState(base,saved){return {...base,...saved,team:{...base.team,...(saved.team||{})},workshop:{...base.workshop,...(saved.workshop||{})},championship:{...base.championship,...(saved.championship||{}),botPoints:{...base.championship.botPoints,...((saved.championship||{}).botPoints||{})}},drivers:Array.isArray(saved.drivers)?saved.drivers:base.drivers,cars:Array.isArray(saved.cars)?saved.cars:base.cars,history:Array.isArray(saved.history)?saved.history:[]};}
  function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);return raw?mergeState(clone(DEFAULT_STATE),JSON.parse(raw)):clone(DEFAULT_STATE);}catch(e){return clone(DEFAULT_STATE);}}
  function saveState(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));renderAll();}
  function driverRating(d){return Math.round(average([d.pace,d.racecraft,d.consistency,d.focus])+(d.level-1)*1.5);}
  function carRating(c){return Math.round(average([c.speed,c.accel,c.grip,c.reliability])+(c.level-1)*1.5);}
  function workshopBonus(){return (state.workshop.engine+state.workshop.aero+state.workshop.tyres+state.workshop.pit-4)*.7;}
  function teamRating(driverId=state.selectedDriver,carId=state.selectedCar){const d=state.drivers.find(x=>x.id===driverId)||state.drivers[0],c=state.cars.find(x=>x.id===carId)||state.cars.find(x=>x.owned);return Math.round(driverRating(d)*.55+carRating(c)*.45+workshopBonus());}
  function openView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.open===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='race')renderRaceSetup();if(name==='multiplayer')renderMultiplayerPlayers();}
  function renderTop(){const next=TRACKS[(state.championship.round-1)%TRACKS.length];$('#credits').textContent=money(state.team.credits);$('#fans').textContent=money(state.team.fans);$('#division').textContent=state.team.division;$('#teamName').textContent=state.team.name;$('#driverSummary').textContent=`${state.drivers.length} signed · ${teamRating()} rating`;$('#garageSummary').textContent=`${state.cars.filter(c=>c.owned).length} owned`;$('#champSummary').textContent=`${state.championship.points} pts`;$('#nextRaceName').textContent=next.name;$('#nextRaceTag').textContent=next.discipline;$('#nextRaceLaps').textContent=`${next.laps} laps`;$('#nextRaceWeather').textContent=`${next.weather} · ${capitalize(next.bias)}`;}
  function stat(label,value){return `<div class="stat"><span><b>${label}</b><b>${Math.round(value)}</b></span><div class="statBar"><i style="width:${clamp(value,5,100)}%"></i></div></div>`;}
  function renderDrivers(){$('#driverList').innerHTML=state.drivers.map(d=>{const selected=d.id===state.selectedDriver,cost=350+d.level*250;return `<article class="driverCard ${selected?'selectedCard':''}"><div class="cardTop"><div class="avatar">${initials(d.name)}</div><div class="cardIdentity"><h3>${escapeHtml(d.name)}</h3><small>Level ${d.level} · ${d.xp} XP</small></div><div class="ratingBubble">${driverRating(d)}</div></div><div class="statGrid">${stat('Pace',d.pace)}${stat('Racecraft',d.racecraft)}${stat('Consistency',d.consistency)}${stat('Focus',d.focus)}</div><div class="cardActions"><button class="secondaryButton" data-select-driver="${d.id}">${selected?'Selected':'Select'}</button><button class="primaryButton" data-upgrade-driver="${d.id}">Train · ${money(cost)}</button></div></article>`;}).join('');}
  function renderCars(){$('#carList').innerHTML=state.cars.map(c=>{const selected=c.id===state.selectedCar,upgradeCost=500+c.level*320;const action=c.owned?`<button class="secondaryButton" data-select-car="${c.id}">${selected?'Selected':'Select'}</button><button class="primaryButton" data-upgrade-car="${c.id}">Upgrade · ${money(upgradeCost)}</button>`:`<button class="primaryButton full" data-buy-car="${c.id}">Buy · ${money(c.cost)}</button>`;return `<article class="carCard ${selected?'selectedCard':''}"><div class="cardTop"><div class="avatar">${c.discipline==='Rally'?'R':c.discipline==='Stock Car'?'S':'OW'}</div><div class="cardIdentity"><h3>${escapeHtml(c.name)}</h3><small>${c.discipline} · Level ${c.level}</small></div><div class="ratingBubble">${carRating(c)}</div></div><div class="statGrid">${stat('Speed',c.speed)}${stat('Acceleration',c.accel)}${stat('Grip',c.grip)}${stat('Reliability',c.reliability)}</div><div class="cardActions">${action}</div></article>`;}).join('');const names={engine:'Engine Lab',aero:'Aero Bay',tyres:'Tyre Lab',pit:'Pit Crew'};$('#workshopUpgrades').innerHTML=Object.entries(state.workshop).map(([key,level])=>{const cost=700+level*500;return `<div class="upgradeRow"><div><strong>${names[key]}</strong><p>Level ${level} · boosts race performance</p></div><button class="primaryButton" data-upgrade-workshop="${key}">${money(cost)}</button></div>`;}).join('');}
  function ensureTrackOptions(){const html=TRACKS.map(t=>`<option value="${t.id}">${t.name} · ${t.discipline}</option>`).join('');if($('#raceTrack')&&!$('#raceTrack').options.length)$('#raceTrack').innerHTML=html;if($('#multiTrack')&&!$('#multiTrack').options.length)$('#multiTrack').innerHTML=html;}
  function renderRaceSetup(){ensureTrackOptions();const track=TRACKS.find(t=>t.id===$('#raceTrack').value)||TRACKS[0];$('#raceDriver').innerHTML=state.drivers.map(d=>`<option value="${d.id}" ${d.id===state.selectedDriver?'selected':''}>${d.name} · ${driverRating(d)}</option>`).join('');let owned=state.cars.filter(c=>c.owned&&c.discipline===track.discipline);if(!owned.length)owned=state.cars.filter(c=>c.owned);$('#raceCar').innerHTML=owned.map(c=>`<option value="${c.id}" ${c.id===state.selectedCar?'selected':''}>${c.name} · ${carRating(c)}</option>`).join('');if(!owned.some(c=>c.id===$('#raceCar').value)&&owned[0])$('#raceCar').value=owned[0].id;renderRaceSummary();}
  function renderRaceSummary(){const track=TRACKS.find(t=>t.id===$('#raceTrack').value)||TRACKS[0],d=state.drivers.find(x=>x.id===$('#raceDriver').value)||state.drivers[0],c=state.cars.find(x=>x.id===$('#raceCar').value)||state.cars.find(x=>x.owned),match=c.discipline===track.discipline,rating=Math.round(driverRating(d)*.55+carRating(c)*.45+workshopBonus()+(match?3:-8));$('#raceSetupSummary').innerHTML=`<div class="summaryStat"><span>Team rating</span><strong>${rating}</strong></div><div class="summaryStat"><span>Difficulty</span><strong>${track.difficulty}</strong></div><div class="summaryStat"><span>Reward</span><strong>${money(track.reward)}</strong></div>`;}
  function seeded(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
  function buildSoloEntrants(track,driverId,carId,seed){const rng=seeded(seed),d=state.drivers.find(x=>x.id===driverId),c=state.cars.find(x=>x.id===carId),disciplineBonus=c.discipline===track.discipline?3:-8,biasBonus=track.bias==='speed'?(c.speed-65)*.08:track.bias==='grip'?(c.grip-65)*.08:track.bias==='control'?((d.consistency+d.focus)/2-65)*.08:0,playerPower=driverRating(d)*.55+carRating(c)*.45+workshopBonus()+disciplineBonus+biasBonus,entrants=[{id:'you',name:state.team.name,power:playerPower,kind:'player',local:true}];shuffle(BOT_NAMES.slice(),rng).slice(0,11).forEach((name,i)=>entrants.push({id:`b${i}`,name,power:track.difficulty-8+rng()*19,kind:'bot'}));return entrants;}
  function simulateRace(track,entrants,seed){const rng=seeded(seed),progress=entrants.map(e=>({...e,p:0,speed:0,finishTick:null})),frames=[];let tick=0;while(progress.some(e=>e.p<100)&&tick<100){tick++;progress.forEach(e=>{if(e.p>=100)return;const variance=(rng()-.5)*2.9,incident=rng()<.018?-(2+rng()*5):0,surge=rng()<.05?rng()*3.5:0;e.speed=Math.max(.5,1.55+(e.power-55)*.027+variance*.16+incident*.12+surge*.12);e.p=Math.min(100,e.p+e.speed);if(e.p>=100&&e.finishTick===null)e.finishTick=tick+(1-rng())*.25;});frames.push(progress.map(e=>({id:e.id,p:e.p})));}const results=progress.slice().sort((a,b)=>(a.finishTick??999)-(b.finishTick??999));results.forEach((e,i)=>e.position=i+1);return{frames,results};}
  function startSoloRace(){clearInterval(raceTimer);const track=TRACKS.find(t=>t.id===$('#raceTrack').value)||TRACKS[0],driverId=$('#raceDriver').value,carId=$('#raceCar').value;state.selectedDriver=driverId;state.selectedCar=carId;localStorage.setItem(SAVE_KEY,JSON.stringify(state));const seed=Date.now()>>>0,entrants=buildSoloEntrants(track,driverId,carId,seed),sim=simulateRace(track,entrants,seed);runRaceAnimation(track,entrants,sim,{mode:'solo'});}
  function runRaceAnimation(track,entrants,sim,opts={}){openView('race');$('#raceArena').classList.remove('hidden');$('#raceResult').classList.add('hidden');$('#liveRaceTitle').textContent=opts.mode==='multi'?`${track.name} · Local Race`:track.name;$('#raceLanes').innerHTML=entrants.map((e,i)=>`<div class="raceLane ${e.kind==='player'?'player':e.kind==='friend'?'friend':''}" data-racer="${e.id}"><span class="position">${i+1}</span><span class="name">${escapeHtml(e.name)}</span><div class="laneTrack"><i class="racerDot"></i></div></div>`).join('');let frame=0,total=sim.frames.length;const update=()=>{const f=sim.frames[frame];if(!f)return;const sorted=f.slice().sort((a,b)=>b.p-a.p),positions=Object.fromEntries(sorted.map((r,i)=>[r.id,i+1]));f.forEach(r=>{const row=$(`[data-racer="${r.id}"]`);if(row){row.querySelector('.racerDot').style.left=`calc(${Math.min(96,r.p*.96)}% - 10px)`;row.querySelector('.position').textContent=positions[r.id];}});$('#raceLap').textContent=`Lap ${Math.min(track.laps,Math.max(1,Math.ceil((frame/Math.max(1,total))*track.laps)))}/${track.laps}`;frame++;};update();raceTimer=setInterval(()=>{if(frame>=total){clearInterval(raceTimer);raceTimer=null;finishRace(track,sim.results,opts);}else update();},280);}
  function finishRace(track,results,opts){const box=$('#raceResult');box.classList.remove('hidden');const playerResult=results.find(r=>r.kind==='player'&&(r.id==='you'||r.local));let rewardText='';if(opts.mode==='solo'&&playerResult){const reward=Math.max(90,Math.round(track.reward*(1.15-(playerResult.position-1)*.055))),fans=Math.max(4,Math.round((13-playerResult.position)*7));state.team.credits+=reward;state.team.fans+=fans;state.championship.points+=POINTS[playerResult.position-1]||0;state.championship.round=state.championship.round>=6?1:state.championship.round+1;updateBotChampionship();state.history.unshift({date:Date.now(),track:track.name,position:playerResult.position,reward});state.history=state.history.slice(0,30);const d=state.drivers.find(x=>x.id===state.selectedDriver);if(d)d.xp+=20+Math.max(0,12-playerResult.position)*2;updateDivision();localStorage.setItem(SAVE_KEY,JSON.stringify(state));rewardText=`+${money(reward)} credits · +${fans} fans · +${POINTS[playerResult.position-1]||0} championship points`;}else if(opts.mode==='multi')rewardText='Local multiplayer race complete — bots filled all unused grid slots.';box.innerHTML=`<h3>Race result</h3><div class="resultList">${results.map((r,i)=>`<div class="resultRow"><b>${i+1}</b><span>${escapeHtml(r.name)}</span><b>${Math.round(r.power)}</b></div>`).join('')}</div>${rewardText?`<div class="rewardBox">${rewardText}</div>`:''}`;renderAll();}
  function updateBotChampionship(){BOT_NAMES.slice(0,9).forEach(name=>{state.championship.botPoints[name]=(state.championship.botPoints[name]||0)+(POINTS[Math.min(11,Math.floor(Math.random()*9))]||0);});}
  function updateDivision(){const f=state.team.fans;state.team.division=f>=1800?'Elite':f>=900?'Pro':f>=350?'Club':'Rookie';}
  function renderStandings(){$('#seasonTitle').textContent=`Season ${state.championship.season} · ${state.team.division} Cup`;$('#seasonRound').textContent=`Round ${state.championship.round}/6`;const all=[{name:state.team.name,points:state.championship.points,you:true},...Object.entries(state.championship.botPoints).map(([name,points])=>({name,points,you:false}))].sort((a,b)=>b.points-a.points);if(all.length===1)BOT_NAMES.slice(0,7).forEach((name,i)=>all.push({name,points:Math.max(0,18-i*2),you:false}));$('#standings').innerHTML=all.slice(0,10).map((t,i)=>`<div class="standingRow ${t.you?'you':''}"><b>${i+1}</b><span>${escapeHtml(t.name)}${t.you?' · You':''}</span><b>${t.points}</b></div>`).join('');}
  function trainDriver(id){const d=state.drivers.find(x=>x.id===id);if(!d)return;const cost=350+d.level*250;if(state.team.credits<cost)return toast('Not enough credits');state.team.credits-=cost;d.level++;d.pace=clamp(d.pace+1+(Math.random()<.4?1:0),1,99);d.racecraft=clamp(d.racecraft+1,1,99);d.consistency=clamp(d.consistency+1,1,99);d.focus=clamp(d.focus+1,1,99);saveState();}
  function upgradeCar(id){const c=state.cars.find(x=>x.id===id);if(!c||!c.owned)return;const cost=500+c.level*320;if(state.team.credits<cost)return toast('Not enough credits');state.team.credits-=cost;c.level++;c.speed=clamp(c.speed+1,1,99);c.accel=clamp(c.accel+1,1,99);c.grip=clamp(c.grip+1,1,99);c.reliability=clamp(c.reliability+1,1,99);saveState();}
  function buyCar(id){const c=state.cars.find(x=>x.id===id);if(!c||c.owned)return;if(state.team.credits<c.cost)return toast('Not enough credits');state.team.credits-=c.cost;c.owned=true;state.selectedCar=c.id;saveState();}
  function upgradeWorkshop(key){const level=state.workshop[key];if(!level)return;const cost=700+level*500;if(state.team.credits<cost)return toast('Not enough credits');state.team.credits-=cost;state.workshop[key]++;saveState();}
  function renderMultiplayerPlayers(){const self={name:state.team.name,rating:teamRating()},connected=hostPeers.filter(p=>p.channel&&p.channel.readyState==='open'&&p.player).map(p=>p.player);if($('#hostPlayers'))$('#hostPlayers').innerHTML=[self,...connected].map((p,i)=>`<div class="playerChip"><strong>${escapeHtml(p.name)}${i===0?' · Host':''}</strong><small>Rating ${Math.round(p.rating||60)}</small></div>`).join('');if($('#startMultiRace'))$('#startMultiRace').disabled=connected.length===0;}
  function makePeer(){return new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});}
  function waitIce(pc){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{let doneCalled=false;const done=()=>{if(doneCalled)return;doneCalled=true;pc.removeEventListener('icegatheringstatechange',check);resolve();},check=()=>{if(pc.iceGatheringState==='complete')done();};pc.addEventListener('icegatheringstatechange',check);setTimeout(done,4500);});}
  function encodeSignal(desc){return btoa(unescape(encodeURIComponent(JSON.stringify(desc))));}
  function decodeSignal(code){return JSON.parse(decodeURIComponent(escape(atob(code.trim()))));}
  async function createHostInvite(){try{$('#hostConnectionState').textContent='Creating';const pc=makePeer(),channel=pc.createDataChannel('gridline'),peer={id:uid(),pc,channel,player:null};wireHostChannel(peer);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);hostPending=peer;$('#hostOffer').value=encodeSignal(pc.localDescription);$('#hostConnectionState').textContent='Invite ready';}catch(err){console.error(err);toast('Could not create invite');$('#hostConnectionState').textContent='Error';}}
  function wireHostChannel(peer){peer.channel.onopen=()=>{$('#hostConnectionState').textContent='Connected';broadcastLobby();};peer.channel.onmessage=evt=>{try{const msg=JSON.parse(evt.data);if(msg.type==='hello'){peer.player={id:peer.id,name:String(msg.player?.name||'Friend').slice(0,24),rating:Number(msg.player?.rating)||60};renderMultiplayerPlayers();broadcastLobby();}}catch(err){console.warn(err);}};peer.channel.onclose=()=>{renderMultiplayerPlayers();broadcastLobby();};}
  async function acceptHostAnswer(){if(!hostPending)return toast('Create an invite first');try{await hostPending.pc.setRemoteDescription(decodeSignal($('#hostAnswer').value));hostPeers.push(hostPending);hostPending=null;$('#hostOffer').value='';$('#hostAnswer').value='';$('#hostConnectionState').textContent='Connecting';}catch(err){console.error(err);toast('That answer code is not valid');}}
  async function makeJoinAnswer(){try{$('#joinConnectionState').textContent='Connecting';joinPeer=makePeer();joinPeer.ondatachannel=evt=>{joinChannel=evt.channel;joinChannel.onopen=()=>{$('#joinConnectionState').textContent='Connected';joinChannel.send(JSON.stringify({type:'hello',player:{name:state.team.name,rating:teamRating()}}));};joinChannel.onmessage=evt=>{try{const msg=JSON.parse(evt.data);if(msg.type==='lobby')renderJoinLobby(msg.players||[]);if(msg.type==='race-start')runIncomingMultiRace(msg.payload);}catch(err){console.warn(err);}};joinChannel.onclose=()=>$('#joinConnectionState').textContent='Disconnected';};await joinPeer.setRemoteDescription(decodeSignal($('#joinOffer').value));const answer=await joinPeer.createAnswer();await joinPeer.setLocalDescription(answer);await waitIce(joinPeer);$('#joinAnswer').value=encodeSignal(joinPeer.localDescription);$('#joinConnectionState').textContent='Answer ready';}catch(err){console.error(err);toast('That invite code is not valid');$('#joinConnectionState').textContent='Error';}}
  function renderJoinLobby(players){$('#joinLobby').innerHTML=players.map(p=>`<div class="playerChip"><strong>${escapeHtml(p.name)}</strong><small>Rating ${Math.round(p.rating||60)}</small></div>`).join('');}
  function broadcastLobby(){const players=[{name:state.team.name,rating:teamRating()},...hostPeers.filter(p=>p.channel?.readyState==='open'&&p.player).map(p=>p.player)],msg=JSON.stringify({type:'lobby',players});hostPeers.forEach(p=>{if(p.channel?.readyState==='open')p.channel.send(msg);});renderMultiplayerPlayers();}
  function startHostMultiRace(){const track=TRACKS.find(t=>t.id===$('#multiTrack').value)||TRACKS[0],seed=Date.now()>>>0,connected=hostPeers.filter(p=>p.channel?.readyState==='open'&&p.player),entrants=[{id:'host',name:state.team.name,power:teamRating(),kind:'player',local:true}];connected.forEach((p,i)=>entrants.push({id:`friend-${i}`,name:p.player.name,power:p.player.rating,kind:'friend'}));const rng=seeded(seed);shuffle(BOT_NAMES.slice(),rng).slice(0,Math.max(0,12-entrants.length)).forEach((name,i)=>entrants.push({id:`bot-${i}`,name,power:track.difficulty-7+rng()*17,kind:'bot'}));const payload={trackId:track.id,seed,entrants};connected.forEach(p=>p.channel.send(JSON.stringify({type:'race-start',payload})));runRaceAnimation(track,entrants,simulateRace(track,entrants,seed),{mode:'multi'});}
  function runIncomingMultiRace(payload){const track=TRACKS.find(t=>t.id===payload.trackId)||TRACKS[0],entrants=(payload.entrants||[]).map(e=>({...e,local:e.name===state.team.name,kind:e.name===state.team.name?'player':e.kind==='player'?'friend':e.kind}));runRaceAnimation(track,entrants,simulateRace(track,entrants,payload.seed>>>0),{mode:'multi'});}
  function shuffle(arr,rng=Math.random){for(let i=arr.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
  function initials(name){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();}
  function capitalize(s){return s.charAt(0).toUpperCase()+s.slice(1);}
  function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function toast(text){let el=$('#gridToast');if(!el){el=document.createElement('div');el.id='gridToast';Object.assign(el.style,{position:'fixed',left:'50%',bottom:'92px',transform:'translateX(-50%)',background:'#082f68',color:'#fff',padding:'10px 15px',borderRadius:'999px',zIndex:'100',fontWeight:'700',boxShadow:'0 10px 30px rgba(8,47,104,.25)'});document.body.appendChild(el);}el.textContent=text;el.style.display='block';clearTimeout(el._t);el._t=setTimeout(()=>el.style.display='none',2200);}
  function renderAll(){renderTop();renderDrivers();renderCars();ensureTrackOptions();renderRaceSetup();renderStandings();renderMultiplayerPlayers();}
  document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){openView(open.dataset.open);return;}const dsel=e.target.closest('[data-select-driver]');if(dsel){state.selectedDriver=dsel.dataset.selectDriver;saveState();return;}const dup=e.target.closest('[data-upgrade-driver]');if(dup){trainDriver(dup.dataset.upgradeDriver);return;}const csel=e.target.closest('[data-select-car]');if(csel){state.selectedCar=csel.dataset.selectCar;saveState();return;}const cup=e.target.closest('[data-upgrade-car]');if(cup){upgradeCar(cup.dataset.upgradeCar);return;}const cbuy=e.target.closest('[data-buy-car]');if(cbuy){buyCar(cbuy.dataset.buyCar);return;}const wup=e.target.closest('[data-upgrade-workshop]');if(wup){upgradeWorkshop(wup.dataset.upgradeWorkshop);return;}});
  $('#raceTrack').addEventListener('change',renderRaceSetup);$('#raceDriver').addEventListener('change',renderRaceSummary);$('#raceCar').addEventListener('change',renderRaceSummary);$('#startSoloRace').addEventListener('click',startSoloRace);$('#hostMode').addEventListener('click',()=>{$('#hostPanel').classList.remove('hidden');$('#joinPanel').classList.add('hidden');renderMultiplayerPlayers();});$('#joinMode').addEventListener('click',()=>{$('#joinPanel').classList.remove('hidden');$('#hostPanel').classList.add('hidden');});$('#createInvite').addEventListener('click',createHostInvite);$('#acceptAnswer').addEventListener('click',acceptHostAnswer);$('#makeAnswer').addEventListener('click',makeJoinAnswer);$('#startMultiRace').addEventListener('click',startHostMultiRace);$('#resetSave').addEventListener('click',()=>{if(confirm('Reset Gridline Racing progress on this device?')){localStorage.removeItem(SAVE_KEY);state=clone(DEFAULT_STATE);renderAll();openView('home');}});
  ensureTrackOptions();renderAll();
})();