export const RIG_GROUPS = {
  base: ['BaseCharacter'],
  blueFemale: ['BlueSoldier_Female'],
  standard: ['BlueSoldier_Male','Casual2_Male','Casual3_Female','Casual_Female','Cow','Cowboy_Female','Cowboy_Hair','Cowboy_Male','Doctor_Female_Old','Doctor_Female_Young','Doctor_Male_Old','Doctor_Male_Young','Elf','Ninja_Female','Ninja_Male','Ninja_Male_Hair','Ninja_Sand_Female','OldClassy_Female','OldClassy_Male','Pirate_Female','Pirate_Male','Pug','Soldier_Female','Suit_Male','VikingHelmet','Viking_Female','Witch','Wizard','Worker_Female','Worker_Male'],
  compactFemale: ['Casual2_Female','Goblin_Female'],
  compactMale: ['Casual3_Male','Casual_Bald'],
  casualMale: ['Casual_Male'],
  chefFemale: ['Chef_Female'],
  armour: ['Chef_Hat','Chef_Male','Kimono_Female','Knight_Golden_Female','Knight_Golden_Male','Knight_Male','Zombie_Female','Zombie_Male'],
  goblinMale: ['Goblin_Male'],
  kimonoMale: ['Kimono_Male'],
  soldierMale: ['Ninja_Sand','Soldier_Male'],
  suitFemale: ['Suit_Female'],
  vikingMale: ['Viking_Male']
};

const RIG_BY_ID = Object.fromEntries(
  Object.entries(RIG_GROUPS).flatMap(([rig, ids]) => ids.map(id => [id, rig]))
);

export const CHARACTER_CATALOG = [
  { id: 'BaseCharacter', label: 'Base Character', group: 'Core', variant: 'Neutral' },
  { id: 'BlueSoldier_Female', label: 'Blue Soldier', group: 'Combat', variant: 'Feminine' },
  { id: 'BlueSoldier_Male', label: 'Blue Soldier', group: 'Combat', variant: 'Masculine' },
  { id: 'Casual_Bald', label: 'Casual · Bald', group: 'Everyday', variant: 'Masculine' },
  { id: 'Casual_Female', label: 'Casual', group: 'Everyday', variant: 'Feminine' },
  { id: 'Casual_Male', label: 'Casual', group: 'Everyday', variant: 'Masculine' },
  { id: 'Casual2_Female', label: 'Casual 2', group: 'Everyday', variant: 'Feminine' },
  { id: 'Casual2_Male', label: 'Casual 2', group: 'Everyday', variant: 'Masculine' },
  { id: 'Casual3_Female', label: 'Casual 3', group: 'Everyday', variant: 'Feminine' },
  { id: 'Casual3_Male', label: 'Casual 3', group: 'Everyday', variant: 'Masculine' },
  { id: 'Chef_Female', label: 'Chef', group: 'Roles', variant: 'Feminine' },
  { id: 'Chef_Hat', label: 'Chef · Hat Variant', group: 'Roles', variant: 'Variant' },
  { id: 'Chef_Male', label: 'Chef', group: 'Roles', variant: 'Masculine' },
  { id: 'Cow', label: 'Cow Mascot', group: 'Creatures', variant: 'Creature' },
  { id: 'Cowboy_Female', label: 'Cowboy', group: 'Adventure', variant: 'Feminine' },
  { id: 'Cowboy_Hair', label: 'Cowboy · Hair Variant', group: 'Adventure', variant: 'Variant' },
  { id: 'Cowboy_Male', label: 'Cowboy', group: 'Adventure', variant: 'Masculine' },
  { id: 'Doctor_Female_Old', label: 'Doctor · Senior', group: 'Roles', variant: 'Feminine' },
  { id: 'Doctor_Female_Young', label: 'Doctor · Young', group: 'Roles', variant: 'Feminine' },
  { id: 'Doctor_Male_Old', label: 'Doctor · Senior', group: 'Roles', variant: 'Masculine' },
  { id: 'Doctor_Male_Young', label: 'Doctor · Young', group: 'Roles', variant: 'Masculine' },
  { id: 'Elf', label: 'Christmas Elf', group: 'Fantasy', variant: 'Special' },
  { id: 'Goblin_Female', label: 'Goblin', group: 'Fantasy', variant: 'Feminine' },
  { id: 'Goblin_Male', label: 'Goblin', group: 'Fantasy', variant: 'Masculine' },
  { id: 'Kimono_Female', label: 'Kimono', group: 'Adventure', variant: 'Feminine' },
  { id: 'Kimono_Male', label: 'Kimono', group: 'Adventure', variant: 'Masculine' },
  { id: 'Knight_Golden_Female', label: 'Golden Knight', group: 'Combat', variant: 'Feminine' },
  { id: 'Knight_Golden_Male', label: 'Golden Knight', group: 'Combat', variant: 'Masculine' },
  { id: 'Knight_Male', label: 'Knight', group: 'Combat', variant: 'Masculine' },
  { id: 'Ninja_Female', label: 'Ninja', group: 'Combat', variant: 'Feminine' },
  { id: 'Ninja_Male_Hair', label: 'Ninja · Hair Variant', group: 'Combat', variant: 'Variant' },
  { id: 'Ninja_Male', label: 'Ninja', group: 'Combat', variant: 'Masculine' },
  { id: 'Ninja_Sand_Female', label: 'Sand Ninja', group: 'Combat', variant: 'Feminine' },
  { id: 'Ninja_Sand', label: 'Sand Ninja', group: 'Combat', variant: 'Masculine' },
  { id: 'OldClassy_Female', label: 'Classic · Senior', group: 'Everyday', variant: 'Feminine' },
  { id: 'OldClassy_Male', label: 'Classic · Senior', group: 'Everyday', variant: 'Masculine' },
  { id: 'Pirate_Female', label: 'Pirate', group: 'Adventure', variant: 'Feminine' },
  { id: 'Pirate_Male', label: 'Pirate', group: 'Adventure', variant: 'Masculine' },
  { id: 'Pug', label: 'Pug Mascot', group: 'Creatures', variant: 'Creature' },
  { id: 'Soldier_Female', label: 'Soldier', group: 'Combat', variant: 'Feminine' },
  { id: 'Soldier_Male', label: 'Soldier', group: 'Combat', variant: 'Masculine' },
  { id: 'Suit_Female', label: 'Suit', group: 'Everyday', variant: 'Feminine' },
  { id: 'Suit_Male', label: 'Suit', group: 'Everyday', variant: 'Masculine' },
  { id: 'Viking_Female', label: 'Viking', group: 'Adventure', variant: 'Feminine' },
  { id: 'Viking_Male', label: 'Viking', group: 'Adventure', variant: 'Masculine' },
  { id: 'VikingHelmet', label: 'Viking · Helmet Variant', group: 'Adventure', variant: 'Variant' },
  { id: 'Witch', label: 'Witch', group: 'Fantasy', variant: 'Special' },
  { id: 'Wizard', label: 'Wizard', group: 'Fantasy', variant: 'Special' },
  { id: 'Worker_Female', label: 'Worker', group: 'Roles', variant: 'Feminine' },
  { id: 'Worker_Male', label: 'Worker', group: 'Roles', variant: 'Masculine' },
  { id: 'Zombie_Female', label: 'Zombie', group: 'Fantasy', variant: 'Feminine' },
  { id: 'Zombie_Male', label: 'Zombie', group: 'Fantasy', variant: 'Masculine' }
].map((entry, index) => ({
  ...entry,
  index,
  file: `${entry.id}.gltf`,
  path: `../shared/asset-pool/quaternius/ultimate-animated-character/${entry.id}.gltf`,
  rig: RIG_BY_ID[entry.id] || 'base'
}));

export const CHARACTER_GROUPS = ['All', 'Core', 'Everyday', 'Roles', 'Adventure', 'Fantasy', 'Combat', 'Creatures'];
