(() => {
  const $ = id => document.getElementById(id);
  const CARD_STORAGE='gamebox.cardGames.v2', COIN_STORAGE='gamebox.coinGames.v1';
  const ranks=['A','K','Q','J','10','9','8','7','6','5','4','3','2'];
  const suits=[{s:'♠',name:'Spades',red:false},{s:'♥',name:'Hearts',red:true},{s:'♦',name:'Diamonds',red:true},{s:'♣',name:'Clubs',red:false}];
  const ruleKeys=[...ranks,'JOKER_RED','JOKER_BLACK'];
  const examples={A:'Make a new rule.',K:'Everyone takes part.',Q:'Ask another player a question.',J:'Choose another player.','10':'Pick a category and take turns naming answers.','9':'Pick a word and take turns rhyming.','8':'Choose a mate.','7':'Hands up — last player loses.','6':'Choose a player.','5':'Everyone joins in.','4':'Touch the floor — last player loses.','3':'You take the action.','2':'Choose two people.',JOKER_RED:'Wild card — invent a temporary rule.',JOKER_BLACK:'Reverse the turn order.'};
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=()=>crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
  const getStore=key=>{try{return JSON.parse(localStorage.getItem(key))||[]}catch{return[]}};
  const setStore=(key,val)=>localStorage.setItem(key,JSON.stringify(val));
  const randBool=()=>{try{const a=new Uint32Array(1);crypto.getRandomValues(a);return (a[0]&1)===1}catch{return Math.random()>=.5}};

  const screens={home:$('homeScreen'),cards:$('cardScreen'),coins:$('coinScreen')};
  function showScreen(name){Object.entries(screens).forEach(([k,v])=>v.classList.toggle('hidden',k!==name));window.scrollTo({top:0,behavior:'smooth'})}
  $('openCards').addEventListener('click',()=>showScreen('cards')); $('openCoins').addEventListener('click',()=>showScreen('coins')); document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>showScreen('home')));

  const card={playerCount:2,names:['Player 1','Player 2'],name:'',rules:Object.fromEntries(ruleKeys.map(k=>[k,''])),deck:[],history:[],current:0,last:null,playing:false};
  function cardSync(){card.name=$('cardGameName').value.trim();for(let i=0;i<card.playerCount;i++){const n=document.querySelector(`[data-card-player="${i}"]`);card.names[i]=n?.value.trim()||`Player ${i+1}`}document.querySelectorAll('[data-card-rule]').forEach(i=>card.rules[i.dataset.cardRule]=i.value.trim())}
  function cardCountUI(){const w=$('cardPlayerCount');w.innerHTML='';for(let n=1;n<=4;n++){const b=document.createElement('button');b.type='button';b.textContent=n;b.className=n===card.playerCount?'active':'';b.addEventListener('click',()=>{cardSync();card.playerCount=n;while(card.names.length<n)card.names.push(`Player ${card.names.length+1}`);card.names=card.names.slice(0,n);cardCountUI();cardNamesUI()});w.appendChild(b)}}
  function cardNamesUI(){const w=$('cardPlayerNames');w.innerHTML='';for(let i=0;i<card.playerCount;i++){const input=document.createElement('input');input.className='textInput';input.type='text';input.maxLength=24;input.value=card.names[i]||`Player ${i+1}`;input.dataset.cardPlayer=i;input.placeholder=`Player ${i+1}`;w.appendChild(input)}}
  function cardRulesUI(){const w=$('cardRules');w.innerHTML='';ranks.forEach(rank=>{const r=document.createElement('div');r.className='ruleRow';r.innerHTML=`<div class="rankBox">${rank}</div><input class="ruleInput" data-card-rule="${rank}" maxlength="100" placeholder="Rule for ${rank}s" value="${esc(card.rules[rank])}">`;w.appendChild(r)});[['JOKER_RED','RED<br>JOKER','red'],['JOKER_BLACK','BLACK<br>JOKER','']].forEach(([key,label,cl])=>{const r=document.createElement('div');r.className='ruleRow';r.innerHTML=`<div class="rankBox joker ${cl}">${label}</div><input class="ruleInput" data-card-rule="${key}" maxlength="100" placeholder="Joker rule" value="${esc(card.rules[key])}">`;w.appendChild(r)})}
  function renderCardSaved(){const w=$('cardSaved'),items=getStore(CARD_STORAGE);w.innerHTML='';if(!items.length){w.innerHTML='<div class="sub" style="margin:0">No saved card games yet.</div>';return}items.forEach(item=>{const d=document.createElement('div');d.className='savedItem';d.innerHTML=`<div class="savedInfo"><strong>${esc(item.name)}</strong><span>${item.playerCount} player${item.playerCount===1?'':'s'} · ${Object.values(item.rules||{}).filter(Boolean).length} rules</span></div><div class="savedActions"><button class="tiny load">Load</button><button class="tiny del">Delete</button></div>`;d.querySelector('.load').addEventListener('click',()=>loadCard(item.id));d.querySelector('.del').addEventListener('click',()=>{setStore(CARD_STORAGE,items.filter(x=>x.id!==item.id));renderCardSaved()});w.appendChild(d)})}
  function saveCard(){cardSync();if(!card.name){$('cardStatus').textContent='Give the game a name before saving.';$('cardGameName').focus();return}const items=getStore(CARD_STORAGE),ix=items.findIndex(x=>x.name.toLowerCase()===card.name.toLowerCase());const item={id:ix>=0?items[ix].id:uid(),name:card.name,playerCount:card.playerCount,names:[...card.names],rules:{...card.rules}};if(ix>=0)items[ix]=item;else items.unshift(item);setStore(CARD_STORAGE,items);renderCardSaved();$('cardStatus').textContent=`Saved “${card.name}”.`}
  function loadCard(id){const item=getStore(CARD_STORAGE).find(x=>x.id===id);if(!item)return;card.name=item.name;card.playerCount=item.playerCount;card.names=[...item.names];card.rules={...Object.fromEntries(ruleKeys.map(k=>[k,''])),...(item.rules||{})};$('cardGameName').value=card.name;cardCountUI();cardNamesUI();cardRulesUI();$('cardStatus').textContent=`Loaded “${item.name}”.`;window.scrollTo({top:0,behavior:'smooth'})}
  function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  function buildDeck(){const d=[];for(const rank of ranks)for(const suit of suits)d.push({rank,suit:suit.s,suitName:suit.name,red:suit.red,ruleKey:rank,label:`${rank}${suit.s}`});d.push({rank:'JOKER',red:true,joker:true,ruleKey:'JOKER_RED',label:'Red Joker'});d.push({rank:'JOKER',red:false,joker:true,ruleKey:'JOKER_BLACK',label:'Black Joker'});return shuffle(d)}
  function cardStart(){cardSync();card.deck=buildDeck();card.history=[];card.current=0;card.last=null;card.playing=true;renderCardPlay();setCardMode('play')}
  function cardRestart(){card.deck=buildDeck();card.history=[];card.current=0;card.last=null;card.playing=true;renderCardPlay();$('cardRestartDialog').close()}
  function cardDraw(){if(!card.playing||!card.deck.length)return;const name=card.names[card.current]||`Player ${card.current+1}`,idx=card.current,c=card.deck.pop();card.last={...c,playerName:name,playerIndex:idx};card.history.unshift(card.last);card.current=(card.current+1)%card.playerCount;renderCardPlay()}
  function renderCardPlay(){const active=card.names[card.current]||`Player ${card.current+1}`;$('cardTurnBubble').textContent=card.current+1;$('cardTurnText').textContent=card.deck.length?`${active}'s turn`:'Deck finished';$('cardTitle').textContent=card.name||'Unsaved Game';$('cardsLeft').textContent=card.deck.length;$('cardsDrawn').textContent=card.history.length;$('deckTop').textContent=card.deck.length?'DRAW':'EMPTY';$('cardHint').textContent=card.deck.length?`Tap to draw for ${active}.`:'All 54 cards have been drawn.';[$('cardDraw'),$('cardDrawMobile')].forEach(b=>{b.disabled=!card.deck.length;b.textContent=card.deck.length?'Draw Card':'Deck Finished'});const ps=$('cardPlayers');ps.innerHTML='';card.names.slice(0,card.playerCount).forEach((name,i)=>{const d=document.createElement('div');d.className='player'+(i===card.current&&card.deck.length?' active':'');d.innerHTML=`<div class="playerDot">${i+1}</div><div>${esc(name||`Player ${i+1}`)}</div>`;ps.appendChild(d)});const slot=$('drawnSlot');if(card.last){slot.className='drawnCard'+(card.last.red?' red':'');slot.innerHTML=card.last.joker?`<div class="jokerFace"><div><span>★</span>${card.last.red?'RED':'BLACK'}<br>JOKER</div></div>`:`<div class="corner tl">${card.last.rank}<span>${card.last.suit}</span></div><div class="centerSuit">${card.last.suit}</div><div class="corner br">${card.last.rank}<span>${card.last.suit}</span></div>`;const rule=card.rules[card.last.ruleKey];$('cardRuleDisplay').classList.toggle('empty',!rule);$('cardRuleText').textContent=rule||'No rule was assigned to this card.'}else{slot.className='emptyCard';slot.textContent='Your card appears here.';$('cardRuleDisplay').classList.add('empty');$('cardRuleText').textContent='Draw a card to begin.'}const h=$('cardHistory');h.innerHTML='';if(!card.history.length){h.innerHTML='<div class="sub" style="margin:0">No cards yet.</div>'}else card.history.slice(0,10).forEach(c=>{const d=document.createElement('div');d.className='historyItem';d.innerHTML=`<div class="historyMini ${c.red?'red':''}">${c.joker?'★':esc(c.label)}</div><div><strong>${esc(c.playerName)} — ${esc(c.label)}</strong><span>${esc(card.rules[c.ruleKey]||'No rule')}</span></div>`;h.appendChild(d)})}
  function setCardMode(mode){const setup=mode==='setup';$('cardSetup').classList.toggle('hidden',!setup);$('cardPlay').classList.toggle('hidden',setup);$('cardSetupTab').classList.toggle('active',setup);$('cardPlayTab').classList.toggle('active',!setup);if(!setup&&!card.playing){$('cardStatus').textContent='Start a game first.';return setCardMode('setup')}window.scrollTo({top:0,behavior:'smooth'})}

  const coin={playerCount:2,name:'',players:[{name:'Player 1',coins:1},{name:'Player 2',coins:1}],current:0,round:1,totalFlips:0,history:[],scores:[],last:[],playing:false};
  function ensureCoinPlayers(){while(coin.players.length<coin.playerCount)coin.players.push({name:`Player ${coin.players.length+1}`,coins:1});coin.players=coin.players.slice(0,coin.playerCount)}
  function coinSync(){coin.name=$('coinGameName').value.trim();for(let i=0;i<coin.playerCount;i++){const n=document.querySelector(`[data-coin-name="${i}"]`),c=document.querySelector(`[data-coin-count="${i}"]`);coin.players[i].name=n?.value.trim()||`Player ${i+1}`;coin.players[i].coins=Math.min(20,Math.max(1,parseInt(c?.value,10)||1))}coinTotalUI()}
  function coinCountUI(){const w=$('coinPlayerCount');w.innerHTML='';for(let n=1;n<=4;n++){const b=document.createElement('button');b.type='button';b.textContent=n;b.className=n===coin.playerCount?'active':'';b.addEventListener('click',()=>{coinSync();coin.playerCount=n;ensureCoinPlayers();coinCountUI();coinPlayersSetupUI();coinTotalUI()});w.appendChild(b)}}
  function coinPlayersSetupUI(){ensureCoinPlayers();const w=$('coinPlayersSetup');w.innerHTML='';coin.players.forEach((p,i)=>{const r=document.createElement('div');r.className='coinPlayerRow';r.innerHTML=`<div><span class="label">Player ${i+1} name</span><input class="textInput" data-coin-name="${i}" maxlength="24" value="${esc(p.name)}"></div><div><span class="label">Coins</span><input class="numberInput" data-coin-count="${i}" type="number" inputmode="numeric" min="1" max="20" value="${p.coins}"></div>`;w.appendChild(r)});w.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{coinSync()}))}
  function coinTotalUI(){$('coinTotalCount').textContent=coin.players.slice(0,coin.playerCount).reduce((s,p)=>s+(parseInt(p.coins,10)||1),0)}
  function renderCoinSaved(){const w=$('coinSaved'),items=getStore(COIN_STORAGE);w.innerHTML='';if(!items.length){w.innerHTML='<div class="sub" style="margin:0">No saved coin games yet.</div>';return}items.forEach(item=>{const total=item.players.reduce((s,p)=>s+p.coins,0),d=document.createElement('div');d.className='savedItem';d.innerHTML=`<div class="savedInfo"><strong>${esc(item.name)}</strong><span>${item.playerCount} player${item.playerCount===1?'':'s'} · ${total} coins per round</span></div><div class="savedActions"><button class="tiny load">Load</button><button class="tiny del">Delete</button></div>`;d.querySelector('.load').addEventListener('click',()=>loadCoin(item.id));d.querySelector('.del').addEventListener('click',()=>{setStore(COIN_STORAGE,items.filter(x=>x.id!==item.id));renderCoinSaved()});w.appendChild(d)})}
  function saveCoin(){coinSync();if(!coin.name){$('coinStatus').textContent='Give the coin game a name before saving.';$('coinGameName').focus();return}const items=getStore(COIN_STORAGE),ix=items.findIndex(x=>x.name.toLowerCase()===coin.name.toLowerCase()),item={id:ix>=0?items[ix].id:uid(),name:coin.name,playerCount:coin.playerCount,players:coin.players.map(p=>({...p}))};if(ix>=0)items[ix]=item;else items.unshift(item);setStore(COIN_STORAGE,items);renderCoinSaved();$('coinStatus').textContent=`Saved “${coin.name}”.`}
  function loadCoin(id){const item=getStore(COIN_STORAGE).find(x=>x.id===id);if(!item)return;coin.name=item.name;coin.playerCount=item.playerCount;coin.players=item.players.map(p=>({...p}));$('coinGameName').value=coin.name;coinCountUI();coinPlayersSetupUI();coinTotalUI();$('coinStatus').textContent=`Loaded “${item.name}”.`;window.scrollTo({top:0,behavior:'smooth'})}
  function coinStart(){coinSync();coin.current=0;coin.round=1;coin.totalFlips=0;coin.history=[];coin.last=[];coin.playing=true;coin.scores=coin.players.map(()=>({heads:0,tails:0}));renderCoinPlay();setCoinMode('play')}
  function coinRestart(){coin.current=0;coin.round=1;coin.totalFlips=0;coin.history=[];coin.last=[];coin.scores=coin.players.map(()=>({heads:0,tails:0}));coin.playing=true;renderCoinPlay();$('coinRestartDialog').close()}
  function doCoinFlip(){if(!coin.playing)return;const p=coin.players[coin.current],results=Array.from({length:p.coins},()=>randBool()?'H':'T'),heads=results.filter(x=>x==='H').length,tails=results.length-heads;coin.last=results;coin.scores[coin.current].heads+=heads;coin.scores[coin.current].tails+=tails;coin.totalFlips+=results.length;coin.history.unshift({player:p.name,results:[...results],heads,tails,round:coin.round});coin.current++;if(coin.current>=coin.playerCount){coin.current=0;coin.round++}renderCoinPlay(true)}
  function renderCoinPlay(animate=false){const p=coin.players[coin.current];$('coinTurnBubble').textContent=coin.current+1;$('coinTurnText').textContent=`${p.name}'s turn`;$('coinTitle').textContent=coin.name||'Unsaved Game';$('coinFlipCount').textContent=coin.totalFlips;$('coinRoundCount').textContent=coin.round;$('coinHint').textContent=`${p.name} flips ${p.coins} coin${p.coins===1?'':'s'}.`;[$('coinFlip'),$('coinFlipMobile')].forEach(b=>b.textContent=`Flip ${p.coins} Coin${p.coins===1?'':'s'}`);const grid=$('coinGrid');grid.innerHTML='';if(!coin.last.length)grid.innerHTML='<div class="emptyCard" style="width:150px;height:150px">Flip coins to begin.</div>';else coin.last.forEach(result=>{const c=document.createElement('div');c.className='coin '+(result==='T'?'tails ':'')+(animate?'flipping':'');c.textContent=result==='H'?'H':'T';c.setAttribute('aria-label',result==='H'?'Heads':'Tails');grid.appendChild(c)});const last=coin.history[0];$('headsResult').textContent=last?.heads||0;$('tailsResult').textContent=last?.tails||0;const scores=$('coinScores');scores.innerHTML='';coin.players.forEach((pl,i)=>{const s=coin.scores[i]||{heads:0,tails:0},d=document.createElement('div');d.className='coinScore'+(i===coin.current?' active':'');d.innerHTML=`<div><strong>${esc(pl.name)}</strong><span>${pl.coins} coin${pl.coins===1?'':'s'} per turn</span></div><strong>${s.heads}H / ${s.tails}T</strong>`;scores.appendChild(d)});const hist=$('coinHistory');hist.innerHTML='';if(!coin.history.length)hist.innerHTML='<div class="sub" style="margin:0">No flips yet.</div>';else coin.history.slice(0,10).forEach(h=>{const d=document.createElement('div');d.className='historyItem';d.innerHTML=`<div class="historyMini">${h.heads}H</div><div><strong>${esc(h.player)} · Round ${h.round}</strong><span>${h.heads} heads · ${h.tails} tails</span></div>`;hist.appendChild(d)})}
  function setCoinMode(mode){const setup=mode==='setup';$('coinSetup').classList.toggle('hidden',!setup);$('coinPlay').classList.toggle('hidden',setup);$('coinSetupTab').classList.toggle('active',setup);$('coinPlayTab').classList.toggle('active',!setup);if(!setup&&!coin.playing){$('coinStatus').textContent='Start a game first.';return setCoinMode('setup')}window.scrollTo({top:0,behavior:'smooth'})}

  $('cardSetupTab').addEventListener('click',()=>setCardMode('setup'));$('cardPlayTab').addEventListener('click',()=>setCardMode('play'));$('cardStart').addEventListener('click',cardStart);$('cardSave').addEventListener('click',saveCard);$('cardExamples').addEventListener('click',()=>{cardSync();card.rules={...card.rules,...examples};cardRulesUI();$('cardStatus').textContent='Example rules added.'});$('cardClear').addEventListener('click',()=>{card.rules=Object.fromEntries(ruleKeys.map(k=>[k,'']));cardRulesUI();$('cardStatus').textContent='Rules cleared.'});$('cardDraw').addEventListener('click',cardDraw);$('cardDrawMobile').addEventListener('click',cardDraw);$('deckStack').addEventListener('click',cardDraw);$('deckStack').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();cardDraw()}});$('cardRestart').addEventListener('click',()=>$('cardRestartDialog').showModal());$('cardRestartYes').addEventListener('click',cardRestart);$('cardBackSetup').addEventListener('click',()=>setCardMode('setup'));
  $('coinSetupTab').addEventListener('click',()=>setCoinMode('setup'));$('coinPlayTab').addEventListener('click',()=>setCoinMode('play'));$('coinStart').addEventListener('click',coinStart);$('coinSave').addEventListener('click',saveCoin);$('coinFlip').addEventListener('click',doCoinFlip);$('coinFlipMobile').addEventListener('click',doCoinFlip);$('coinRestart').addEventListener('click',()=>$('coinRestartDialog').showModal());$('coinRestartYes').addEventListener('click',coinRestart);$('coinBackSetup').addEventListener('click',()=>setCoinMode('setup'));
  document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));

  cardCountUI();cardNamesUI();cardRulesUI();renderCardSaved();coinCountUI();coinPlayersSetupUI();coinTotalUI();renderCoinSaved();showScreen('home');
})();
