(() => {
'use strict';
const cv=document.getElementById('world'),c=cv.getContext('2d'),mc=document.getElementById('miniCanvas'),m=mc.getContext('2d');
c.imageSmoothingEnabled=m.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),loc=$('locationLabel'),toast=$('toast'),action=$('actionBtn'),actionLabel=$('actionLabel'),dlg=$('dialogue'),dlgName=$('dialogueName'),dlgText=$('dialogueText'),dlgNext=$('dialogueNext'),portrait=$('portrait'),pc=portrait.getContext('2d');
const journal=$('journal'),dayGrid=$('dayGrid'),mini=$('miniScreen'),miniTitle=$('miniTitle'),miniDay=$('miniDay'),miniSubtitle=$('miniSubtitle'),miniScore=$('miniScore'),miniHelp=$('miniHelp'),miniButtons=$('miniButtons'),miniResult=$('miniResult'),resultTitle=$('resultTitle'),resultText=$('resultText');
const P=window.CHIPIN_WORLD_PROJECT,maps=Object.fromEntries(P.maps.map(x=>[x.name.trim(),x])),town=maps['Town Map'],npcMap=maps['NPC House - Downstairs'],W=160,H=240,STORE='advent-apprentice-v2';
const defs=[
['Holly Tinkerton','TF Gnome B.png','Light Lines','Planning ahead','I have three hundred lights and no intention of untangling them twice.'],
['Bernard Boxwood','TF Gnome A.png','Parcel Push','Organisation','Red labels left, gold labels right, and fragile things nowhere near the reindeer.'],
['Pip Wren','TF Elf B.png','Toy Train Tangle','Attention to detail','Making a toy work once is easy. Making sure it works every time is the job.'],
['Bramble','TF Reindeer Child.png','Reindeer Run','Confidence and control','Everybody says I am too young for the sleigh team. Race me and we will see.'],
['Nutmeg Crumb','TF Gnome B.png','Gingerbread Rush','Timing and preparation','Christmas baking is about having the right thing ready at the right moment.'],
['Rudi Lanternnose','TF Rudolph Child.png','Lantern Maze','Navigation','The nose only lets you see enough to make the next decision.'],
['Melody Bell','TF Elf B.png','Bell Choir','Listening and memory','Anybody can make a noise. The trick is knowing when your note belongs.'],
['Copper','TF Reindeer B.png','Sleigh Slide','Precision','Flying fast is easy. Stopping exactly where you are supposed to is skill.'],
['Bjorn Snowpaw','TF Polar Bear.png','Snow Shift','Problem solving','Move snow from one path and you will put it somewhere else.'],
['Merry Mistle','TF Gnome A.png','Wreath Weaver','Pattern recognition','You have been following my wreaths all week. About time you learned how they are made.'],
['Juniper','TF Reindeer.png','Winter Routes','Route planning','The shortest road is not always the fastest road.'],
['Cocoa Snowpaw','TF Polar Bear Cub.png','Snow Search','Observation','Finding the decorations is fun. Finding them efficiently is the clever bit.'],
['Clove Hearthwick','TF Gnome A.png','Chimney Drop','Spatial thinking','Santa going down the chimney is not the difficult bit. Try the parcels.'],
['Aurora','TF Rudolph Adult B.png','Star Flight','Adapting under pressure','A route can change while you are already flying it.'],
['Felix Ribbon','TF Elf B.png','Perfectly Packed','Efficiency','Paper costs money, ribbon tangles, and boxes are never the shape you want.'],
['Firkin Switchgear','TF Gnome B.png','Workshop Shift','Thinking ahead','Never move something just because you can. Know what happens next.'],
['Bellamy Frost','TF Jesus.png','Bell Tower','Timing','Too early is wrong. Too late is wrong. Christmas has quite a lot of that.'],
['Comet','TF Rudolph Adult.png','Snow Curling','Prediction','Training is not all running. Sometimes you have to beat me at something first.'],
['Nicholas Quill','TF Jesus.png','Christmas Chronicle','Memory and tradition','Traditions are stories people liked enough to repeat.'],
['Ember Hearth','TF Gnome B.png','Christmas Kitchen','Prioritisation','One dinner, twenty-four households, six ovens. Welcome to the busy part.'],
['Northwind','TF Rudolph Adult B.png','Formation','Anticipating others','Eight reindeer do not fly independently. Watch the others.'],
['Mrs Claus','TF Mrs Claus.png','Christmas Control','Coordination','Santa gets one very busy night. The rest of us get December.'],
['Star','TF Rudolph Adult.png','The Long Run','Leadership','Tomorrow everyone will be looking forward. Somebody has to know where we are going.'],
['Santa Claus','TF Santa.png','Christmas Eve','Putting it together','Twenty-three doors. Twenty-three teachers. There is only one thing left to do.']
];
const positions=[[400,688],[272,80],[464,80],[752,80],[944,80],[1120,80],[80,336],[272,336],[464,336],[752,336],[944,336],[1120,336],[80,880],[272,880],[464,880],[752,880],[944,880],[1120,880],[80,1112],[272,1112],[464,1112],[752,1112],[944,1112],[1120,1112]];
const kinds=['rotate','push','rotate','race','sequence','maze','sequence','maze','push','rotate','route','maze','push','race','push','maze','timing','curl','sequence','timing','route','manage','race','final'];
const residents=defs.map((d,i)=>({day:i+1,name:d[0],asset:d[1],game:d[2],skill:d[3],intro:d[4],kind:kinds[i],x:positions[i][0],y:positions[i][1],doorX:positions[i][0]+32,doorY:positions[i][1]+32}));
const house=town.assets.find(a=>a.asset==='house2.png');
const now=new Date(),unlock=now.getMonth()===11?Math.min(24,now.getDate()):24;
$('dayBadge').querySelector('strong').textContent=String(now.getMonth()===11?Math.min(24,now.getDate()):24);
const state={map:'Player House - Bedroom',x:P.initialSpawn.x,y:P.initialSpawn.y,dir:'down',moving:false,anim:performance.now(),cam:{x:0,y:0},resident:null,met:{},done:{},scores:{},jx:0,jy:0};
try{const s=JSON.parse(localStorage.getItem(STORE)||'{}');state.met=s.met||{};state.done=s.done||{};state.scores=s.scores||{}}catch(e){}
let assets=null,last=performance.now(),joyId=null,currentAction=null,queue=[],afterDlg=null,game=null,gameLast=0,finished=false;
const keys=new Set();
function save(){localStorage.setItem(STORE,JSON.stringify({met:state.met,done:state.done,scores:state.scores}))}
function msg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove('show'),1600)}
function activeMap(){return state.map==='NPC House - Downstairs'?npcMap:maps[state.map]}
function mapLabel(){return state.resident&&state.map==='NPC House - Downstairs'?'DAY '+state.resident.day+' · '+state.resident.name.toUpperCase():state.map.toUpperCase()}
function go(name,x,y,r=null){state.map=name;state.x=x;state.y=y;state.resident=r;state.moving=false;loc.textContent=mapLabel();msg(mapLabel())}
function ac(name,frame,w,h){try{let q;if((q=name.match(/^BigSet r(\d+) c(\d+)/)))return assets.frame('BigSet.png',+q[1]*8+(+q[2]),16,16);if((q=name.match(/^Dungeon r(\d+) c(\d+)/)))return assets.frame('Dungeon.png',+q[1]*10+(+q[2]),16,16);if(frame!=null&&w&&h)return assets.frame(name,frame,w,h);return assets.canvas(name)}catch(e){return null}}
function drawAsset(a,camx=0,camy=0){const s=ac(a.asset,a.frame,a.w,a.h),x=Math.round(a.x-camx),y=Math.round(a.y-camy);if(!s){c.fillStyle='#7a6650';c.fillRect(x,y,a.w,a.h);return}c.save();c.translate(x+(a.flipX?a.w:0),y+(a.flipY?a.h:0));c.scale(a.flipX?-1:1,a.flipY?-1:1);c.drawImage(s,0,0,a.w,a.h);c.restore()}
function spr(ctx,name,x,y,dir='down',step=0,size=20){try{const b={down:0,up:4,left:8,right:12}[dir]||0,s=assets.frame(name,b+(step%4),16,16);ctx.drawImage(s,Math.round(x-size/2),Math.round(y-size+3),size,size)}catch(e){ctx.fillStyle='#a9363f';ctx.fillRect(x-size/2,y-size,size,size)}}
function worldDraw(t){const mp=activeMap(),cam=state.cam;c.fillStyle=mp.bg||'#e8eee9';c.fillRect(0,0,W,H);let arr=mp.assets.slice();if(state.map==='Town Map')residents.slice(1).forEach(r=>arr.push(Object.assign({},house,{x:r.x,y:r.y,id:'h'+r.day,layer:1,aboveCharacters:true})));arr.sort((a,b)=>(a.layer||0)-(b.layer||0)||a.y-b.y);arr.filter(a=>!a.aboveCharacters).forEach(a=>drawAsset(a,cam.x,cam.y));if(state.map==='Town Map')residents.forEach(r=>{const x=r.doorX-cam.x,y=r.doorY-cam.y;c.fillStyle=r.day<=unlock?'#d8ae58':'#777';c.fillRect(x-7,y-24,18,10);c.fillStyle='#18231d';c.font='bold 7px monospace';c.textAlign='center';c.fillText(r.day,x+2,y-16)});if(state.map==='NPC House - Downstairs'&&state.resident)spr(c,state.resident.asset,80,112);const st=state.moving?Math.floor((t-state.anim)/150)%4:0;spr(c,'TF Elf A.png',state.x-cam.x,state.y-cam.y,state.dir,st,20);arr.filter(a=>a.aboveCharacters).forEach(a=>drawAsset(a,cam.x,cam.y))}
function blocked(nx,ny){const mp=activeMap(),r=5;if(nx<6||ny<8||nx>mp.width-6||ny>mp.height-5)return true;for(const a of mp.assets)if(a.solid&&nx+r>a.x&&nx-r<a.x+a.w&&ny+r>a.y&&ny-r<a.y+a.h)return true;if(state.map==='Town Map')for(const h of residents.slice(1))if(nx+r>h.x+4&&nx-r<h.x+76&&ny+r>h.y+4&&ny-r<h.y+28)return true;return false}
function dist(x,y){return Math.hypot(state.x-x,state.y-y)}
function add(label,fn,p=1){if(!currentAction||p>currentAction.p)currentAction={label,fn,p}}
function transition(t){const m=P.maps.find(x=>x.id===t.targetMapId);if(m)go(m.name.trim(),t.targetX,t.targetY)}
function talk(r){state.met[r.day]=true;save();dialog(r.name,r.asset,[r.intro,'Your lesson is '+r.skill.toLowerCase()+'.','Head upstairs when you are ready. The room up there is set up for '+r.game+'.'])}
function actions(){currentAction=null;if(state.map==='Town Map'){for(const r of residents)if(dist(r.doorX,r.doorY)<18)add(r.day<=unlock?'ENTER':'DAY '+r.day,()=>r.day<=unlock?go('NPC House - Downstairs',72,200,r):msg('This door opens on December '+r.day+'.'),8)}else if(state.map==='NPC House - Downstairs'&&state.resident){if(dist(80,112)<23)add('TALK',()=>talk(state.resident),10);const stairs=npcMap.transitions.find(t=>t.targetMapId!==town.id),out=npcMap.transitions.find(t=>t.targetMapId===town.id);if(stairs&&dist(stairs.x+8,stairs.y+8)<18)add('UPSTAIRS',()=>state.met[state.resident.day]?openGame(state.resident):msg('Speak to '+state.resident.name+' first.'),9);if(out&&dist(out.x+8,out.y+8)<18)add('OUTSIDE',()=>go('Town Map',state.resident.doorX,state.resident.doorY+24),9)}else for(const t of activeMap().transitions||[])if(dist(t.x+t.w/2,t.y+t.h/2)<17)add(t.targetMapId===town.id?'OUTSIDE':'STAIRS',()=>transition(t),7);action.disabled=!currentAction;action.classList.toggle('ready',!!currentAction);actionLabel.textContent=currentAction?currentAction.label:'ACTION'}
function dialog(name,asset,lines){queue=lines.slice();dlgName.textContent=name;dlg.hidden=false;pc.clearRect(0,0,32,32);spr(pc,asset,16,27,'down',0,28);nextDlg()}
function nextDlg(){if(queue.length){dlgText.textContent=queue.shift();dlgNext.textContent=queue.length?'NEXT':'CLOSE'}else dlg.hidden=true}
dlgNext.onclick=nextDlg;action.onclick=()=>{if(currentAction&&dlg.hidden)currentAction.fn()};
function update(dt,t){if(!dlg.hidden||!journal.hidden||!mini.hidden)return;let x=state.jx,y=state.jy;if(joyId===null){x=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0);y=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0)}const mag=Math.hypot(x,y);if(mag>.12){x/=mag;y/=mag;const sp=54,nx=state.x+x*sp*dt,ny=state.y+y*sp*dt;if(!blocked(nx,state.y))state.x=nx;if(!blocked(state.x,ny))state.y=ny;const d=Math.abs(x)>Math.abs(y)?(x<0?'left':'right'):(y<0?'up':'down');if(!state.moving||d!==state.dir){state.anim=t;state.dir=d}state.moving=true}else state.moving=false;const mp=activeMap();state.cam.x=mp.width>W?Math.max(0,Math.min(mp.width-W,state.x-W/2)):0;state.cam.y=mp.height>H?Math.max(0,Math.min(mp.height-H,state.y-H/2)):0;actions()}
const joy=$('joystick'),knob=$('joyKnob');function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=28,mm=Math.hypot(dx,dy)||1,s=Math.min(1,max/mm),x=dx*s,y=dy*s;knob.style.transform='translate('+x+'px,'+y+'px)';state.jx=x/max;state.jy=y/max}joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(e.pointerId===joyId)joyMove(e)};function joyEnd(e){if(e.pointerId!==joyId)return;joyId=null;state.jx=state.jy=0;knob.style.transform='translate(0,0)'}joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(['arrowleft','arrowright','arrowup','arrowdown',' '].includes(k))e.preventDefault();if(!mini.hidden&&game&&game.key)game.key(k);else if((k===' '||k==='enter')&&currentAction&&dlg.hidden)currentAction.fn()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function renderJournal(){dayGrid.innerHTML='';residents.forEach(r=>{const d=document.createElement('div');d.className='dayCard'+(r.day>unlock?' locked':'')+(state.done[r.day]?' done':'');d.innerHTML='<strong>DAY '+r.day+' · '+r.name+'</strong><span>'+r.game+(state.done[r.day]?' · COMPLETE':'')+'</span>';dayGrid.appendChild(d)})}
$('journalBtn').onclick=()=>{renderJournal();journal.hidden=false};document.querySelector('[data-close="journal"]').onclick=()=>journal.hidden=true;
function setButtons(items){miniButtons.innerHTML='';items.forEach(v=>{const b=document.createElement('button');b.textContent=v[0];b.onclick=v[1];miniButtons.appendChild(b)})}
function done(text){if(finished)return;finished=true;state.done[game.r.day]=true;state.scores[game.r.day]=Math.max(state.scores[game.r.day]||0,Math.round(game.score||0));save();renderJournal();resultTitle.textContent=game.r.game+' complete';resultText.textContent=text;miniResult.hidden=false}
function back(){miniResult.hidden=true;mini.hidden=true;const r=game&&game.r?game.r:state.resident;game=null;go('NPC House - Downstairs',120,168,r)}
$('returnMap').onclick=back;$('resultReturn').onclick=back;$('playAgain').onclick=()=>{miniResult.hidden=true;openGame(state.resident)};$('restartMini').onclick=()=>openGame(state.resident);
function bg(title){m.fillStyle='#f2ead7';m.fillRect(0,0,360,560);m.fillStyle='#173c2a';m.fillRect(0,0,360,36);m.fillStyle='#fff';m.font='bold 14px monospace';m.textAlign='center';m.fillText(title,180,23)}
function cell(x,y,s,fill){m.fillStyle=fill;m.fillRect(x,y,s,s);m.strokeStyle='#304238';m.strokeRect(x,y,s,s)}
function rand(n){return Math.floor(Math.random()*n)}
function makeMaze(){const N=11,g=Array.from({length:N},(_,y)=>Array.from({length:N},(_,x)=>x===0||y===0||x===N-1||y===N-1||Math.random()<.2?1:0));for(let x=1;x<N-1;x++)g[1][x]=0;for(let y=1;y<N-1;y++)g[y][N-2]=0;return{N,g,p:[1,1],goal:[N-2,N-2],moves:0}}
function buildGame(r){
 const kind=r.kind;
 if(kind==='rotate'){let a=Array.from({length:25},()=>rand(4)),target=Array.from({length:25},()=>rand(4));return{r,score:0,draw(){bg(r.game);for(let y=0;y<5;y++)for(let x=0;x<5;x++){const i=y*5+x,px=55+x*50,py=105+y*50;cell(px,py,44,['#a9363f','#d8ae58','#4c7455','#596f91'][a[i]]);m.fillStyle='#fff';m.font='bold 16px monospace';m.fillText('↻',px+22,py+27)}m.fillStyle='#173c2a';m.font='9px monospace';m.fillText('Rotate every tile to match its hidden Christmas alignment.',180,390)},pointer(x,y){const gx=Math.floor((x-55)/50),gy=Math.floor((y-105)/50);if(gx>=0&&gx<5&&gy>=0&&gy<5){const i=gy*5+gx;a[i]=(a[i]+1)%4;this.score+=4;if(a.every((v,i)=>v===target[i]))done('Every piece is aligned correctly.')}}}}
 if(kind==='push'){let p=[1,5],boxes=[[2,4],[3,3],[4,2]],goals=[[5,1],[5,2],[5,3]],moves=0;function mv(dx,dy){let nx=p[0]+dx,ny=p[1]+dy;if(nx<0||ny<0||nx>6||ny>6)return;const bi=boxes.findIndex(b=>b[0]===nx&&b[1]===ny);if(bi>=0){const bx=nx+dx,by=ny+dy;if(bx<0||by<0||bx>6||by>6||boxes.some(b=>b[0]===bx&&b[1]===by))return;boxes[bi]=[bx,by]}p=[nx,ny];moves++;if(goals.every(g=>boxes.some(b=>b[0]===g[0]&&b[1]===g[1])))done('You solved the whole spatial puzzle.')}const g={r,get score(){return Math.max(0,800-moves*5)},draw(){bg(r.game);for(let y=0;y<7;y++)for(let x=0;x<7;x++){const px=40+x*40,py=95+y*40;cell(px,py,36,'#e0d3b4');if(goals.some(q=>q[0]===x&&q[1]===y)){m.strokeStyle='#d8ae58';m.lineWidth=4;m.strokeRect(px+5,py+5,26,26)}}boxes.forEach(q=>{m.fillStyle='#a9363f';m.fillRect(45+q[0]*40,100+q[1]*40,26,26)});spr(m,'TF Elf A.png',58+p[0]*40,126+p[1]*40,'down',0,24)},buttons(){return[['←',()=>mv(-1,0)],['↑',()=>mv(0,-1)],['↓',()=>mv(0,1)],['→',()=>mv(1,0)]]},key(k){if(k==='arrowleft')mv(-1,0);if(k==='arrowright')mv(1,0);if(k==='arrowup')mv(0,-1);if(k==='arrowdown')mv(0,1)}};return g}
 if(kind==='race'){let x=180,t=0,score=0,obs=[];return{r,get score(){return score},update(dt){t+=dt;score+=dt*20;if(Math.random()<dt*1.7)obs.push({x:45+rand(270),y:-20});obs.forEach(o=>o.y+=120*dt);for(const o of obs)if(Math.abs(o.x-x)<26&&Math.abs(o.y-445)<24){score=Math.max(0,score-80);o.y=999}obs=obs.filter(o=>o.y<600);if(t>=24)done('You completed the full run and kept control to the finish.')},draw(){bg(r.game);m.fillStyle='#dbe8ed';m.fillRect(35,50,290,500);obs.forEach(o=>{m.fillStyle='#fff';m.beginPath();m.arc(o.x,o.y,18,0,7);m.fill()});spr(m,r.asset,x,470,'up',1,32);m.fillStyle='#173c2a';m.fillText('TIME '+Math.max(0,24-t).toFixed(1),180,520)},buttons(){return[['LEFT',()=>x=Math.max(55,x-35)],['RIGHT',()=>x=Math.min(305,x+35)]]},key(k){if(k==='arrowleft')x=Math.max(55,x-25);if(k==='arrowright')x=Math.min(305,x+25)}}}
 if(kind==='sequence'){let seq=[rand(4),rand(4),rand(4)],inp=[],show=true,clock=0,round=0,score=0;return{r,get score(){return score},update(dt){clock+=dt;if(show&&clock>seq.length*.65+.4){show=false;clock=0}},draw(){bg(r.game);for(let i=0;i<4;i++){const on=show&&seq[Math.floor(clock/.65)]===i;m.fillStyle=on?'#ffe76a':['#a9363f','#d8ae58','#4c7455','#596f91'][i];m.beginPath();m.arc(70+i*75,255,28,0,7);m.fill();m.fillStyle='#fff';m.fillText(i+1,70+i*75,260)}m.fillStyle='#173c2a';m.fillText(show?'WATCH':'YOUR TURN',180,360)},buttons(){return[1,2,3,4].map((n,i)=>[''+n,()=>{if(show)return;if(i===seq[inp.length]){inp.push(i);score+=20;if(inp.length===seq.length){round++;if(round>=5)return done('You completed five increasingly difficult patterns.');seq.push(rand(4));inp=[];show=true;clock=0}}else{inp=[];score=Math.max(0,score-20)}}])}}}
 if(kind==='maze'){const q=makeMaze();function mv(dx,dy){const nx=q.p[0]+dx,ny=q.p[1]+dy;if(!q.g[ny]||q.g[ny][nx])return;q.p=[nx,ny];q.moves++;if(nx===q.goal[0]&&ny===q.goal[1])done('You found the route through the challenge.')}return{r,get score(){return Math.max(0,900-q.moves*4)},draw(){bg(r.game);for(let y=0;y<q.N;y++)for(let x=0;x<q.N;x++){const d=Math.hypot(x-q.p[0],y-q.p[1]);if(d<4.5)cell(38+x*26,90+y*26,23,q.g[y][x]?'#4d6255':'#dbcfae')}m.fillStyle='#d8ae58';m.fillRect(43+q.goal[0]*26,95+q.goal[1]*26,13,13);spr(m,'TF Elf A.png',49+q.p[0]*26,116+q.p[1]*26,'down',0,22)},buttons(){return[['←',()=>mv(-1,0)],['↑',()=>mv(0,-1)],['↓',()=>mv(0,1)],['→',()=>mv(1,0)]]},key(k){if(k==='arrowleft')mv(-1,0);if(k==='arrowright')mv(1,0);if(k==='arrowup')mv(0,-1);if(k==='arrowdown')mv(0,1)}}}
 if(kind==='route'){const N=7,terrain=Array.from({length:49},()=>1+rand(3));let p=0,cost=0;function mv(dx,dy){const x=p%N,y=Math.floor(p/N),nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=N||ny>=N)return;p=ny*N+nx;cost+=terrain[p];if(p===48)done('Route complete. Your total travel cost was '+cost+'.')}return{r,get score(){return Math.max(0,1000-cost*15)},draw(){bg(r.game);for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=y*N+x,px=40+x*40,py=100+y*40;cell(px,py,36,['#ddd0ad','#d8e8ee','#adc7d1'][terrain[i]-1]);m.fillStyle='#18231d';m.font='8px monospace';m.fillText(terrain[i],px+18,py+21)}m.fillStyle='#a9363f';m.fillRect(46+(p%N)*40,106+Math.floor(p/N)*40,24,24)},buttons(){return[['←',()=>mv(-1,0)],['↑',()=>mv(0,-1)],['↓',()=>mv(0,1)],['→',()=>mv(1,0)]]}}}
 if(kind==='timing'){let a=0,hits=0,score=0;function hit(){let d=Math.abs(((a%(Math.PI*2))+Math.PI*2)%(Math.PI*2)-Math.PI/2);d=Math.min(d,Math.PI*2-d);if(d<.3){hits++;score+=100;if(hits>=8)done('Eight perfect timings. Lesson complete.')}else score=Math.max(0,score-25)}return{r,get score(){return score},update(dt){a+=2.3*dt},draw(){bg(r.game);m.strokeStyle='#173c2a';m.lineWidth=8;m.beginPath();m.arc(180,270,120,0,7);m.stroke();m.strokeStyle='#d8ae58';m.lineWidth=18;m.beginPath();m.arc(180,270,120,Math.PI/2-.3,Math.PI/2+.3);m.stroke();m.fillStyle='#a9363f';m.beginPath();m.arc(180+Math.cos(a)*120,270+Math.sin(a)*120,13,0,7);m.fill();m.fillStyle='#173c2a';m.fillText('PERFECT '+hits+'/8',180,450)},buttons(){return[['GO',hit]]}}}
 if(kind==='curl'){let aim=0,shots=0,score=0;function shoot(){const precision=Math.max(0,100-Math.abs(aim)*80-rand(35));score+=precision;shots++;aim=(Math.random()-.5)*1.5;if(shots>=6)done('Six stones played. Your accuracy score was '+Math.round(score)+'.')}return{r,get score(){return score},update(dt){aim+=Math.sin(performance.now()/500)*dt*.8},draw(){bg(r.game);m.fillStyle='#d9e8ee';m.fillRect(40,60,280,470);for(const rr of [85,55,28]){m.strokeStyle=rr===28?'#a9363f':'#6a98aa';m.lineWidth=6;m.beginPath();m.arc(180,140,rr,0,7);m.stroke()}m.strokeStyle='#173c2a';m.beginPath();m.moveTo(180,480);m.lineTo(180+Math.sin(aim)*120,360);m.stroke();m.fillStyle='#173c2a';m.fillText('SHOTS '+shots+'/6',180,525)},buttons(){return[['AIM ←',()=>aim-=.15],['THROW',shoot],['AIM →',()=>aim+=.15]]}}}
 if(kind==='manage'){let bars=[70,65,75,60],t=0,score=0;function boost(i){bars[i]=Math.min(100,bars[i]+25)}return{r,get score(){return score},update(dt){t+=dt;bars=bars.map((v,i)=>v-(5+i)*dt);score=t*20;if(bars.some(v=>v<=0))return done('The shift ended. Replay to keep every system healthy longer.');if(t>=45)done('You kept every Christmas system running for a full shift.')},draw(){bg(r.game);['WORKSHOP','SLEIGH','KITCHEN','POST'].forEach((n,i)=>{const y=120+i*90;m.fillStyle='#173c2a';m.fillText(n,180,y);m.fillStyle='#57252a';m.fillRect(55,y+16,250,24);m.fillStyle=bars[i]<25?'#e24a50':'#4e8a5b';m.fillRect(55,y+16,250*bars[i]/100,24)})},buttons(){return[['TOOLS',()=>boost(0)],['FEED',()=>boost(1)],['OVEN',()=>boost(2)],['SORT',()=>boost(3)]]}}}
 let phase=0,score=0,progress=0,land=25,del=0;return{r,get score(){return score},update(dt){if(phase===1){progress+=20*dt;score+=dt*3;if(progress>=100)phase=2}},draw(){bg(r.game);m.fillStyle='#173c2a';m.font='bold 15px monospace';m.fillText(['PLAN THE ROUTE','FLY THE NIGHT','LAND THE SLEIGH','DELIVER THE GIFTS'][phase],180,90);if(phase===0){for(let i=0;i<6;i++){m.fillStyle=i<progress?'#d8ae58':'#d8cba9';m.fillRect(65+i*42,180,32,32)}}if(phase===1){m.fillStyle='#102a42';m.fillRect(40,145,280,270);spr(m,'TF Rudolph Adult.png',180,285,'up',1,34);m.fillStyle='#d8ae58';m.fillRect(40,380,280*Math.min(1,progress/100),18)}if(phase===2){m.strokeStyle='#d8ae58';m.lineWidth=6;m.strokeRect(110,220,140,80);m.fillStyle='#a9363f';m.fillRect(160+land,180,40,30)}if(phase===3){m.fillStyle='#7a543b';m.fillRect(140,170,80,180);m.fillStyle='#a9363f';m.fillRect(165,300-del*35,30,30)}},buttons(){if(phase===0)return[['ROUTE',()=>{progress++;score+=20;if(progress>=6){phase=1;progress=0}}]];if(phase===1)return[['STEADY',()=>score+=1]];if(phase===2)return[['LEFT',()=>land=Math.max(-40,land-10)],['LAND',()=>{if(Math.abs(land)<15){phase=3;score+=200}else score=Math.max(0,score-20)}],['RIGHT',()=>land=Math.min(40,land+10)]];return[['DELIVER',()=>{del++;score+=100;if(del>=3)done('You planned the route, flew it, landed safely and completed the Christmas Eve deliveries.')}]]}}
}
const helps={
1:'Rotate the tiles until every Christmas-light piece is aligned.',2:'Push every parcel onto a gold delivery square.',3:'Rotate the track pieces into the correct railway layout.',4:'Dodge the snowbanks and keep control to the finish.',5:'Watch the order, then repeat the recipe sequence.',6:'Your lantern reveals only nearby tiles. Find the far corner.',7:'Watch the bells, then repeat the pattern.',8:'Navigate the icy route to the target without losing your way.',9:'Push the snow piles into the marked clearing spaces.',10:'Rotate every wreath segment into its correct position.',11:'Reach the far corner while keeping your route cost low.',12:'Search the snowfield and find the hidden target route.',13:'Push the present blocks into the correct chimney positions.',14:'Fly through the storm and avoid every cloud bank you can.',15:'Fit all gifts into their correct packing spaces.',16:'Navigate the shifting workshop maze to the toy.',17:'Press GO when the moving marker crosses the gold zone.',18:'Aim and throw six snowballs as accurately as possible.',19:'Remember the story pattern and repeat it correctly.',20:'Time each kitchen action precisely.',21:'Move the formation along the most efficient route.',22:'Keep all four Christmas systems healthy for a full shift.',23:'Stay in control through the long senior reindeer run.',24:'Complete the final four-part Christmas Eve test.'
};
function openGame(r){state.resident=r;finished=false;game=buildGame(r);mini.hidden=false;miniResult.hidden=true;miniDay.textContent='DAY '+r.day;miniTitle.textContent=r.game;miniSubtitle.textContent=r.name+' · '+r.skill;miniHelp.textContent=helps[r.day];setButtons(game.buttons?game.buttons():[]);gameLast=performance.now();requestAnimationFrame(gameLoop)}
mc.onpointerdown=e=>{if(!game||!game.pointer)return;const r=mc.getBoundingClientRect();game.pointer((e.clientX-r.left)*360/r.width,(e.clientY-r.top)*560/r.height)};
function gameLoop(t){if(mini.hidden||!game)return;const dt=Math.min(.05,(t-gameLast)/1000);gameLast=t;if(!finished)game.update&&game.update(dt);game.draw();miniScore.textContent=Math.max(0,Math.round(game.score||0));if(game.r.kind==='final'&&!finished)setButtons(game.buttons());requestAnimationFrame(gameLoop)}
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt,t);worldDraw(t);requestAnimationFrame(loop)}
VillagePixelAssets.ready.then(a=>{assets=a;loc.textContent=mapLabel();renderJournal();requestAnimationFrame(loop)}).catch(e=>{console.error(e);msg('Could not load Christmas assets')});
})();